var TRADI_DP_BRAND_LIST = [
    'abadi jmk group',
    'agatri',
    'alibaba store',
    'aneka elektronik',
    'aneka meubel & elektronik',
    'asiang com',
    'ask jaya cell',
    'aurora',
    'bandara ponsel',
    'bayang bayang langit',
    'bedjo tech',
    'bgp',
    'bintank cell',
    'biz telekom',
    'cahaya baru artha abadi',
    'changfong ponsel',
    'discovery cell',
    'duta ponsel',
    'free cell',
    'galaxy gadget',
    'garuda teknik',
    'gh shop',
    'global communication',
    'gondrong cell',
    'guffy cell',
    'gumilar',
    'harmony ponsel',
    'hoki jaya sentosa',
    'ide komunika',
    'indo bismar',
    'isob gadget',
    'jc my phone',
    'jc phone',
    'jh phone',
    'kana',
    'kana manado',
    'karya cell',
    'langgeng djoyo',
    'las vegas',
    'like phonecell',
    'mackindo jaya',
    'maraphone',
    'max primera telecom',
    'media cell',
    'media jaya cell',
    'mega selindo',
    'mitra agung',
    'muraiki',
    'naga mas group',
    'okey megah perkasa',
    'pasar ponsel',
    'pertemuan cellular',
    'pluto sellular',
    'prima elektronik banjaran',
    'pusat hape',
    'puskrip',
    'raja ponsel',
    'sahabat celullar',
    'sinar jaya cellular',
    'sinar mas',
    'sms shop',
    'sriwijaya selular',
    'tangs ponsel',
    'tele global indo',
    'teman group',
    'terminal phone',
    'timses mandau',
    'toko tangga mas',
    'toko tasik',
    'top deal electronics',
    'top phone shop',
    'trio sukses',
    'wewe',
    'wijaya cellular',
    'wkm jaya',
    'yy mobile',        
    'top indo maju 001 - top cell atrium mall panakukang',
    'top indo maju 008 - top cell xiaomi shop rappocini'];

var TRADI_DP_MERCHANT_EXCLUDE = [
    'pluto sellular 13 - prima sellular street',
    'jc my phone 03 - kulim',
    'sinar mas 30 - selluler pusat',
    'toko tasik 01 - star centre sumedang',
    'toko tasik 02 - star komunika sumedang',
    'toko tasik 03 - elektronik sumedang',
    'bgp 02 pgc',
    'bgp 03 pgc',
    'bgp 05 pgc',
    'asia jaya 14 - asia jaya store plaza marina',
    'maraphone 001 - plasa simpang lima 01',
    'maraphone 003 - plasa simpang lima 03',
    'ask jaya cell 01 - ask cell cimindi',
    'ask jaya cell 02 - ask cell cimindi 2',
    'ask jaya cell 03 - ask cell cijerah',
    'ask jaya cell 04 - ask cell ujungberung',
    'ask jaya cell 05 - ask cell ujungberung 2',
    'ask jaya cell 06 - ask cell cicalengka',
    'aurora 01 - pamulang siliwangi',
    'aurora 02 - pamulang surya kencana',
    'aurora 03 - pamulang square d8',
    'aurora 04 - pamulang square d9',
    'aurora 05 - pamulang square d6',
    'las vegas 11 - mobile store kapas krampung',
    'las vegas 13 - mobile store gresik pangsud',
    'las vegas 15 - mobile store gresik gkb 2',
    'karya cell 01 - karya cell ciputat',
    'karya cell 02 - gallery phone cipayung',
    'karya cell 03 - best phone bsd',
    'like phonecell 01 - like phonecell majalaya',
    'like phonecell 02 - suka phone cell rancaekek',
    'mega selindo 01 mbh',
    'mega selindo 02 perumnas 3',
    'mega selindo 03 mi shop perumnas 3',
    'mega selindo 05 gosaka',
    'mega selindo 06 mbh',
    'pluto sellular 01 - pluto sellular 1',
    'pluto sellular 02 - pluto sellular 2',
    'pluto sellular 03 - pluto sellular 3',
    'pluto sellular 04 - prima sellular 1',
    'pluto sellular 05 - prima sellular 2',
    'pluto sellular 06 - utama sellular',
    'pluto sellular 07 - pluto sellular 5',
    'pluto sellular 08 - xiaomi store',
    'pluto sellular 09 - vivo store',
    'pluto sellular 10 - vivo store',
    'pluto sellular 11 - xiaomi store',
    'puskrip 001 - rungkut madya',
    'puskrip 003 - siwalan kerto',
    'puskrip 004 - rungkut tengah',
    'puskrip 005 - rungkut kidul',
    'puskrip 007 - pogot',
    'puskrip 008 - gunung anyar',
    'puskrip 009 - merr',
    'puskrip 016 - betr0',
    'maraphone 002 - plasa simpang lima 02',
    'sinar mas 01 - selluler 1',
    'sinar mas 03 - selluler lt. dasar ii',
    'sinar mas 04 - selluler 3 reborn',
    'sinar mas 05 - selluler spp',
    'sinar mas 06 - m2 new',
    'sinar mas 10 - selluler tlogosari',
    'sinar mas 11 - sms selluler tlogosari',
    'sinar mas 12 - selluler shop tlogosari',
    'sinar mas 14 - sms selluler ngaliyan ii',
    'sinar mas 15 - selluler banyumanik',
    'sinar mas 17 - selluler karangawen',
    'sinar mas 18 - selluler kaliwungu',
    'sinar mas 19 - selluler veteran - kudus',
    'sinar mas 20 - kudus simpang 7 - kudus',
    'sinar mas 21 - sms selluler menara - kudus',
    'sinar mas 22 - selluler jepara - mayong',
    'sinar mas 23 - selluler serayu - tegal',
    'sinar mas 24 - selluler kartini - tegal',
    'sinar mas 25 - selluler pancasila - tegal',
    'sinar mas 26 - selluler sudibyo - tegal',
    'sinar mas 27 - selluler shop pancasila - tegal',
    'sinar mas 28 - bumiayu - brebes',
    'sinar mas 29 - selluler salatiga',
    'sms shop 01 - display simpanglima',
    'sms shop 04 - depan simpanglima',
    'sms shop 05 - atas simpanglima',
    'sms shop 06 - mega simpanglima',
    'sms shop 07 - xiaomi simpanglima',
    'sms shop 12 - sambiroto',
    'sms shop 13 - gajah',
    'sms shop 14 - lampersari',
    'sms shop 16 - pemuda',
    'sms shop 17 - banyumanik 1',
    'sms shop 18 - banyumanik 2',
    'sms shop 19 - mijen boja',
    'sms shop 21 - ungaran 2',
    'sms shop 22 - babadan',
    'sms shop 24 - ambarawa 2',
    'sms shop 26 - demak',
    'sms shop 27 - purwodadi 1',
    'sms shop 28 - purwodadi 2',
    'sms shop 29 - jepara',
    'sms shop 30 - salatiga kosambi',
    'hoki jaya sentosa 001 - rajawali cell tlogosari',
    'hoki jaya sentosa 002 - rajawali cell kaliwungu i',
    'hoki jaya sentosa 003 - rajawali cell kaliwungu ii',
    'hoki jaya sentosa 004 - sinar cell tlogosari',
    'hoki jaya sentosa 005 - nagasakti cell tlogosari',
    'hoki jaya sentosa 007 - indocell tlogosari',
    'hoki jaya sentosa 008 - indocell sambiroto',
    'hoki jaya sentosa 009 - indocell banyumanik',
    'hoki jaya sentosa 010 - indocell ungaran',
    'hoki jaya sentosa 012 - indocell mijen',
    'hoki jaya sentosa 013 - indocell kaliwungu',
    'hoki jaya sentosa 014 - indocell wolter',
    'media cell 01 - media cell',
    'media cell 02 - seni abadi',
    'alibaba store 011 - original store grosir pasuruan',
    'alibaba store 013 - original store pandaan',
    'biz telekom 08 - bismar ponsel pasuruan',
    'sms shop 02 - tlogosari 3',
    'sms shop 10 - tlogosari 1',
    'sms shop 11 - tlogosari 2',
    'jc phone 02 kramat jati',
    'tele global indo 018 - telering yogyakarta 1',
    'tele global indo 027 - telering yogyakarta 2 ( ses yogya )',
    'tele global indo 041 - telering godean yogya',
    'mitra agung 01 - mitra agung electronic',
    'sms shop 25 - mranggen',
    'hoki jaya sentosa 011 - indocell thamrin',
    'hoki jaya sentosa 015 - indocell mranggen',
    'sinar mas 16 - selluler mranggen',
    'pertemuan cellular 010 - oppo store',
    'pertemuan cellular 02 - tuparev',
    'pertemuan cellular 03 - brigpol sukama',
    'pertemuan cellular 04 - telukjambe',
    'pertemuan cellular 05 - dewi sartika',
    'wkm jaya 01 - ryzla phone shop',
    'wkm jaya 02 - laku laku 1',
    'wkm jaya 03 - laku laku 2',
    'wkm jaya 04 - laku laku 3',
    'wkm jaya 05 - jtc mobile phone shop',
    'wkm jaya 06 - djogja cell',
    'aneka elektronik 01 - mall cikampek',
    'aneka elektronik 02 - bike',
    'asiang com 01 - dumai',
    'sinar mas 31 - huawei store ciputra',
    'sinar mas 32 - huawei store paragon',
    'like phonecell 03 - bless mobile ciparay',
    'kana 01 - kana computer gejayan',
    'kana 02 - jj komputer',
    'kana 03 - lenovo exclusive store by kana',
    'kana 04 - asus exclusive store by kana',
    'langgeng djoyo 003 - lancar djoyo cell gkb gresik',
    'sms shop 32 - sampangan',
    'sms shop 33 - simongan',
    'prima elektronik banjaran 02 - prima elektronik gading soreang'
];

var abtestUniqueId = mainApplicationCreditLimitOrderId == null ? "static-bucket-id" : mainApplicationCreditLimitOrderId;

var mandatory_dp_tradi_experiment = abTestingHelper.getVariation(abtestUniqueId, 'mandatory_dp_tradi_experiment', 'default_value');

var experiment_offline = abTestingHelper.getVariation(abtestUniqueId, 'offline_simplification_ab_test_2025', 'default_value');

/*Default rate key assignment*/
var dp_rate = 0;
var rate_key_result = merchantCreditRateGroupKey;
var isTrxAllowedToUsePromo = true;
var userPromoRiskGrade = '';

/* offlineFeatures */
var userLastActivitySegment = offlineFeatures['userTransactionHistoryFeatures']['userLastActivitySegment'] == null ? "-99" : offlineFeatures['userTransactionHistoryFeatures']['userLastActivitySegment'];
var sumPaymentVaBeforeTrx = offlineFeatures['userTransactionHistoryFeatures']['sumPaymentVaBeforeTrx'] == null ? -99 : offlineFeatures['userTransactionHistoryFeatures']['sumPaymentVaBeforeTrx'];

var VA_MERCHANTS = [
    '77337991-bf38-11ee-a258-31e5ebb41a87' /*agoda*/
    ,'4ede4340-ab7b-11ee-9642-9f3f449c6c33' /*lazada*/
    ,'826b91a3-a0b0-11ee-90cf-23cf2d34ee74' /*shopee*/
    ,'184ab49f-ab7b-11ee-8196-87e351c1a74e' /*tiktok*/
    ,'209b4e8b-7324-11ee-9749-abb1dc7c3e41' /*tokopedia*/
    ,'642cbedd-b99a-11ee-9b3e-fbaefd543359' /*zalora*/
    ,'fe70c52c-7588-11ef-b98b-5754b239ed4d' /*traveloka*/
];

var OFFLINE_PARENT_MERCHANT_VERY_LOW_RISK = [
  'IBOX','GTN','GAN','DIGIMAP','DIGIPLUS','PLANETGADGET','MEGALLERY','MITRAHUBINDONESIA','CELULLARWORLD'
];

var OFFLINE_MERCHANT_LOW_RISK = [
  'MII URBAN REPUBLIC 054 - URBAN REPUBLIC DUTA MALL BANJARMASIN','ORISKIN 54 - MALL CIPUTRA SERAYA PEKANBARU', 'ADVANCE 134 - LAMPUNG CITY MALL', 'EAR 613 - ERAFONE GRESSMALL', 'ERABLUE 11 - ERABLUE ELECTRONICS KUTABUMI', 'DUETTO AUDIO DAN LAMPU 002 - FORTINO PRO AUDIO MUSIC', 'ERABLUE 21 - ERABLUE ELECTRONICS RAYA PARUNG', 'IBOX 23 - KOTA KASABLANKA', 'IBOX 79 - EPICENTRUM LOMBOK', 'GAN 14 - HELLO BUAH BATU', 'ELECTRONIC CITY 11 - KRAMAT JATI', 'RUMAH GADGET 001 - LIKE NEW', 'MAXI STORE 02 - MAXI STORE ALAUDDIN', 'GTN 251 - BLIBLI STORE AEON MALL TANJUNG BARAT', 'YOGYA 24 - GRIYA GRAND MAJALAYA', 'LOTTE GROSIR 16- CIKARANG', 'ERABLUE 27 - ERABLUE ELECTRONICS PONDOK PETIR', 'IBOX 63 - BANDUNG ELECTRONIC CENTER', 'ERABLUE 57 - ERABLUE ELECTRONICS KRESEK', 'IBOX 132 - IBOX SKA MALL PEKANBARU', 'GTN 144 - BLIBLI STORE THE PARK SAWANGAN DEPOK', 'SARI BUNGA 001 - BADILAN AYANI', 'ABSOLUTEFIT MITRA INDONESIA 002 - ABSOLUTEFIT CENGKARENG', 'GAN 16 - HELLO KALIBATA CITY', 'EAR 06 - MEGASTORE CIBINONG CITY MALL', 'IBOX 84 - IBOX LIPPO PLAZA MALL SIDOARJO', 'ABSOLUTEFIT MITRA INDONESIA 004 - ABSOLUTEFIT KEBAYORAN LAMA', 'ELECTRONIC CITY 19 - RUKO PEMUDA', 'TOPSELL PLAZA 004 - JOMBANG', 'EAR 68 - ERAFONE MALL KOTA KASABLANKA', 'IBOX 118 - IBOX PARAGON SEMARANG', 'JEFINDO TEKNOLOGI 01 - PUSAT', 'HARTONO ELEKTRONIK 02 - BGJ', 'ORISKIN 18 - DIY', 'CELULLAR WORLD 17 - ARENA LIKE NEW TEUKU UMAR', 'ERABLUE 06 - ERABLUE ELECTRONICS HOS COKROAMINOTO', 'PURA PURA PONSEL 003 - DENPASAR BARAT', 'WILLFITNESS 14 - TEGALSARI SURABAYA', 'ERABLUE 42 - ERABLUE ELECTRONICS PUSPITEK', 'ERABLUE 28 - ERABLUE ELECTRONICS BOJONG SARI LAMA', 'PLANET GADGET 02 - SEP TEUKU UMAR 84', 'UFO 19 - UFO TEUKU UMAR', 'IBOX 175 - IBOX PANCA USAHA MATARAM', 'IBOX 127 - IBOX SOLO PARAGON MALL', 'FITHUB 65 - SUNSET ROAD', 'ERABLUE 84 - ERABLUE ELECTRONICS BUARAN RAYA', 'ELECTRONIC CITY 15 - RUKO BUARAN', 'EAR 15 MEGASTORE SUPERMALL KARAWACI', 'ORISKIN 27 - MALANG', 'DEVSTORE 002 - NEW GATSU', 'IBOX 45 - LIVING WORLD PEKANBARU', 'PLANET GADGET 05 - TABANAN', 'KAWAN LAMA SELMA 31 - MEGA MALL MANADO', 'ERABLUE 54 - ERABLUE ELECTRONICS MAUK', 'MII URBAN REPUBLIC 046 - URBAN REPUBLIC SUMMARECON MALL SERPONG', 'IBOX 76 - WTC ( WORLD TRADE CENTER )', 'IBOX 68 - PLAZA ASIA TASIKMALAYA', 'GRAMEDIA 483 CILEUNGSI', 'PUTRA NIAGA LESTARI 01 - PONDOK ELEKTRONIK BANJARMASIN', 'IBOX 40 - THE PARK SAWANGAN', 'SJS PLAZA PADANG 01 - SJS PLAZA PADANG', 'IBOX 114 - IBOX SOEKARNO HATTA SUHAT MALANG', 'KAWAN LAMA SELMA 49 - THE PARK KENDARI', 'PLANET GADGET 01 - SES TEUKU UMAR 06', 'JURAGAN STORE MANDIRI 006 - JURAGAN STORE BANJARMASIN', 'HYPERMART 460 CITRA RAYA', 'ERABLUE 30 - ERABLUE ELECTRONICS DURI KOSAMBI', 'EAR 09 - MEGASTORE MARGO CITY', 'IBOX 59 - RITA MALL PURWOKERTO', 'GTN 256 - BLIBLI STORE PAKUWON MALL BEKASI', 'ERABLUE 62 - ERABLUE ELECTRONICS BENDA PERMAI RAYA', 'ELECTRONIC CITY 53 - BOGOR TRADE MALL', 'EAR 248 - ERAFONE RUKO KOPO BANDUNG', 'GTN 188 - BLIBLI STORE LIVING WORLD PEKANBARU', 'DIGIMAP 12 - DIGIMAP AEON MALL SENTUL', 'EAR 433 - RUKO HOS COKROAMINOTO CIAMIS', 'GAN 10 - HELLO MARGONDA DEPOK', 'ABSOLUTEFIT MITRA INDONESIA 003 - ABSOLUTEFIT TANJUNG PRIOK', 'ERABLUE 03 - ERABLUE ELECTRONICS MARGONDA', 'ELECTRONIC CITY 52 - JATINANGOR', 'IBOX 29 - MALL KELAPA GADING', 'IBOX 58 - CIPUTRA SEMARANG', 'CELLULAR WORLD 01 - TEUKU UMAR', 'IBOX 133 - IBOX CIBINONG CITY MALL', 'NEW STORE TANGCITY 01 - TANGCITY MALL', 'GAN 02 - HELLO LIPPO MALL CIKARANG', 'YOGYA 25 - GRIYA CICALENGKA', 'WILLFITNESS 11 - KOSAMBI', 'IBOX 52 - AMBARUKMO PLAZA YOGYAKARTA', 'IBOX 178 - ROYAL PLAZA SURABAYA', 'ANYELIR PONSEL 001 - NEW KESIMAN DENPASAR', 'ERABLUE 20 - ERABLUE ELECTRONICS SATU MARET', 'DIGIMAP 64 - DIGIMAP MALANG TOWN SQUARE', 'PLANET GADGET 15 - PONDOK BAMBU', 'FITHUB 53 - BALI TEUKU UMAR', 'DIGIMAP 56 - DIGIMAP CITIMALL DUMAI', 'KAWAN LAMA INFORMA 070 LP PETTARANI MKS', 'EAR 832 - ERAFONE RUKO SUDIRMAN PEKANBARU', 'IBOX 97 - IBOX MALL RATU INDAH MAKASSAR', 'OKE SHOP 53 OKESHOP MAL PANAKUKANG (U82)', 'GTN 195 - BLIBLI STORE BLUE BINTARO PLAZA', 'GTN 234 - BLIBLI STORE BLUE ITC BSD', 'IBOX 77 - MALL OLYMPICE GARDEN', 'IBOX 137 - IBOX SAMARINDA CENTRAL PLAZA', 'JURAGAN STORE MANDIRI 001 - JURAGAN MALL STORE AYANI BANJARBARU KM 36', 'IBOX 78 - TRANS STUDIO MALL BALI', 'IBOX 90 - IBOX LIVING WORLD DENPASAR', 'DIGIMAP 16 - DIGIMAP LIPPO PLAZA KRAMAT JATI', 'DIGIMAP 53 - DIGIMAP PALEMBANG INDAH MALL', 'TOKO ALPINE 01 - TOKO ALPINE PERINTIS MAKASAR', 'IBOX 37 - CIPUTRA CITRARAYA TANGERANG', 'EAR 64 - ERAFONE SUMARECON MALL BEKASI', 'IBOX 06 - BOTANI SQUARE BOGOR', 'GTN 59 - TUKAR TAMBAH CCM', 'ERABLUE 33 - ERABLUE ELECTRONICS RAYA CURUG', 'ERABLUE 48 - ERABLUE ELECTRONICS KH HASYIM ASHARI', 'GTN 190 - BLIBLI STORE BLUE MALL PANAKKUKANG', 'GTN 117 - TUKAR TAMBAH TEUKU UMAR BALI', 'ERABLUE 41 - ERABLUE ELECTRONICS CEGER RAYA', 'FITHUB 34 - BALI RENON', 'KAWAN LAMA INFORMA ELEKTRONIK 86 - CITIMALL GARUT', 'IBOX 110 - IBOX PLAZA ASIA SUMEDANG', 'IBOX 86 - IBOX GATOT SUBROTO BALI', 'ELECTRONIC CITY 23 - RUKO JABABEKA', 'EAR 325 - ERAFONE PLAZA AMBARUKMO', 'IBOX 122 - IBOX SUDIRMAN PEKANBARU', 'ERABLUE 45 - ERABLUE ELECTRONICS H NAWI', 'IBOX 57 - DP MALL SEMARANG', 'ELECTRONIC CITY 34 - UJUNG MENTENG', 'IBOX 81 - LIPPO MALL KUTA (KUTA ICON) BALI', 'EAR 07 - ERAFONE 2 BOTANI SQUARE', 'GTN 202 - BLIBLI STORE BLUE TANGERANG CITY', 'CELLULAR WORLD 09 - E WORLD', 'IBOX 53 - HARTONO YOGYAKARTA', 'IBOX 80 - TEUKU UMAR BALI', 'GTN 156 - BLIBLI STORE SUPERMALL KARAWACI', 'EAR 665 - ERAFONE MEGASTORE MALL PANAKKUKANG', 'IBOX 160 - IBOX PATTIMURA PADANG', 'EAR 899 - ERAFONE RUKO PRAYA', 'ABSOLUTEFIT MITRA INDONESIA 005 - ABSOLUTEFIT MENTENG', 'IBOX 34 - FLAGSHIP SUMMARECON MALL SERPONG', 'HARTONO ELEKTRONIK 06 - PIN', 'ERABLUE 29 - ERABLUE ELECTRONICS KARANG TENGAH JAKARTA', 'GTN 111 - BLIBLI STORE GANDARIA CITY', 'ABSOLUTEFIT MITRA INDONESIA 006 - ABSOLUTEFIT KEBON JERUK XTENSION', 'EAR 434 - MEGASTORE RUKO TASIKMALAYA', 'PERDANA KOMUNIKASI 001 - PLATINUM STORE KUANINO KUPANG', 'MITRA10 033 - SUNAN GUNUNG JATI CRB', 'FITHUB 79 - GATSU TIMUR', 'EAR 51 - MEGASTORE BX CHANGE', 'EAR 829 - ERAFONE MEGASTORE RUKO PANAM PEKANBARU', 'SARI BUNGA 002 - BADILAN SERIRIT', 'PLANET GADGET 07 - GATSU TENGAH', 'HARTONO ELEKTRONIK 03 - KTI', 'ERABLUE 37 - ERABLUE ELECTRONICS KEADILAN RAYA', 'CATUR WARGA COMPUTER 01 - CATUR WARGA COMPUTER MATARAM', 'DIGIMAP 09 - DIGIMAP AEON MALL BSD', 'GOOD PONSEL', 'IBOX 145 - IBOX IMAM BONJOL BALI', 'SEHATI GROUP 03 - MEGASTORE', 'KAWAN LAMA INFORMA ELEKTRONIK 02 - IBCC BDG', 'KAWAN LAMA INFORMA 089 DAMAR PADANG', 'ERABLUE 07 - ERABLUE ELECTRONICS RAWA BUNTU', 'K FITNESS 02 - SEMARANG', 'LOG IN MEGASTORE 09 - CINUNUK', 'MITRA10 054 - GARUT', 'FITHUB 117 - NUSA DUA', 'MANADO MITRA BERSAMA 001 - SAMSUNG STORE MANTOS 3', 'WILLFITNESS 16 - DEPOK', 'GAN 17 - HELLO TEBET', 'UFO 18 - UFO COKROAMINOTO', 'IBOX 119 - IBOX GIANYAR BALI', 'IBOX 83 - IBOX ARMADA TOWN SQUARE', 'IBOX 54 - LIPPO PLAZA YOGYAKARTA II', 'DIGIMAP 28 - DIGIMAP TRANS STUDIO MALL BANDUNG', 'ELECTRONIC CITY 43 - TANGERANG CITY', 'DIGIMAP 35 - DIGIMAP TUNJUNGAN PLAZA 3', 'NASA 130 - SES MALL PANAKKUKANG', 'ELECTRONIC CITY 36 - METLAND CILEUNGSI', 'IBOX 169 - IBOX GRAND BATAM MALL', 'GTN 29 - POINT 2000 KOTA KASABLANKA', 'HYPERMART 210 DAAN MOGOT', 'GRAND BUMI MAS 001 - GATSU', 'DIGIPLUS 09 - DIGIPLUS CIBINONG CITY MALL 2', 'IBOX 180 - IBOX LIPPO PLAZA KUPANG', 'DIGIMAP 29 - DIGIMAP 23 PASKAL MALL', 'GAN 22 - HELLO LIVING WORLD GRAND WISATA', 'ELECTRONIC CITY 06 - MARGO', 'IBOX 166 - MANYAR KERTOARJO', 'JALAN UNTUK KEMENANGAN 03 - ATLANTIS SMARTPHONE MATARAM GAJAH MADA', 'BERKAH BERSAMA TARA NEW 01 - TUKAD BARITO', 'GTN 151 - BLIBLI STORE MARGO CITY', 'GTN 164 - BLIBLI STORE SUMMARECON MALL BANDUNG', 'HARTONO ELEKTRONIK 05 - MLG', 'EAR 723 - ERAFONE & MORE RUKO A YANI DENPASAR', 'HARTONO ELEKTRONIK 04 - BDB', 'DIGIMAP 39 - DIGIMAP GALERIA MALL', 'IBOX 35 - TANGERANG CITY MALL', 'IBOX 154 - IBOX BINTARO JAYA XCHANGE MALL 2', 'KAWAN LAMA INFORMA 094 IBCC BANDUNG', 'GTN 86 - BLIBLI STORE CENTRAL PARK', 'ELS.ID 004 - SEMARANG', 'FITHUB 103 - GATSU BARAT', 'KAWAN LAMA INFORMA 044 CIBINONG', 'GTN 155 - BLIBLI STORE DISCOVERY MALL BALI', 'DIGIMAP 10 - DIGIMAP SUPERMALL KARAWACI', 'GTN 163 - BLIBLI STORE BLOK M PLAZA', 'GTN 207 - BLIBLI STORE BLUE MALL PAKUWON SOLO', 'DIGIMAP 60 - DIGIMAP AEON DELTAMAS', 'JURAGAN STORE MANDIRI 002 - JURAGAN STORE AYANI BANJARBARU KM 35', 'KAWAN LAMA INFORMA 103 GORONTALO', 'KAWAN LAMA INFORMA 027 KENDARI', 'DIGI STORE O4 - DIGI STORE MALL PANAKUKKANG', 'DIGIMAP 66 - DIGIMAP SUN CITY MALL SIDOARJO', 'DIGIMAP 62 - DIGIMAP LIVING WORLD KOTA WISATA', 'KAWAN LAMA INFORMA ELEKTRONIK 34 - LW PEKANBARU', 'GTN 161 - BLIBLI STORE BINTARO XCHANGE MALL 2', 'IBOX 07 - MARGO CITY', 'GTN 192 - BLIBLI STORE BLUE PARAGON SEMARANG', 'IBOX 179 - SLAMET RIYADI SURAKARTA', 'KAWAN LAMA INFORMA 117 - CITIMALL GARUT', 'WILLFITNESS 17 - BALI GATSU BARAT', 'KAWAN LAMA INFORMA 004 MANADO TOWN SQUARE', 'KAWAN LAMA INFORMA 208 - LP BANJARMASIN', 'LOTTE 01- GANDARIA CITY MALL', 'KAWAN LAMA INFORMA 066 LW PEKAN BARU', 'PURA PURA PONSEL 002 - NEW', 'BERKAH BERSAMA TARA NEW 03 - DALUNG', 'KAWAN LAMA INFORMA 101 TEKNOMART KRWNG', 'WILLFITNESS 18 - KARAWACI', 'DIGIMAP 51 - DIGIMAP BASKO PADANG', 'KAWAN LAMA INFORMA 087 PANAKKUKANG MAKASAR', 'IBOX 20 - GANDARIA CITY', 'IBOX 153 - IBOX DEWATA UDAYANA', 'MII URBAN REPUBLIC 015 - URBAN REPUBLIC TEUKU UMAR BALI', 'ME GALLERY 06 - ME GALLERY MALL PANAKKUKANG MAKASSAR', 'GTN 150 - BLIBLI STORE TSM MAKASSAR', 'GTN 265 - BLIBLI STORE SUMMARECON MALL SERPONG', 'EAR 888 - ERAFONE MEGASTORE RUKO MT HARYONO BALIKPAPAN', 'GTN 168 - BLIBLI STORE AEON MALL DELTA MAS', 'DIGIMAP 17 - DIGIMAP PLAZA BLOK M', 'ME GALLERY 01 - ME GALLERY TSM MAKASSAR', 'GTN 134 - BLIBLI STORE LIVING WORLD DENPASAR', 'KAWAN LAMA INFORMA 106 LATANETE MAKASAR', 'CELLULAR WORLD 08 - SES TEUKU UMAR', 'KAWAN LAMA INFORMA 112 CITRA RAYA TGR', 'MHI 020 - CIBINONG CITY MALL', 'WILLFITNESS 19 - BANDUNG KOPO', 'PLANET GADGET 24 - KUPANG', 'IBOX 41 - PLAZA MEDAN FAIR', 'IBOX 183 - IBOX AHMAD YANI SERANG', 'IBOX 142 - IBOX SUMMARECON MALL BANDUNG', 'DIGIMAP 74 - DIGIMAP JATINANGOR TS', 'BERKAH BERSAMA TARA NEW 05 - MALANG', 'ALASKA MANDIRI CEMERLANG 01 - MAKASSAR', 'MII URBAN REPUBLIC 011 - URBAN REPUBLIC PLAZA AMBARUKMO YOGYA'
];

var OFFLINE_MERCHANT_AVERAGE_RISK = [
  'ERABLUE 02 - ERABLUE ELECTRONICS KALI ABANG', 'COURTS 101 - KOTA HARAPAN INDAH', 'GTN 191 - BLIBLI STORE BLUE CIREBON SUPER BLOCK', 'LAVITA JAYA MANDIRI 001 - MAKASSAR', 'EAR 292 - MEGASTORE RUKO A YANI KARAWANG', 'DIGIPLUS 29 - DIGIPLUS SUMMARECON BANDUNG', 'MHI 021 - DEPOK TOWN SQUARE', 'EAR 724 - ERAFONE & MORE RUKO GATOT SUBROTO', 'PLANET GROUP 01 - PLANET COMPUTER', 'GAN 13 - HELLO GREEN PRAMUKA', 'DARGAN CELL 01 - SOEKARNO HATTA', 'IBOX 139 - IBOX SUDIRMAN BALIKPAPAN', 'EAR 842 - ERAFONE PERAWANG RIAU', 'EAR 780 - ERAFONE MB HASANUDDIN GOWA', 'TOPSELL PLAZA 007 - SIDOARJO', 'EAR 105 - ERAFONE MEGASTORE TAMBUN', 'LOTTE 02- KELAPA GADING', 'ORISKIN 08 - KARAWACI', 'IBOX 156 - IBOX OPI PALEMBANG', 'DIGIMAP 42 - DIGIMAP PLAZA MALIOBORO YOGYA', 'ORISKIN 16 - DENPASAR BALI', 'YOGYA 07 - GRIYA GRAND CINUNUK', 'GTN 227 - BLIBLI STORE BLUE GATOT SUBROTO SOLO', 'IBOX 19 - FLAGSHIP SENAYAN CITY', 'GTN 193 - BLIBLI STORE BLUE DAAN MOGOT', 'EAR 671 - ERAFONE MALL RATU INDAH', 'MDP SUPERSTORE 01 - MDP IT SUPERSTORE', 'TOKO ANUGERAH 02 - TOKO ANUGERAH AROEPPALA MAKASSAR', 'ANDALAS 07 - PENTACITY', 'DAZZLE 001 - SUPER DAZZLE GEJAYAN', 'BUCCHERI 104 - PALU GALARA MALL', 'HARTONO MOBILE 01 - SDN', 'SEMERU 001 - SEMERU PERINTIS MAKASAR', 'BINA KARYA SARANA BANGUN 002 - PLAZA BANGUNAN ELECTRONIC', 'ERABLUE 49 - ERABLUE ELECTRONICS CIKARANG', 'ANDREAN CELL 001 - NEW WTC MALL LT. 1', 'CAHAYA BERKAT 03 - DIAMOND KUTA', 'IBOX 94 - IBOX METROPOLITAN MALL CILEUNGSI', 'BERKAH BERSAMA TARA 09 NEW - SIDOARJO', 'RUMAH GADGET 002 - NEW', 'UFO 24 - UFO SUTOYO MALANG', 'EAR 76 - ERAFONE GREEN PRAMUKA SQUARE', 'DIGIMAP 49 - DIGIMAP THE PARK KENDARI', 'ERABLUE 12 - ERABLUE ELECTRONICS SAWANGAN', 'LOTTE 06 - TAMAN SURYA', 'CURVES INDONESIA 42 - SAMARINDA', 'GTN 77 - TUKAR TAMBAH JAMBU DUA', 'IBOX 65 - FESTIVAL CITYLINK BANDUNG', 'IPHONE TASIK 01 - IPHONE TASIK', 'GTN 189 - BLIBLI STORE BLUE MALL ARTHA GADING', 'EAR 635 - ERAFONE & MORE SAWOJAJAR MALANG', 'BERKAH BERSAMA TARA LIKE NEW 04 - DALUNG', 'LUCKY PERDANA 06 - LUCKY DEPOK BEJI', 'EAR 814 - ERAFONE AND MORE SUDIRMAN BANTUL', 'IBOX 99 - IBOX KARAWANG CENTRAL PLAZA', 'ME GALLERY 07 - ME GALLERY NIPAH MALL MAKASSAR', 'IBOX 12 - ST MORITZ', 'EAR 97 - ERAFONE KEJAYAAN DEPOK', 'NUANSA SUPERSTORE 05 - IMAM BONJOL SAMARINDA', 'SEMERU 002 - SEMERU SARAPPO MAKASAR', 'IBOX 69 - CIREBON', 'UFO 12 - UFO MALANG', 'ERABLUE 36 - ERABLUE ELECTRONICS CISOKA TIGARAKSA', 'WILLFITNESS 06 - GROGOL', 'ADVANCE 110 EC PANAKUKKANG', 'FITHUB 86 - ULUWATU', 'HDSHOP 001 - PADANG', 'IBOX 91 - IBOX ICON MALL GRESIK', 'DIGIMAP 08 - DIGIMAP TRANS CIBUBUR MALL', 'ORISKIN 46 - LIVING WORLD PEKANBARU', 'DIGIPLUS 63 - DIGIPLUS THE PARK SAWANGAN', 'IBOX 126 - IBOX CITIMALL GARUT', 'LUCKY PERDANA 01 - LUCKY CIRACAS 7', 'AGRES JOGJA TEKNOLOGI 001 - AGRES.ID SIMANJUNTAK', 'HARTONO MOBILE 02 - BGJ', 'IBOX 22 - MALL OF AMBASSADOR II', 'ERABLUE 39 - ERABLUE ELECTRONICS JATIWARINGIN', 'ADVANCE 197 NUANSA ELEKTRONIK MATOS', 'IBOX 13 - ATRIUM', 'PLANET GADGET 08 - GATSU BARAT', 'CELLULAR WORLD 02 - GATSU', 'DIGIPLUS 15 - DIGIPLUS PAKUWON MALL YOGYAKARTA', 'ME GALLERY 08 - ME GALLERY PETTARANI MAKASSAR', 'ORISKIN 38 - SURABAYA', 'EAR 38 MEGASTORE SEMPER', 'SPM SUKSES SEJAHTERA 01 - SUPER MURAH PANCA USAHA', 'MULTI MEDIA 003 - ANDUONOHU', 'LOTTE 07 - GREEN PRAMUKA', 'IBOX 102 - IBOX BULUSARAUNG', 'BERKAH BERSAMA TARA 08 LIKE NEW - SURABAYA', 'ERABLUE 40 - ERABLUE ELECTRONICS SYEH MUBAROK', 'IBOX 115 - IBOX QUEEN CITY SEMARANG', 'EAR 904 - ERAFONE MEGASTORE PALEMBANG SQUARE', 'PLANET GADGET 18 - KUTA', 'ERABLUE 70 - ERABLUE ELECTRONICS MAULANA HASANUDIN', 'EAR 323 - ERAFONE GEJAYAN JOGJA', 'EAR 775 - ERAFONE & MORE KAKATUA MAKASSAR', 'MII URBAN REPUBLIC 016 - URBAN REPUBLIC LIVING WORLD DENPASAR', 'SEHATI GROUP 04 - SEHATI PREMIUM STORE 02', 'ERABLUE 19 - ERABLUE ELECTRONICS MUSTIKA JAYA', 'ERABLUE 24 - ERABLUE ELECTRONICS MOHAMAD TOHA BOGOR', 'DIGIPLUS 13 - DIGIPLUS MALL OLYMPIC GARDEN MALANG', 'EAR 711 - ERAFONE BANGKA RAYA', 'PLANET GADGET 03 - HAND PHONE SHOP', 'IBOX 93 - IBOX CIBUBUR JUNCTION', 'EAR 729 - ERAFONE CILAMPENI BANDUNG', 'ERABLUE 31 - ERABLUE ELECTRONICS PATRIOT', 'ERABLUE 51 - ERABLUE ELECTRONICS CIOMA KRETEG', 'IBOX 112 - IBOX JOGJA JAKAL', 'MOBI CELL 001 - OPPO OFFICIAL MARINA', 'LOTTE GROSIR 18 - BOGOR', 'TIGA PUTRA 01 - KAWI', 'LOTTE GROSIR 01 - PASAR REBO', 'INDOCELL 003 - LIKE NEW TEUKU UMAR', 'GTN 174 - BLIBLI STORE SKA MALL PEKANBARU', 'ATLANTA 06 - HOS COKROAMINOTO YOGYA', 'ANEKA JAYA MOBILE 003 - MT HARYONO', 'GTN 211 - BLIBLI STORE MALL RATU INDAH', 'GTN 243 - BLIBLI STORE PALEMBANG INDAH MALL', 'WILLFITNESS 05 - CEMPAKA PUTIH', 'SEHATI GROUP 05 - SEHATI SMART SHOP', 'MITRA10 003 - SEMARANG', 'ROSE CELLULAR 001 - TUPAREV', 'PLANET GADGET 20 - CIREBON', 'MANADO MITRA BERSAMA 004 - APPLE SHOP MHC', 'GTN 172 - BLIBLI STORE LIVING WORLD KOTA WISATA', 'YOGYA 21 - GRAND YOGYA KEPATIHAN', 'DIGIPLUS 35 - DIGIPLUS POPUP SUNRISE MALL MOJOKERTO', 'CANDI JITU INDONESIA 01 - CANDI ELEKTRONIK SOLO PREMIUM', 'KAWAN LAMA INFORMA 102 METRO INDAH BANDUNG', 'EAR 623 - ERAFONE CICALENGKA', 'IBOX 136 - IBOX KLATEN TOWN SQUARE', 'EAR 740 - ERAFONE CIBANTENG KOJA', 'GAYATRI 07 - PUTRA JAYA JIMBARAN', 'EAR 15 ERAFONE SUPERMAL KARAWACI', 'IBOX 148 - IBOX MALL ALAM SUTERA', 'GTN 166 - SEP CITY PLAZA GARUT', 'IBOX 134 - IBOX BIGMALL SAMARINDA', 'GUDANG LAPTOP 03 - GUNUNG AGUNG', 'EAR 841 - ERAFONE RUKO DURI RIAU', 'ERABLUE 85 - ERABLUE ELECTRONICS PRAMUKA', 'MITRA10 002 - SOLO BARU', 'RID01 - AGRES.ID ITC DEPOK 3 163', 'SUMBAR SMARTPHONE 01 - PREMIERE', 'OSBOND GYM LITE 04 CIBUBUR', 'ERABLUE 25 - ERABLUE ELECTRONICS MOH TOHA TANGERANG', 'PLANET GADGET 23 - MOJOKERTO', 'EAR 674 - ERAFONE MEGASTORE DAENG TATA M', 'GAN 08 - HELLO DAAN MOGOT', 'KAWAN LAMA INFORMA ELEKTRONIK 84 HCIR IE PANAKKUKANG SQUARE', 'PURA PURA PONSEL 001 - LIKE NEW', 'ERABLUE 55 - ERABLUE ELECTRONICS KANO RAYA', 'ATRIA 32 - ATRIA KENDARI', 'NASA 160 - SPS THE PARK KENDARI', 'EAR 793 - ERAFONE AND MORE MAYJEND SUNGKONO', 'IBOX 38 - MALL AMBASSADOR 3', 'ANYELIR PONSEL 002 - LIKE NEW KESIMAN DENPASAR', 'EAR 652 - MAYOR ABDURAHMAN', 'ELECTRONIC CITY 60 - CITRA RAYA CIKUPA', 'EAR 594 - ERAFONE MEGASTORE CONDET 2', 'NBC 02 - TAMAN GRIYA', 'YULI SUMBER LARIS 02 - PETTARANI', 'YOGYA 26 - GRIYA PLAZA SUMEDANG', 'JAYAWIJAYA AUDIO 001 - BALI', 'EAR 882 - ERAFONE RUKO ANTASARI SAMARINDA', 'IBOX 109 - IBOX BUARAN PLAZA', 'SARI BUNGA 006 - BADILAN SUDIRMAN', 'ERABLUE 90 - ERABLUE ELECTRONICS RAYA MAUK JATIWARINGIN', 'INDOCELL 002 - NEW SESETAN', 'GALERY HANDPHONE 009 - SHOWROOM IPHONE', 'JMG INTERNATIONAL 042 - JMG TANAH ABANG BLOK B', 'UFO 01 - UFO KERTAJAYA', 'EAR 783 - ERAFONE MEGASTORE BATUA MAKASSAR', 'WILLFITNESS 13 - KALIMALANG', 'MHI 031 - TANGCITY 1', 'DIGIMAP 76 - DIGIMAP LIPPO PLAZA MANADO', 'EAR 255 - ERAFONE PONDOK LABU', 'EAR 29 ERAFONE RUKO CEGER TGR', 'EAR 86 - ERAFONE DAAN MOGOT MALL', 'EAR 902 - ERAFONE PALEMBANG TRADE CENTER', 'DIGIMAP 18 - DIGIMAP PONDOK INDAH MALL 2', 'JET FITNESS 01 KARAWACI', 'DIGIPLUS 64 - DIGIPLUS Q MALL BANJARMASIN', 'GAYATRI 11 - GAYATRI GLOBAL TECH COMPUTER TABANAN', 'DH STORE 002 - LIKE NEW WTC LT. 1 SURABAYA', 'IBOX 09 - FLAGSHIP CENTRAL PARK', 'A TAKRIB 01 - JL KYAI MOJO', 'JEFINDO TEKNOLOGI 02 - TELESTORE', 'ELECTRONIC CITY 07 - BOTANI SQUARE', 'ELECTRONIC CITY 09 - REVO TOWN BEKASI', 'ELECTRONIC CITY 72 - SKA', 'IBOX 149 - IBOX JUANDA SAMARINDA', 'KAWAN LAMA SELMA 44 - HCIR SELMA PANAKKUKANG SQUARE', 'ADVANCE 192 PLAZA BALIKPAPAN', 'ERABLUE 38 - ERABLUE ELECTRONICS CIRENDEU', 'HYPERMART 207 PURI INDAH', 'ATLANTA 02 - NGALIYAN', 'LOG IN MEGASTORE 01 - ABC', 'BERKAH BERSAMA TARA NEW 14 - KEDIRI', 'MII URBAN REPUBLIC 039 - URBAN REPUBLIC MARGO CITY DEPOK', 'DIGIMAP 38 - DIGIMAP GALAXY MALL', 'MITRA10 046 - TASIKMALAYA', 'GS 001 - PLATINUM STORE', 'EAR 660 - ERAFONE MEGASTORE CILILITAN', 'APOLLO 03 - WTC SPP', 'SMART PHONE SHOP 04 - SMART GADGET BCP', 'EAR 677 - ERAFONE RUKO BUMI TAMALANREA PERMAI', 'GTN 132 - BLIBLI STORE TUNJUNGAN PLAZA', 'DIGIMAP 69 - DIGIMAP LIPPO PLAZA BATU', 'ELECTRONIC CITY 10 - BEKASI METALL', 'FITHUB 82 - BUAH BATU', 'ERABLUE 17 - ERABLUE ELECTRONICS MERUYA SELATAN', 'EAR 02 - ERAFONE 3 MEGA BEKASI HYPERMALL', 'BPI 01 - TEUKU UMAR', 'HARTONO MOBILE 04 - BDB', 'ORISKIN 45 - CINERE MALL', 'DIGIPLUS 90 - DIGIPLUS SKA MALL', 'DUTA PONSEL PEKANBARU 01 - SUDIRMAN', 'EAR 441 - ERAFONE MALL AMBASADOR', 'A TAKRIB 02 - JL MAGELANG', 'BERKAH BERSAMA TARA LIKE NEW 06 - MALANG', 'GAYATRI 05 - PUTRA JAYA LAPTOP TEUKU UMAR', 'DEVSTORE 001 - LIKE NEW GATSU', 'DIGIPLUS 20 - DIGIPLUS BIG MALL SAMARINDA', 'ERABLUE 80 - ERABLUE ELECTRONICS RAYA KRESEK SUKAMULYA', 'MITRA10 038 - TANJUNG API API', 'MHI 016 - CIKARANG', 'DIGIPLUS 18 - DIGIPLUS TRANS STUDIO MALL MAKASSAR EXTENSION', 'KAWAN LAMA SELMA 11 - CIREBON SUPERBLOCK', 'LOTTE GROSIR 23 - PADALARANG', 'GTN 180 - BLIBLI STORE TSM BALI', 'KAWAN LAMA INFORMA ELEKTRONIK 18 - CIBINONG BGR', 'KAWAN LAMA INFORMA ELEKTRONIK 12 - MANTOS MND', 'EAR 805 - ERAFONE RUKO CIMANUK GARUT', 'ELECTRONIC CITY 77 - THE PARK KENDARI', 'MITRA10 020 - CIBUBUR', 'DIGIPLUS 37 - DIGIPLUS CITIMALL GARUT', 'ELECTRONIC CITY 46 - CIBUBUR', 'MODERN ELECTRONIC 01 - MODERN ELECTRONIC SEMARANG', 'GAN 19 - HELLO MALL CIPUTRA PEKANBARU', 'YUDHAOMBOK STORE 02 - YUDHAOMBOK STORE NEW SUROPATI', 'MII URBAN REPUBLIC 009 - URBAN REPUBLIC TSM MAKASSAR', 'ORISKIN 47 - LIPPO CIKARANG MALL', 'DIGIMAP 63 - DIGIMAP JAVA SUPERMALL SEMARANG', 'JMG INTERNATIONAL 034 - JMG EXHIBITION THE PARK SAWANGAN DEPOK', 'DIGI STORE 02 - DIGI STORE MALL MARI', 'IBOX 36 - BINTARO PLAZA', 'EAR 619 - ERAFONE FRANCHISE RUKO KLIPANG', 'ELECTRONIC CITY 54 - CIBINONG CITY MALL', 'MANADO MITRA BERSAMA 002 - SAMSUNG STORE MANTOS 1', 'EAR 767 - ERAFONE 2.5 TRANS STUDIO MAKASSAR', 'EAR 70 - ERAFONE RUKO M KAHFI', 'PIXEL 01 - ELECTRO SMART KARAWANG', 'IBOX 150 - IBOX GATOT SUBROTO BANJARMASIN', 'MHI 036 - TASIKMALAYA', 'MII URBAN REPUBLIC 035 - URBAN REPUBLIC GANDARIA CITY', 'ADVANCE 202 SAMARINDA SQUARE', 'YOGYA 19 - YOGYA TASIK HZ', 'BELANJA DIGITAL BORNEO 001 - BORNEO STORE BANJARMASIN GADGET', 'IBOX 51 - THE PARK MALL SOLO', 'YOGYA 40 - YOGYA BOJONGSOANG', 'EAR 892 - ERAFONE AND MORE SOREANG BANDUNG', 'BERKAH BERSAMA TARA 10 LIKE NEW - SIDOARJO', 'MII URBAN REPUBLIC 006 - URBAN REPUBLIC MALL PANAKKUKANG MAKASSAR', 'EAR 398 - ERAFONE RUKO TEMBALANG', 'KAWAN LAMA SELMA 53 - CITIMALL DUMAI', 'EAR 376 - ERAFONE RUKO DONGKELAN', 'MITRA10 008 - PASAR BARU', 'GTN 235 - BLIBLI STORE BLUE PEJATEN VILLAGE', 'KAWAN LAMA SELMA 27 - MAYASARI TASIK', 'ADVANCE 19 MITRA10 HARAPAN INDAH', 'ERABLUE 60 - ERABLUE ELECTRONICS WIBAWA MUKTI', 'IBOX 01 - AEON JAKARTA GARDEN CITY', 'MITRA10 045 - BINTARO', 'EVOLUSI RAGA INDONESIA OSBOND GYM 003 - CEMPAKA PUTIH', 'YOGYA 17 - YOGYA CIAMIS', 'ELECTRONIC CITY 56 - LIPPO MALL CIKARANG', 'GTN 236 - BLIBLI STORE BLUE KALIBATA CITY', 'WILLFITNESS 20 - GUBENG SURABAYA', 'BALI SATU COMPUTER 001 - BLESSING COMPUTER', 'KAWAN LAMA SELMA 36 - PRABUMULIH', 'EAR 16 ERAFONE TANGCITY', 'KAWAN LAMA INFORMA 083 LP BALIKPAPAN', 'GRAMEDIA 181 TASIKMALAYA', 'ELECTRONIC CITY 05 - KARAWACI', 'ADVANCE 85 MITRA10 GATSU BALI', 'KAWAN LAMA SELMA 07 - BG JUNCTION SURABAYA', 'YOGYA 39 - YOGYA PLAZA CIMAHI', 'BITCOM 03 - BITPLUS IT SUPERSTORE', 'HITECH CELL 01 - HITECH CELL TASIKMALAYA', 'IBOX 116 - IBOX PADJAJAN BOGOR', 'LOTTE 12 - MAKASSAR', 'MITRA10 021 - BOGOR', 'EAR 714 - ERAFONE & MORE MANYAR KERTOARJO SURABAYA', 'EAR 745 - ERAFONE VETERAN', 'CITITEL 01 CIKARANG', 'ERABLUE 16 - ERABLUE ELECTRONICS LEGOK', 'EAR 20 ERAFONE PLAZA BINTARO', 'MITRA10 026 - A YANI SURABAYA', 'EAR 268 - MEGASTORE TUNJUNGAN PLAZA 3', 'MHI 038 - BEC 2', 'ADVANCE 100 LIVING WORLD PEKANBARU', 'KAWAN LAMA INFORMA 091 KARAWACI TGR', 'DIGIPLUS 44 - DIGIPLUS ARION MALL', 'MHI 071 - CIBINONG CITY MALL 2', 'KAWAN LAMA SELMA 51 - PALEMBANG SQUARE', 'ELS.ID 003 - SURAKARTA', 'KLA COMPUTER 001 - SEMARANG', 'RCM01 - AGRES.ID CCM LG NO.17', 'UFO 20 - UFO JIMBARAN', 'UFO 15 - UFO JOGJAKARTA', 'KAWAN LAMA INFORMA ELEKTRONIK 96 - IE LP PALEMBANG', 'KAWAN LAMA INFORMA ELEKTRONIK 29 - LP CIREBON', 'JURAGAN STORE BALI 02 - LIKE NEW', 'ELECTRONIC CITY 13 - BINTARO', 'EAR 339 - ERAFONE MEGASTORE SEMARANG', 'IBOX 143 - IBOX DUTAMALL BANJARMASIN', 'KAWAN LAMA SELMA 06 - KJI (KRAMAT JATI INDAH)', 'GAYATRI 02 - ADI DHARMA KOMPUTER', 'GTN 139 - BLIBLI STORE PAKUWON SURABAYA', 'KAWAN LAMA INFORMA 093 LP TASIKMALAYA', 'LOTTE GROSIR 21 - PAKANSARI', 'KAWAN LAMA INFORMA ELEKTRONIK 57 - BEC BANDUNG', 'KAWAN LAMA SELMA 24 - KINGS', 'KAWAN LAMA INFORMA 076 A.YANI BEKASI', 'IBOX 55 - JOGJA CITY MALL', 'KAWAN LAMA INFORMA ELEKTRONIK 24 - LP TASIKMALAYA', 'KAWAN LAMA INFORMA ELEKTRONIK 42 - PTC PALEMBANG', 'GTN 196 - BLIBLI STORE BLUE MALL LIPPO CIKARANG', 'IBOX 105 - IBOX LIPPO PLAZA EKALOKASARI', 'NASA 40 - SES SUMMARECON MALL SERPONG', 'RKI06 - MAJU JAYA COMPUTER KARAWACI J1 NO.3-3A', 'BERKAH BERSAMA TARA 07 NEW - SURABAYA', 'MHI 022 - SMS DEPOK', 'PIXEL 03 - ELECTRO SMART HYPERMALL BEKASI', 'OSBOND GYM - 07 TANGCITY', 'DIGIPLUS 17 - DIGIPLUS NIPAH PARK MAKASSAR', 'EAR 353 - ERAFONE MEGASTORE RUKO SINGARAJA BALI', 'EAR 636 - ERAFONE 2.5 JENDRAL HAYAM WURUK DENPASAR', 'KAWAN LAMA SELMA 18 - CITRA RAYA', 'DIGIMAP 02 - DIGIMAP GRAND INDONESIA', 'DIGIPLUS 14 - DIGIPLUS SOLO PARAGON MALL', 'RGC02 - AGRES.ID PGC 3A NO. 562C', 'YAMADA BEST 09 - YAMADA BEST AEON DELTA MAS CIKARANG', 'IBOX 64 - BANDUNG INDAH PLAZA', 'MHI 031 - TANGCITY 2', 'KLA COMPUTER 005 - CIREBON', 'ATRIA 16 - ATRIA PASARBARU', 'ISTANA IT 001 - GATSU', 'KARYA RUANG 02 - FURNITURE ASIA PLAZA', 'IBOX 08 - PESONA SQUARE DEPOK', 'ELECTRONIC CITY 45 - PANAKUKANG', 'DIGIPLUS 04 - DIGIPLUS MARGOCITY DEPOK', 'MANADO MITRA BERSAMA 003 - M STORE MANTOS 3', 'GTN 205 - BLIBLI STORE BLUE MALL CIPUTRA CITRARAYA TANGERANG', 'FTL GYM 06 - CIPUTAT', 'DIGIPLUS 27 - DIGIPLUS QUEEN CITY MALL', 'KAWAN LAMA INFORMA ELEKTRONIK 25 - TKM KARAWANG', 'IBOX 88 - IBOX THE PARK MALL SEMARANG', 'ATRIA 05 - ATRIA KALIMALANG', 'SCANDIA 001 - BOTANI SQUARE', 'ATRIA 04 - ATRIA CIBUBUR', 'UFO 16 - UFO JOGJAKARTA 2', 'MITRA10 055 - TENTH AVENUE BANDUNG', 'GTN 118 - BLIBLI STORE PASKAL 23', 'MHI 023 - SAWANGAN', 'MITRA10 011 - KALIMANG BARU', 'GTN 146 - BLIBLI STORE AEON SENTUL CITY', 'GTN 91 - BLIBLI STORE TSM CIBUBUR', 'JOY PHONE 001 - BATUBULAN', 'HARTONO ELEKTRONIK 08 - BANDUNG', 'MENARA GRUP 001 - MENARA COMPUTER & GADGET', 'ATRIA 11 - ATRIA GATSU BALI', 'A TAKRIB 03 - ATAKRIB ELECTRONICS LIFESTYLE', 'PERFECT HEALTH 05 - AYANI PONTIANAK', 'GTN 162 - BLIBLI STORE NIPAH MALL MAKASSAR', 'KAWAN LAMA INFORMA ELEKTRONIK 23 - LP PETTARANI MKS', 'BOOSTERFITS', 'OFFO LIVING 01 - STORE BOGOR', 'GTN 92 - BLIBLI STORE LIPPO MALL PURI', 'KAWAN LAMA INFORMA 114 PTC PALEMBANG', 'ATRIA 28 - ATRIA SAMARINDA', 'KAWAN LAMA INFORMA ELEKTRONIK 04 - MARGONDA DPK', 'WILLFITNESS 22 - IMAM BONJOL BALI', 'SUKSES SEHAT SEJAHTERA SELAMANYA 001 - FIT SOCIETY', 'SENTRAL KOMPUTER 019 - SENTRAL KOMPUTER EXHIBITION JAKARTA FAIR KEMAYORAN 2025', 'PLANET GADGET 25 - BATUBULAN', 'ORISKIN 66 - TSM BALI', 'OKE SHOP 52 SAMSUNG MAL PANAKUKANG (FX1)', 'MII URBAN REPUBLIC 001 - URBAN REPUBLIC BINTARO JAYA EXCHANGE 2', 'MHI 029 - SES KARAWACI', 'MHI 018 - BOGOR TRADE MALL 1', 'ME GALLERY 03 - ME GALLERY MARI', 'KAWAN LAMA INFORMA ELEKTRONIK 89 - LW KOTA WISATA', 'KAWAN LAMA INFORMA ELEKTRONIK 100 - LW GRAND WISATA BEKASI', 'KAWAN LAMA INFORMA ELEKTRONIK 09 - AYB BEKASI', 'KAWAN LAMA INFORMA 034 LP MANDO PAAL DUA', 'KAWAN LAMA INFORMA 032 LP PERINTIS MAKASAR', 'IUSEDPHONE NEW 002 - BALI', 'IBOX 62 - BANDUNG ELECTRONIC CENTER 1', 'IBOX 206 - IBOX ANNIVERSARY MALL KOTA KASABLANKA', 'IBOX 198 - IBOX EXHIBITION IBOXING WEEK MALL RATU INDAH MAKASSAR', 'IBOX 197 - IBOX EXHIBITION JAKARTA FAIR KEMAYORAN 2025', 'IBOX 194 - IBOX DAYS MANADO TOWN SQUARE', 'IBOX 04 - METROPOLITAN MALL BEKASI', 'GTN 96 - TUKAR TAMBAH PESONA SQUARE', 'GTN 284 - BLIBLI EXHIBITION JAKARTA FAIR KEMAYORAN 2025', 'GTN 154 - BLIBLI STORE LIVING WORLD ALAM SUTERA', 'GTN - SES BOTANI', 'GAN 25 - HELLO EXHIBITION JAKARTA FAIR KEMAYORAN 2025', 'GAN 21 - HELLO MALL OF SERANG', 'GAN 11 - HELLO GREEN SEDAYU', 'GAN 01 - HELLO TRANSPARK BINTARO', 'GALLERY PHONE 001 - RAPOCINI', 'ELECTRONIC CITY 44 - KOTA KASABLANKA', 'EAR 828 - ERAFONE SKA MALL', 'EAR 67 - ERAFONE MALL GANDARIA CITY', 'EAR 541 - ERAFONE MASPION SQUARE', 'EAR 1201 - ERAFONE EXHIBITION JAKARTA FAIR KEMAYORAN 2025', 'EAR 1087 - ERAFONE AND MORE LOMBOK EPICENTRUM MALL', 'DUBAI SMARTPHONE 01 - SAWAHAN', 'DIGIPLUS 75 - DIGIPLUS MEGA MALL BTM', 'DIGIPLUS 74 - DIGIPLUS PALEMBANG TC', 'DIGIPLUS 41 - DIGIPLUS CIREBON SUPERBLOCK', 'DIGIPLUS 02 - DIGIPLUS BINTARO XCHANGE', 'DIGIMAP 81 - DIGIMAP TENTH AVENUE', 'DIGIMAP 44 - DIGIMAP PAKUWON MALL SOLO BARU', 'DIGIMAP 43 - DIGIMAP SOLO SQUARE', 'DIGIMAP 36 - DIGIMAP GRESSMALL GRESIK', 'DIGI STORE 12 - HUAWEI MALL PANAKKUKANG', 'DIANA EVA FURNITURE 03 - CIBUBUR', 'ALFAMART - FRANCHISE', 'ADVANCE 62 PLAZA AMBARUKMO', 'ADVANCE 48 MITRA10 TANJUNG APIAPI', 'ADVANCE 334 EXHIBITION JAKARTA FAIR KEMAYORAN 2025', 'ADVANCE 198 MITRA 10 SAMARINDA', 'ABSOLUTEFIT MITRA INDONESIA 008 - KWITANG', 'EAR 357 - ERAFONE MEGASTORE 2 TEUKU UMAR', 'EAR 104 - ERAFONE MEGASTORE JBK CIKARANG', 'EAR 799 - ERAFONE PALLANGGA GOWA', 'EAR 791 - ERAFONE MEGASTORE RUKO TODDOPULI', 'EAR 518 - ERAFONE MEGASTORE RUKO TEUKU UMAR BARAT'
];

var OFFLINE_MERCHANT_MODERATE_RISK = [
  'ERABLUE 32 - ERABLUE ELECTRONICS CIKUPA PEUSAR', 'EAR39 MEGASTORE MKG', 'ERABLUE 14 - ERABLUE ELECTRONICS SETIA MEKAR', 'UFO 14 - UFO MOJOKERTO', 'SUARA ELEKTRO 006 - TOMOHON', 'MAXI STORE 01- MAXI STORE PERINTIS', 'B STORE 01 - CONDET JAKARTA', 'EAR 361 - RUKO SUPRATMAN CIPUTAT', 'EAR 824 - ERAFONE 1 MEGA MALL MANADO', 'EAR 1037 - ERAFONE MEGASTORE RUKO MT HARYONO KENDARI', 'IBOX 71 - MEGAMALL MANADO', 'ERABLUE 72 - ERABLUE ELECTRONICS RENGASDENGKLOK', 'EAR 98 - ERAFONE MALL BUARAN', 'ANDALAS 01 - SUPERSTORE SOEKARNO HATTA', 'ATLANTA 08 - MAJAPAHIT SEMARANG', 'IBOX 74 - PLAZA MARINA 1 SURABAYA', 'GTN 100 - TUKAR TAMBAH SUPERMALL KARAWACI', 'CINDY CELL 001 - STORE', 'EAR 71 - MEGASTORE KEMANG', 'BUMI MAS BALI PRIMA 001 - BUMI MAS ELEKTRONIK & FURNITURE TABANAN', 'ERABLUE 82 - ERABLUE ELECTRONICS CITRA KEBUN MAS', 'GADGET MART 01 - BJM BELITUNG', 'GAN 04 - HELLO UPTOWN MALL', 'LOG IN MEGASTORE 02 - CIMINDI', 'EAR 887 - ERAFONE MEGASTORE THE BALIKPAPAN PLAZA', 'ERABLUE 76 - ERABLUE ELECTRONICS BOJONG KONENG', 'DIGIPLUS 68 - DIGIPLUS LIPPO PLAZA KENDARI', 'NUANSA SUPERSTORE 02 - SUTOYO', 'ERABLUE 83 - ERABLUE ELECTRONICS PROKLAMASI', 'MII URBAN REPUBLIC 048 - URBAN REPUBLIC PALEMBANG ICON', 'ERABLUE 78 - ERABLUE ELECTRONICS SYEH QURO PALUMBONSARI', 'GTN 179 - BLIBLI STORE BEC BANDUNG', 'NUANSA SUPERSTORE 04 - MATOS SAMARINDA', 'WIN INDO NUSA 01 - WIN CELLULAR', 'EAR 781 - ERAFONE MULTIBRAND LIDAH WETAN', 'ERABLUE 81 - ERABLUE ELECTRONICS SYEH QURO TELAGASARI', 'MERDEKA FURNITURE 001 - IMAM BONJOL', 'FTL GYM 05 - GANDARIA', 'ERABLUE 73 - ERABLUE ELECTRONICS RAYA HANKAM', 'EAR 604 - ERAFONE RUKO TABANAN', 'SUARA ELEKTRO 001 - PANIKI', 'MII URBAN REPUBLIC 024 - URBAN REPUBLIC AEON MALL TANJUNG BARAT', 'ERABLUE 58 - ERABLUE ELECTRONICS RAYA LEGOK KARAWACI', 'VINIX INTICOM 01 - ASEAN CELL PANCA USAHA NEW', 'MITRA10 004 - GATOT SUBROTO DPS', 'GAYATRI 04 - GAYATRI LAPTOP SINGARAJA', 'ERABLUE 53 - ERABLUE ELECTRONICS RE MARTADINATA', 'BENUA ELECTRONIC SENTRA 001 - MANADO', 'EAR 440 - ERAFONE MEGASTORE TEGALREJO JOGJAKARTA', 'DIGIMAP 70 - DIGIMAP PLAZA SURABAYA', 'ERA TELEKOMUNIKASI 01 - TOPSELL JOGJATRONIK', 'JAYA GRAHA ABADI 01 - GRAHA ELEKTRONIK MATARAM MALL', 'GAYATRI 03 - AGUSTIN LAPTOP', 'TOPSELL BHAYANGKARA 001 - MOJOKERTO', 'KARTIKA ELEKTRONIK 01 - TOKO KARTIKA ELEKTRONIK PEKANBARU', 'DIGIPLUS 32 - DIGIPLUS PLAZA PARAHYANGAN BANDUNG', 'TOKO ANUGERAH 01 - TOKO ANUGERAH GOWA', 'INDOCELL 001 - LIKE NEW SESETAN', 'MII URBAN REPUBLIC 049 - URBAN REPUBLIC PALEMBANG SQUARE', 'EAR 431 - PLAZA ASIA', 'EAR 704 - ERAFONE RUKO ALAUDDIN MAKASSAR', 'ERABLUE 35 - ERABLUE ELECTRONICS PAHLAWAN', 'GTN 231 - BLIBLI STORE BLUE ITC ROXY MAS', 'IBOX 172 - IBOX LIPPO PLAZA KENDARI', 'SURYA PHONE 06 - ABUL HASAN SSP', 'EAR 825 - ERAFONE PAAL DUA MANADO', 'GTN 199 - BLIBLI STORE BLUE BEKASI CYBER PARK', 'MAJU BERSAMA 016 - MAJU HARDWARE KEDIRI', 'ORISKIN 06 - BINTARO JAYA', 'ERABLUE 69 - ERABLUE ELECTRONICS TELAGASARI KOSAMBI', 'UFO 06 - UFO BANJARMASIN', 'RA GADGET 003 - TUKAD PAKERISAN LIKE NEW', 'EAR 736 - ERAFONE & MORE AROEPALA', 'ELECTRONIC CITY 02 - MALL ARTHA GADING', 'UFO 09 - UFO KEDIRI', 'LISTAR PUTRA GORONTALO 002 - PULUBALA', 'KELLY DENZEL ELEKTRONIC 001 - K & D ELEKTRONIK CENTRE PONTIANAK', 'ERABLUE 05 - ERABLUE ELECTRONICS SILIWANGI', 'ATLANTA 04 - KARANGWULAN', 'SENTRA 002 - SENTRA OPPO L1 R172', 'ERABLUE 26 - ERABLUE ELECTRONICS BANTAR GERBANG SATU', 'EAR 591 - ERAFONE PLAZA SURABAYA', 'TOPSELL 014 - BERKAH ELEKTRONIK MOJOAGUNG', 'EAR 540 - ERAFONE RUKO KAPAS KRAMPUNG SURABAYA', 'JAYA GRAHA ABADI 02 - GRAHA ELEKTRONIK BRAWIJAYA', 'EAR 294 - ERAFONE RUKO CIPULIR', 'EAR 322 - ERAFONE JOGYATRONIK MALL', 'NASA 118 - SES PLAZA ASIA TASIKMALAYA', 'HYPERMART 320 KARAWACI', 'PLANET GROUP 03 - NOTEBOOK CITY', 'IBOX 146 - IBOX PANAKKUKANG BOULEVARD MAKASSAR', 'ERABLUE 09 - ERABLUE ELECTRONICS RADEN FATAH', 'IBOX 10 - ITC ROXY', 'EAR 85 - ERAFONE RUKO BINUS', 'ALYOSHA 002 - JOGJATRONIK', 'EAR 733 - ERAFONE 2.5 PAMULANG', 'EAR 655 - ERAFONE TAMAN KOPO INDAH', 'PLANET GADGET 10 - SIDOARJO', 'EAR 80 - ERAFONE AEON MALL JGC', 'DIGIPLUS 26 - DIGIPLUS PLAZA ATRIUM SENEN', 'CELULLAR WORLD 12 - ARENA', 'MATANI TIGA BERSAUDARA 001 - MATANI ELCOM MANADO', 'ERABLUE 95 - ERABLUE ELECTRONICS MANGUNJAYA', 'EAR 247 - ERAFONE MOH. TOHA BANDUNG', 'DIGIMAP 34 - DIGIMAP PAKUWON MALL', 'EAR 822 - ERAFONE MEGASTORE RUKO MANADO', 'SEHATI GROUP 02 - MODERN STORE GARUT', 'IBOX 176 - IBOX SUDIRMAN PALEMBANG', 'KANA MANADO 001 - KANA CELL MEGAMAS', 'ORISKIN 07 - ALAM SUTERA', 'EAR 409 - ERAFONE WTC E - MALL LANTAI 2 SURABAYA', 'WILLFITNESS 09 - CENGKARENG', 'EAR 229 - ERAFONE 1 BANDUNG ELECTRONIC CENTER', 'ERABLUE 47 - ERABLUE ELECTRONICS PARUNG BOGOR', 'TOPSELL ANGGREK 002 - MOJOKERTO', 'EAR 770 - ERAFONE AND MORE USMAN SADAR GRESIK', 'EAR 1036 - ERAFONE THE PARK KENDARI', 'NAGA MAS GROUP 01 - NAGA MAS CELLULER PUSAT', 'ERABLUE 87 - ERABLUE ELECTRONICS SUKATANI', 'EAR 867 - ERAFONE RUKO MAJALAYA BANDUNG', 'GTN 135 - BLIBLI STORE CIBINONG CITY MALL 2', 'TAMARA MEUBEL 01 - SRIWIJAYA MATARAM', 'IBOX 02 - GRAND GALAXY PARK BEKASI', 'IBOX 49 - PALEMBANG SQUARE', 'ERABLUE 86 - ERABLUE ELECTRONICS SERANG CIBARUSAH', 'MUGEN 01 - MUGEN COMPUTER PETTARANI', 'DENPASAR ELEKTRONIK & FURNITURE 001 - DENPASAR ELEKTRONIK & FURNITURE GATSU TIMUR', 'STRONGEST FITNESS INDONESIA 001 - BG JUNCTION SURABAYA', 'UFO 17 - UFO SEMARANG', 'METEOR CELL 01 - GAJAYANA PUSAT', 'RA GADGET 001 - WR SUPRATMAN LIKE NEW', 'PLANET GADGET 13 - SINGARAJA', 'NASA 96 - SES MEGAMALL MANADO', 'SINAR GUNTUR 01 - TOKO SINAR GUNTUR GARUT', 'IBOX 157 - IBOX SUNRISE MALL MOJOKERTO', 'GTN 206 - BLIBLI STORE BLUE MALL OLYMPIC GARDEN (MOG) MALANG', 'ORISKIN 19 - SEMARANG', 'COURTS 102 - MEGA BEKASI HYPERMALL', 'ERABLUE 15 - ERABLUE ELECTRONICS BINTARA', 'GTN 200 - BLIBLI STORE BLUE WTC SURABAYA', 'UFO 13 - UFO JOMBANG', 'SARI BUNGA 004 - BADILAN NGURAH RAI', 'SURYA PHONE 04 - BUNGTOMO', 'IUSEDPHONE LIKE NEW 001 - BALI', 'ERABLUE 74 - ERABLUE ELECTRONICS KAMPUNG MELAYU', 'GTN 194 - BLIBLI STORE BLUE MEGAMALL MANADO', 'ORISKIN 51 - TANG CITY MALL', 'EAR 83 - MEGASTORE CILEUNGSI', 'ERABLUE 01 - ERABLUE ELECTRONICS TOLE ISKANDAR', 'ERABLUE 61 - ERABLUE ELECTRONICS PLUMPANG SEMPER', 'ERABLUE 12 - ERABLUE ELECTRONICS SAWANGAN', 'ERABLUE 04 - ERABLUE ELECTRONICS RADEN SALEH', 'ERABLUE 02 - ERABLUE ELECTRONICS KALI ABANG', 'ERABLUE 34 - ERABLUE ELECTRONICS BOSIH RAYA', 'ERABLUE 67 - ERABLUE ELECTRONICS KH. AGUS SALIM'
];

var OFFLINE_MERCHANT_HIGH_RISK = [
  'MDP SUPERSTORE 01 - MDP IT SUPERSTORE','GAN 03 - HELLO KUNINGAN CITY', 'EAR 72 - MEGASTORE PONDOK PINANG', 'ADVANCE 204 GRAND MALL PALU', 'INDOMARET', 'ATLANTA 03 - NGESREP', 'EAR 1042 - ERAFONE & MORE RAWASARI', 'IBOX 66 - DAGO BANDUNG', 'ERABLUE 68 - ERABLUE ELECTRONICS RAYA CIBADAK', 'PLANET GADGET 11 - MALANG', 'IBOX 61 - RESINDA KARAWANG', 'WEWE MANDIRI MAKMUR 001 - WW PONSEL NEW', 'IBOX 56 - PENTACITY', 'HARAPAN PONSEL 01 - HARAPAN PONSEL PEKANBARU', 'DIGIPLUS 38 - DIGIPLUS KARAWANG CENTRAL PLAZA', 'J-BROS 001 - ARIF RAHMAN HAKIM', 'DIGIPLUS 11 - DIGIPLUS PLAZA MARINA SURABAYA', 'ERABLUE 66 - ERABLUE ELECTRONICS LEUWILIANG', 'EAR 424 - ERAFONE RUKO GARUT', 'EAR 941 - ERAFONE MEGASTORE GIRIAN BITUNG', 'ATLANTA 01 - MT HARYONO', 'ERABLUE 75 - ERABLUE ELECTRONICS PENDIDIKAN', 'EAR 230 - MEGASTORE ISTANA BANDUNG ELECTRONIC CENTER', 'EAR 273 - ERAFONE WORLD TRADE CENTER SURABAYA', 'APPEL HOUSE 03 - APPEL HOUSE BABARSARI', 'NASA 17 - SES KALIBATA CITY', 'EAR 898 - ERAFONE MEGASTORE MATARAM', 'TOPSELL PLOSO 005 - JOMBANG', 'FAMILY DIGITALCOM 001 - FAMILY DIGITALCOM 1', 'SYIHAB JAYA UTAMA 005 - SYIHAB PHONE VETERAN BANJARMASIN', 'EAR 18 ERAFONE ITC BSD', 'HARTONO ELEKTRONIK 01 - SDN', 'EAR 320 - ERAFONE RUKO PERCETAKAN NEGARA', 'EAR 784 - ERAFONE & MORE BULUSARAUNG', 'PRIMA INDAH CELL 04 - PRIMA INDAH CELL MAROS', 'ERABLUE 23 - ERABLUE ELECTRONICS MT HARYONO', 'HACOM 02 - PACUAN KUDA', 'IBOX 159 - IBOX GRAGE MAL CIREBON', 'ADVANCE 44 MALL BOEMI KEDATON', 'ERABLUE 46 - ERABLUE ELECTRONICS KALIABANG TENGAH', 'KAWAN LAMA INFORMA ELEKTRONIK 74 - MEGAMALL MANADO', 'EAR 933 - ERAFONE AND MORE PLAZA JAMBU 2 BOGOR', 'EAR 621 - ERAFONE RUKO SUROTOKUNTO KLARI', 'DIGIPLUS 33 - DIGIPLUS MALL CIPUTRA SEMARANG', 'EAR 675 - ERAFONE MEGASTORE RUKO PONGTIKU', 'ERABLUE 94 - ERABLUE ELECTRONICS JERUK RAYA', 'EAR 782 - ERAFONE & MORE RAPPOCINI MAKASSAR', 'MAKMUR SENTOSA DIGITAL BISNIS 001 - SWISS BARU WALANDA', 'ERABLUE 65 - ERABLUE ELECTRONICS PASAR KEMIS', 'IBOX 155 - IBOX PALEMBANG TRADE CENTER', 'YOGYA 60 - YOGYA SOREANG', 'LOTTE GROSIR 35 - MATARAM', 'ANDALAS 12 - MT HARYONO', 'EAR 231 - ERAFONE 3 BANDUNG ELECTRONIC CENTER', 'EAR 940 - ERAFONE TOMOHON', 'EAR 401 - ERAFONE MALL OLYMPIC GARDEN', 'CAHAYA BERKAT 02 - DIAMOND SESETAN', 'MICHAEL HUTAMA PERSADA 001 - MICHAEL HP PANCA USAHA', 'ORISKIN 21 - POINT SQUARE MEDAN', 'EAR 430 - PLAZA ASIA SUMEDANG', 'PRIMA COMPUTER 001 - SOLO', 'EAR 22 MEGASTORE RUKO CIPUTAT', 'ERABLUE 71 - ERABLUE ELECTRONICS RAYA NAROGONG', 'ERABLUE 77 - ERABLUE ELECTRONICS KRONJO', 'SBC BERKAH BERSAMA 001 - SBC NGORO', 'NEOFIT GYM 03 - SEKARPACE', 'LRI AGUNG CELL 01 - AGUNG CELL PUSAT', 'TAHAKI 02 - TAHAKI CELL', 'SELULAR MEDIA PRATAMA 002 - PARAFONE SAMSUNG', 'MULTI MEDIA 001 - AHMAD YANI', 'SAMI JAYA 001 - ELEKTRONIK FURNITURE DRIYOREJO', 'DATA BASIS TECHNOLOGY 001 - DATABASE COMPUTER PONTIANAK', 'EAR 01 - ERAFONE 1 MEGA BEKASI HYPERMALL', 'SMS SHOP 15 - JAVAMALL', 'ERABLUE 44 - ERABLUE ELECTRONICS KEBALEN', 'EAR 351 - ERAFONE MEGASTORE RUKO TELOGOSARI SEMARANG', 'EAR 532 - ERAFONE MEGASTORE PONDOK BAMBU', 'TOPSELL 011 - SURABAYA', 'EAR 392 - ERAFONE & MORE RUKO MARGONDA DEPOK', 'MII URBAN REPUBLIC 013 - URBAN REPUBLIC PARAGON MALL SEMARANG', 'EGA JAYA ELEKTRIK 001 - EGAJAYA ELEKTRONIK', 'GTN 203 - BLIBLI STORE BLUE PALEMBANG SQUARE', 'ERABLUE 79 - ERABLUE ELECTRONICS LETJEN IBRAHIM ADJIE', 'IBOX 124 - IBOX CITY PLAZA GARUT', 'ERABLUE 50 - ERABLUE ELECTRONICS PONDOK KELAPA', 'ERABLUE 13 - ERABLUE ELECTRONICS SILIWANGI BEKASI', 'MII URBAN REPUBLIC 008 - URBAN REPUBLIC MALL RATU INDAH MAKASSAR', 'EAR 09 - ERAFONE PLAZA PONDOK GEDE', 'ERABLUE 93 - ERABLUE ELECTRONICS SYEH QURO LEMAHABANG', 'GTN 237 - BLIBLI STORE BLUE BASSURA', 'ERABLUE 59 - ERABLUE ELECTRONICS RAYA CIBARUSAH SIMPANG TIGA', 'IBOX 162 - IBOX KEDIRI TOWN SQUARE', 'IBOX 70 - MANADO TOWN SQUARE', 'PLANET GADGET 06 - GIANYAR', 'GAN 12 - HELLO JAMBU DUA', 'EAR 779 - ERAFONE & MORE PUCANG ANOM SURABAYA', 'ERABLUE 88 - ERABLUE ELECTRONICS JL PIK PENGGILINGAN', 'ELS.ID 001 - YOGYAKARTA', 'DIGIPLUS 10 - DIGIPLUS WTC MALL SURABAYA', 'EAR 30 MEGASTORE ITC ROXY', 'ERABLUE 22 - ERABLUE ELECTRONICS PERJUANGAN TAMAN', 'EAR 661 - ERAFONE RUKO CIWIDEY', 'TOPSELL 009 - KEDIRI', 'MHI 076 - SES SOLO KRATONAN', 'ERABLUE 08 - ERABLUE ELECTRONICS DEWI SARTIKA', 'DAZZLE 002 - SUPER DAZZLE KALIURANG', 'ATLANTA 07 - MUNTILAN', 'MAX-INDO 001 - PADANG'
];

var OFFLINE_MERCHANT_VERY_HIGH_RISK = [
  'DIGIPLUS 93 - DIGIPLUS CITIMALL GORONTALO', 'ANEKA ELEKTRONIK 01 - MALL CIKAMPEK', 'DIGIPLUS 40 - DIGIPLUS LIPPO PLAZA EKALOKASARI', 'A8 ELEKTRONIK BTM 01 - A8 ELEKTRONIK FURNITURE BATAM', 'GOALMOBILE 8 - IWORLD BEC LG D03', 'UFO 03 - UFO SIDOARJO', 'SYIHAB JAYA UTAMA 002 - SYIHAB STORE AYANI MARTAPURA', 'EAR 290 - ERAFONE RESINDA PARK KARAWANG', 'CAHAYA BARU ARTHA ABADI 002 - CB PHONE 1 SIDOARJO', 'EAR 425 - ERAFONE RUKO ROROTAN', 'EAR 46 - ERAFONE TAMAN PALEM PAJAJARAN', 'JAKARTA ELECTRONIC 002 - AIWA ELECTRONIC KUANINO KUPANG', 'BERKAT JAYA FURNITURE 001 - BATAM', 'ERABLUE 63 - ERABLUE ELECTRONICS TELUK JAMBE', 'ERABLUE 56 - ERABLUE ELECTRONICS MERCEDES BENZ', 'IBOX 05 - SUMMARECON MALL BEKASI', 'BENGKONG JAYA FURNITURE 001 - BATAM', 'EAR 36 ERAFONE 1 AMBASADOR', 'ERABLUE 10 - ERABLUE ELECTRONICS JATIMULYA', 'IBOX 182 - CITIMALL GORONTALO', 'GUDANG CELL 01 - HANDPHONE PUSAT', 'GTN 140 - BLIBLI STORE RESINDA PARK MALL', 'DC 007 - TOP ONE CELL WTC 823', 'SENTRA 001 - SENTRA OPPO L2 R205-207', 'CAHAYA ELEKTRONIK JAYA 01 - MATARAM', 'NATURAL FURNITURE & ELEKTRONIK 001 - KENDARI', 'SYIHAB JAYA UTAMA 001 - SYIHAB STORE AYANI BANJARBARU', 'APOLLO 17 - WADUNG ASRI', 'MII URBAN REPUBLIC 067 - URBAN REPUBLIC DP MALL SEMARANG', 'MII URBAN REPUBLIC 018 - URBAN REPUBLIC LOMBOK EPICENTRUM MALL', 'HACOM 06 - MANUKAN', 'EAR 1083 - ERAFONE MEGASTORE RUKO PURWAKARTA', 'EAR 31 ERAFONE ARION MALL', 'GTN 264 - BLIBLI STORE BLUE GORONTALO', 'IBOX 171 - IBOX MEGAMALL BATAM', 'GEMILANG JAYA 002 - GEMILANG JAYA IT CENTER', 'ANDALAS 10 - GUNUNG MALANG SUTOYO', 'EAR 90 - ERAFONE AEON TANJUNG BARAT'
];

var OFFLINE_MERCHANT_DOWNGRADE = [
    /* Batam Area Tradi */
    '7340c6ee-f4ce-11ef-89b0-6f17da6671f2', 
    '0305efd6-2af5-11f0-a504-0f84cdbac718',
    '6ee30fd8-a7dd-11ef-952a-271321a27ad0',
    '9ae74d8c-a7df-11ef-8362-a9a1c58f513d',
    'a1417e89-edcc-11ef-a94a-bdb3d6908e86',
    '7098e8c1-d8c9-11ef-910c-c77c400a204f',
    'd10edc06-d8ca-11ef-8606-ed7e73775513',
    '9520d726-a7d3-11ef-9aaa-e7c2241d7a12',
    'c3a2e121-4cd2-11f0-82f5-abbffabe0adb',
    'c78430ac-6cf2-11f0-9374-c5481c8b55be',
    'a7c6b733-8786-11ef-8790-31c1d963305a',
    'a7d0c95e-8786-11ef-8790-672487b3da43',
    '3c8da565-f316-11ee-a3d0-b3c90b9fcd5e',
    'f82ea3d9-a7da-11ef-9660-db33d6836dad',
    'b91b6065-bebd-11ef-8509-97f71879a0d3',
    '77a18d82-bebc-11ef-b86b-c58f92afe434',
    '77a8926b-bebc-11ef-b86b-9b7e4f185a7d',
    'ca00da0a-20b8-11f0-978a-e937b7ea6a32',
    '7277995b-a7be-11ef-9660-0761a28f6aac',
    '7181537f-3154-11f0-a67a-d76dda82f320',
    '04451a11-3ba7-11f0-bb1c-b370556dde94',
    '04606a4a-3ba7-11f0-bb1c-810c04bfbcc3',
    '9910ca92-4ffd-11f0-8401-a744a93cf72e',
    '2c4c136f-f4d1-11ef-89b0-7f2853e3ce74',
    '2c55d778-f4d1-11ef-89b0-ef48034ad58e',
    '73f1a26c-fa39-11ef-b369-156de6cccc68',
    'cc953c4e-a7bb-11ef-952a-9d5b76ae61cf',
    '98df2531-beba-11ef-b86b-6942466dbb46',
    'c4fe0bd3-a7d9-11ef-9660-3fb56e7ec95e',
    'c505fb1c-a7d9-11ef-9660-eb5b1cb66533',
    'b0f6db62-ce53-11ef-9152-77264670183a',
    '7cd70648-f4d6-11ef-9ee3-ef88ce6a7f53',
    '7cdf1ca1-f4d6-11ef-9ee3-931dd7466c56',
    '7ce5854a-f4d6-11ef-9ee3-ef9c87a11a5d',
    'b900f95e-c139-11ef-8509-8be1004a3453',
    '64a240b0-4a96-11f0-9c02-bf551ddb6a6b',
    '64ac79e9-4a96-11f0-9c02-29e1512c6c8e',
    '64b3a5e2-4a96-11f0-9c02-dddfd6d7624b',
    '64c2e834-4a96-11f0-9c02-eba0fa60d9ba',
    'cf2d2655-03b2-11f0-8550-3d74c7634cea',
    'cf3d52fe-03b2-11f0-8550-3b2e6a1e2d24'
];

/*Offline item categorization*/
var OFFLINE_WHITELIST_ITEMS = [ 
    'find n2 flip',
    'find n3 flip',
    'vivo x80',
    'find x5'
];

var TIKET_MERCHANT_ID = 'b4f0dc58-b43e-11ea-ba26-98039b2bc484';
var EWALLET_MERCHANT_ID = '3be04791-06c6-11ef-b1a6-2d64d067f971';
var CERMATI_DIGITAL_MERCHANT_ID = '301289e7-11ef-11ec-87a2-31f7040ea4a7';

var OFFLINE_WHITELIST_ITEMS_APPLE_EDITIONS = [
    'iphone 12',
    'iphone 13',
    'iphone 14',
    'iphone 15',
    'ip 12',
    'ip 13',
    'ip 14',
    'ip 15',
    'iphone12',
    'iphone13',
    'iphone14',
    'iphone15',
    'apple 12',
    'apple 13',
    'apple 14',
    'apple 15',
    'apple12',
    'apple13',
    'apple14',
    'apple15',
    'ipad',
    'macbook',
    'imac',
    'watch'
];

var OFFLINE_WHITELIST_ITEMS_SAMSUNG_EDITIONS = [
    's21',
    's22',
    's23',
    's24',
    's25',
    's26',
    'z',
    'flip',
    'fold'
];

var sanitizedItemNames = itemNames.replaceAll("_", " ");
var lowerCaseItemNames = sanitizedItemNames.toLowerCase();
var is_current_item_offline_whitelisted_item = false;
var is_va_transaction = false;

for (merchant: VA_MERCHANTS) {
    if (merchantId == merchant) {
        is_va_transaction = true;
        break;
    }
}

var is_offline_merchant_downgrade = false;
var offline_merchant_tag = 'normal'
for (offline_merchant: OFFLINE_MERCHANT_DOWNGRADE) {
    if (merchantId == offline_merchant) {
        is_offline_merchant_downgrade = true;
        offline_merchant_tag = 'downgrade';
        break;
    }
} 

/* Assignment of Offline Merchant Risk Category */
var offline_merchant_risk_category = 'not top merchant';
var offline_merchant_risk_category_group = 'high risk';

var merchantNameLowerCase =  merchantName.toLowerCase();
for (offline_merchant: OFFLINE_MERCHANT_LOW_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'low';
        break;
    }
} 
for (offline_merchant: OFFLINE_MERCHANT_AVERAGE_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'average';
        break;
    }
} 
for (offline_merchant: OFFLINE_MERCHANT_MODERATE_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'moderate';
        break;
    }
} 
for (offline_merchant: OFFLINE_MERCHANT_HIGH_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'high';
        break;
    }
} 
for (offline_merchant: OFFLINE_MERCHANT_VERY_HIGH_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'very high';
        break;
    }
} 
/*Very Low Risk Brand Override*/
var sanitizedParentMerchantName = parentMerchantName.replaceAll(" ", "").toLowerCase();
for (offline_brand: OFFLINE_PARENT_MERCHANT_VERY_LOW_RISK) {
    if (sanitizedParentMerchantName == offline_brand.toLowerCase()) {
        offline_merchant_risk_category = 'very low';
        break;
    }
} 

if ((offline_merchant_risk_category == 'very low') || (offline_merchant_risk_category == 'low') || (offline_merchant_risk_category == 'average')) {
    offline_merchant_risk_category_group = 'ok';
}

for (item: OFFLINE_WHITELIST_ITEMS) {
    if (stringUtils.contains(lowerCaseItemNames, item)) {
        is_current_item_offline_whitelisted_item = true;
        break;
    }
}

/* samsung + (s21/s22/s23/flip/fold/z) */
for (samsung_series: OFFLINE_WHITELIST_ITEMS_SAMSUNG_EDITIONS) {
    if(stringUtils.contains(lowerCaseItemNames, 'samsung') 
    && stringUtils.contains(lowerCaseItemNames, samsung_series.toLowerCase())) {
        is_current_item_offline_whitelisted_item = true;
        break;
    }
}

/*Apple + (iphone 12/iphone 13/iphone 14/iphone 15/ipad/macbook/imac/watch)*/
for (apple_series: OFFLINE_WHITELIST_ITEMS_APPLE_EDITIONS) {
    if(stringUtils.contains(lowerCaseItemNames, 'apple') 
    && stringUtils.contains(lowerCaseItemNames, apple_series.toLowerCase())) {
        is_current_item_offline_whitelisted_item = true;
        break;
    }
}

var is_smartphone_transaction = false;
for (itemtypes : itemTypes) {
    if (itemtypes.toLowerCase() == 'smartphone') {
        is_smartphone_transaction = true;
        break;
    }
}

/*Is tradi brands*/
var is_tradi_trx = false;
for (store_initial: TRADI_DP_BRAND_LIST) {
    if (stringUtils.contains(merchantNameLowerCase, store_initial)) {
        is_tradi_trx = true;
    } 
}

var is_exclude_from_dp = false;
for (store_initial: TRADI_DP_MERCHANT_EXCLUDE) {
    if (stringUtils.contains(merchantNameLowerCase, store_initial)) {
        is_exclude_from_dp = true;
    } 
}

var is_eligible_dp_tradi_trx = false;
if (is_tradi_trx == true && is_exclude_from_dp == false) {
    is_eligible_dp_tradi_trx = true;
    riskMerchantCategoryName = 'average';
}

var is_offline_transaction = false;
var is_offline_edc_transaction = false;
var is_offline_qr_transaction = false;
for (item_cat: itemCategories) {
    var itemCatLowerCase = item_cat.toLowerCase();
    if (itemCatLowerCase == 'offline-store' || itemCatLowerCase == 'offline-transaction'  || itemCatLowerCase == 'offline') {
        is_offline_transaction = true; /* offline-store, trx with promotors can handover */
    }
    if (itemCatLowerCase == 'offline-transaction') {
        is_offline_qr_transaction = true;
    }
    if (itemCatLowerCase == 'offline') {
        is_offline_edc_transaction = true;
    }
}

var offline_item_category = 'other';
if (is_offline_transaction) {
    offline_item_category = 'non-smartphone'
    if (is_offline_edc_transaction || is_offline_qr_transaction) {
        offline_item_category = 'QR'
    } 
    if (is_smartphone_transaction) {
        offline_item_category = 'smartphone'
        if (is_current_item_offline_whitelisted_item) {
            offline_item_category = 'high-end phone'
        }
    }
}

/*User categorization*/
var EXISTING_USERS_RISK_GRADE = [
    'A',
    'B',
    'C',
    'D',
    'E'
];

/* MUST UPDATE Definition of existing users need to be based on payment */
var is_existing_user = riskGradeOfflineScore > 0;

/* userPromoRiskGrade assignment */
if (is_offline_transaction) {
    userPromoRiskGrade = 'C';
    
    /* Score Reduction on Selected Offline Merchant (risk downgrade) */
    if (is_offline_merchant_downgrade) {
        riskGradeOfflineScore = riskGradeOfflineScore == null ? null : (riskGradeOfflineScore - 50);
        selectedReinforcedScore = selectedReinforcedScore == null ? null : ( selectedReinforcedScore - 50);
    }

      if (is_existing_user) {
        if (offline_item_category == 'smartphone' || offline_item_category == 'high-end phone') {
            /* MUST UPDATE Inconsistencies for offline score between risk query and prod due to scheduling https://reports.indodana.com/queries/24097/source 10% difference in every risk grade refresh date */
            if (hasNonLimitActiveCashLoanContract == true) {
                if (riskGradeOfflineScore >= 521) {userPromoRiskGrade = 'B'}
                if (riskGradeOfflineScore < 521) {userPromoRiskGrade = 'D'}
                if (riskGradeOfflineScore < 470) {userPromoRiskGrade = 'E'}
            } else if (offline_merchant_risk_category_group == 'high risk') {
                if (riskGradeOfflineScore >= 535) {userPromoRiskGrade = 'A'}
                if (riskGradeOfflineScore < 535) {userPromoRiskGrade = 'B'}
                if (riskGradeOfflineScore < 475) {userPromoRiskGrade = 'C'}
                if (riskGradeOfflineScore < 461) {userPromoRiskGrade = 'D'}
                if (riskGradeOfflineScore < 454) {userPromoRiskGrade = 'E'}
            } else {
                if (riskGradeOfflineScore >= 521) {userPromoRiskGrade = 'A'}
                if (riskGradeOfflineScore < 521) {userPromoRiskGrade = 'B'}
                if (riskGradeOfflineScore < 469) {userPromoRiskGrade = 'C'}
                if (riskGradeOfflineScore < 453) {userPromoRiskGrade = 'D'}
                if (riskGradeOfflineScore < 433) {userPromoRiskGrade = 'E'}
            }
        } else if (offline_item_category == 'non-smartphone' || offline_item_category == 'QR') {
            if (riskGradeOfflineScore >= 521) {userPromoRiskGrade = 'A'}
            if (riskGradeOfflineScore < 521) {userPromoRiskGrade = 'B'}
            if (riskGradeOfflineScore < 469) {userPromoRiskGrade = 'C'}
            if (riskGradeOfflineScore < 453) {userPromoRiskGrade = 'D'}
            if (riskGradeOfflineScore < 433) {userPromoRiskGrade = 'E'}
        }
    } else {
        if (offline_item_category == 'smartphone' || offline_item_category == 'high-end phone') {
            /* MUST UPDATE Reinforced score is not based on cached result from BQ2, but current selector rule version */
            if (offline_merchant_risk_category_group == 'high risk') {
                if (selectedReinforcedScore >= 460) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 400) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 380) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 360) {userPromoRiskGrade = 'E'}
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_koperasi_20240405' || selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_no_ewallet_20240912') {
                    if (selectedReinforcedScore >= 560) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 560) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 525) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 493) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'E'}
                }
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_contact_call_20250728') {
                    if (selectedReinforcedScore >= 568) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 568) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 518) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 478) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 442) {userPromoRiskGrade = 'E'}
                }
            } else {
                if (selectedReinforcedScore >= 460) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 400) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 380) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 360) {userPromoRiskGrade = 'E'}
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_koperasi_20240405' || selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_no_ewallet_20240912') {
                    if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 483) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 457) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 431) {userPromoRiskGrade = 'E'}
                }
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_contact_call_20250728') {
                    if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 469) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 440) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 410) {userPromoRiskGrade = 'E'}
                }
            }
        } else if (offline_item_category == 'non-smartphone' || offline_item_category == 'QR') {
            if (selectedReinforcedScore >= 460) {userPromoRiskGrade = 'A'}
            if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'B'}
            if (selectedReinforcedScore < 400) {userPromoRiskGrade = 'C'}
            if (selectedReinforcedScore < 380) {userPromoRiskGrade = 'D'}
            if (selectedReinforcedScore < 360) {userPromoRiskGrade = 'E'}
            if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_koperasi_20240405' || selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_no_ewallet_20240912') {
                if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 483) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 457) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 431) {userPromoRiskGrade = 'E'}
            }
            if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_contact_call_20250728') {
                if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 469) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 440) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 410) {userPromoRiskGrade = 'E'}
            }
        } 
    }   
}

/* Merchant Risk Based Pricing Rule */
if (riskMerchantCategoryName == 'Bad' || riskMerchantCategoryName == 'Very Bad') {
    rate_key_result = 'offline_transaction290k'
}

/* DO NOT REPLACE THIS SECTION - for addon transaction we will return specific rate group key */
if (merchantId == '9dbbd98c-7777-11ec-ab86-6f31bc08f747') { /* FSP */
    rate_key_result = '1month-12month-no_min_installment-int199';
}

/* aput (INTEGRATION TEAM) UAT risk grade promo  */
if (userId == '6354b3a5-8b5a-49ee-b99d-03a681aeaddc' || userId == 'af0e9f88-ad57-4781-a771-4f52c5a266f1' || userId == '6354b3a5-8b5a-49ee-b99d-03a681aeaddc' || userId == '5159dce1-b88a-45e7-a86a-a372a1250a4f' || userId == '28c47e88-939b-460b-b20f-9d60b0c15c84' || userId == 'e2d719d0-4d55-4997-8890-3f231caf7408') {
    if(stringUtils.contains(lowerCaseItemNames, 'riska')) {userPromoRiskGrade = 'A'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riskb')) {userPromoRiskGrade = 'B'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riskc')) {userPromoRiskGrade = 'C'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riskd')) {userPromoRiskGrade = 'D'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riske')) {userPromoRiskGrade = 'E'} 
}

if ((masterUserId == null || masterUserId == '') && (userId != null || userId != '')) {
    masterUserId = userId
}

var whitelistedResults = null;
if (masterUserId != null && masterUserId != '') {
  whitelistedResults = blacklistHelper.getWhitelists([
    {"type": 'users', "namespace": 'offline-mp-higher-rate-cde', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'mandatory-dp-offline-mp-higher-rate-cde', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'traditional-mp-eligible-promo', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'traditional-mandatory-dp-offline-mp', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'phase-2-cash-loan-via-limit', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'tiket-additional-approval-higher-pricing', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'above-480-nonmp-downlimit-highrate-experiment', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'below-480-nonmp-downlimit-highrate-experiment', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'risk-reactivation', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'ecommerce-va-payment-auto', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'ecommerce-va-payment', "searchField": {"userId": masterUserId}}

  ]);
}

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------ Offline OVERWRITE RBP -------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/

if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
    userPromoRiskGrade = 'E';
}

/*[CHRISTIE] Additional Approval High Risk Erafone Roadside Experiment, rate 3.5% 99k-259k */
/* ------------------------------------------------------------------------------------------------*/
var is_additional_approval_mp_cde = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'offline-mp-higher-rate-cde', {"userId": masterUserId}, whitelistedResults);

/* 
C - admin 199k, bunga 3.49%
D - admin 199k, bunga 3.99%
E - admin 349k, bunga 4.49% 
*/
if (is_additional_approval_mp_cde && userPromoRiskGrade == 'C' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
    isTrxAllowedToUsePromo = false;
}
else if (is_additional_approval_mp_cde && userPromoRiskGrade == 'D' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
    isTrxAllowedToUsePromo = false;
}
else if (is_additional_approval_mp_cde && userPromoRiskGrade == 'E' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    isTrxAllowedToUsePromo = false;
}
else if (is_additional_approval_mp_cde && !['C','D','E'].contains(userPromoRiskGrade)) {
    rate_key_result = merchantCreditRateGroupKey;
    isTrxAllowedToUsePromo = true;
}

/*[CHRISTIE] Additional Approval High Risk Erafone Roadside Experiment, rate 3.5% 99k-259k */
var is_mandatory_dp_additional_approval_mp_cde = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'mandatory-dp-offline-mp-higher-rate-cde', {"userId": masterUserId}, whitelistedResults);

/* 
C - admin 199k, bunga 3.49%
D - admin 199k, bunga 3.99%
E - admin 349k, bunga 4.49%

4 Dec 
C/D/E - admin 349k, bunga 4.49%
*/


if (is_mandatory_dp_additional_approval_mp_cde && userPromoRiskGrade == 'C' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    dp_rate = 0.1;
    isTrxAllowedToUsePromo = false;
}
else if (is_mandatory_dp_additional_approval_mp_cde && userPromoRiskGrade == 'D' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    dp_rate = 0.1;
    isTrxAllowedToUsePromo = false;
}
else if (is_mandatory_dp_additional_approval_mp_cde && userPromoRiskGrade == 'E' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    dp_rate = 0.1;
    isTrxAllowedToUsePromo = false;
}
else if (is_mandatory_dp_additional_approval_mp_cde && !['D','E'].contains(userPromoRiskGrade)) {
    rate_key_result = merchantCreditRateGroupKey;
    isTrxAllowedToUsePromo = true;
}

/* Non-MP Downlimit Project Higher Rate */
/* ------------------------------------------------------------------------------------------------*/
var above_480_nonmp_downlimit_highrate_experiment = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'above-480-nonmp-downlimit-highrate-experiment', {"userId": masterUserId}, whitelistedResults);

var below_480_nonmp_downlimit_highrate_experiment = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'below-480-nonmp-downlimit-highrate-experiment', {"userId": masterUserId}, whitelistedResults);


/* 
- OFFLINE SET A -

- Identity Above 480++
--- 372++ - 4.60% (6Mio)
--- 407++ - Normal Price (9Mio)
--- 420++ - Normal Price (12.5Mio)

- Identity Below 480++
--- 372++ - 4.60% (6Mio)
--- 410++ - 3.90% (9Mio)
--- 420++ - Normal Price (12.5Mio)

- OFFLINE SET B -

- Identity Above 480++
--- 315++ - 4.60% (6Mio)
--- 361++ - Normal Price (9Mio)
--- 386++ - Normal Price (12.5Mio)

- Identity Below 480++
--- 315++ - 4.60% (6Mio)
--- 376++ - 3.90% (9Mio)
--- 386++ - Normal Price (12.5Mio)
*/

if (above_480_nonmp_downlimit_highrate_experiment || below_480_nonmp_downlimit_highrate_experiment){

    /* - OFFLINE SET A - */
    if (experiment_offline == 'offline_set_a'){

        if (above_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 420) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 407) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 372) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        } else if (below_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 420) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 410) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
                isTrxAllowedToUsePromo = false;
            } else if (selectedReinforcedScore >= 372) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        }
    } 

    /* - OFFLINE SET B - */
    else if (experiment_offline == 'offline_set_b'){
        
        if (above_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 386) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 361) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 315) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        } else if (below_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 386) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 376) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_349';
                isTrxAllowedToUsePromo = false;
            } else if (selectedReinforcedScore >= 315) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        }
    }

    if (loanAmount < 1000000){
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
}





/*Tradi Eligible Promo, B and D*/
var submit_traditional_eligible_promo = whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'traditional-mp-eligible-promo', {"userId": masterUserId}, whitelistedResults);

var submit_traditional_mandatory_dp_no_promo = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'traditional-mandatory-dp-offline-mp', {"userId": masterUserId}, whitelistedResults);;


/* 
Submit Tradi Eligible Promo (B/D)
-- new user (pefindo)
510++ - B Treatment
440++ - D Treatment
360++ - D Treatment (set A)
*/

if (submit_traditional_eligible_promo){
    if (selectedReinforcedScore >= 510) {
        userPromoRiskGrade = 'B';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    else if (selectedReinforcedScore >= 440) {
        userPromoRiskGrade = 'D';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    /*Mandatory DP set A*/
    else if (selectedReinforcedScore >= 360) {
        userPromoRiskGrade = 'D';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
}

/*
Submit Tradi No Promo Mandatory DP
-- new user (pefindo)
420++ - admin 190k, bunga 3.00% (set B)
400++ - admin 199k, bunga 3.49% (set B)
360++ - admin 199k, bunga 3.99% (set B)
*/

else if (submit_traditional_mandatory_dp_no_promo){
    /*Mandatory DP set B*/
    if (selectedReinforcedScore >= 420) {
        rate_key_result = 'offline_transaction190k'; 
        dp_rate = is_smartphone_transaction == true ? 0.1 : 0;
        isTrxAllowedToUsePromo = false;
    }
    else if (selectedReinforcedScore >= 400) {
        rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
        dp_rate = is_smartphone_transaction == true ? 0.1 : 0;
        isTrxAllowedToUsePromo = false;
    }
    else if (selectedReinforcedScore >= 360) {
        rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
        dp_rate = is_smartphone_transaction == true ? 0.1 : 0;
        isTrxAllowedToUsePromo = false;
    }

    if (loanAmount < 1000000){
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
        dp_rate = 0;
    }
}

/*
Existing Tradi Eligible Promo (B/D)
-- existing user (offline RG score)
540++ - B Treatment
485++ - D Treatment
0++   - D treatment (set A)

Existing Tradi No Promo Mandatory DP
-- existing user (offline RG score)
460++ - admin 190k, bunga 3.00% (set B)
450++ - admin 199k, bunga 3.49% (set B)
0++ - admin 199k, bunga 3.99% (set B)
*/

else if (is_eligible_dp_tradi_trx && is_existing_user){
    if (riskGradeOfflineScore >= 540) {
        userPromoRiskGrade = 'B' ;
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    else if (riskGradeOfflineScore >= 485) {
        userPromoRiskGrade = 'D';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    else if (mandatory_dp_tradi_experiment == 'set_a'){
        if (riskGradeOfflineScore > 0) {
            userPromoRiskGrade = 'D';
            rate_key_result = merchantCreditRateGroupKey;
            isTrxAllowedToUsePromo = true;
        }
    }
    else if (mandatory_dp_tradi_experiment == 'set_b'){
        if (riskGradeOfflineScore >= 460) {
            rate_key_result = 'offline_transaction190k'; 
            dp_rate = is_smartphone_transaction == true ? 0.1 : 0;
            isTrxAllowedToUsePromo = false;
        }
        else if (riskGradeOfflineScore >= 450) {
            rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
            dp_rate = is_smartphone_transaction == true ? 0.1 : 0;
            isTrxAllowedToUsePromo = false;
        }
        else if (riskGradeOfflineScore > 0) {
            rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
            dp_rate = is_smartphone_transaction == true ? 0.1 : 0;
            isTrxAllowedToUsePromo = false;
        }
    }
}



/* Greylist */
var is_greylist = 
    whitelistedResults != null && blacklistHelper.isWhitelistedByNamespaceAndReasonBulkCheck('users', 'phase-2-cash-loan-via-limit', 'greylist', {"userId": masterUserId}, whitelistedResults);

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* -------------------------------------- VA Transaction RBP --------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
var ab_test_va_rbp = '';
if (is_va_transaction) {
    if (is_greylist) {
        rate_key_result = 'va_new_rate_2024_09';
    } else if (sumPaymentVaBeforeTrx <= 0 && hasNonLimitActiveCashLoanContract == true) {
        ab_test_va_rbp = abTestingHelper.getVariation(masterUserId, 'RISK_VA_RBP', 'NORMAL');
        
        if (ab_test_va_rbp == 'HIGHER') {
            rate_key_result = 'va_new_rate_2024_09';
        } 
    } else if (sumPaymentVaBeforeTrx <= 0 && userLastActivitySegment == 'CASH_LOAN') {
        ab_test_va_rbp = abTestingHelper.getVariation(masterUserId, 'RISK_VA_RBP', 'NORMAL');
        if (ab_test_va_rbp == 'HIGHER') {
            rate_key_result = 'va_new_rate_2024_09';
        } 
    } else if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        /*------------------------------------- Reactivated Accounts Higher Price For First 60d -------------------------------*/
        rate_key_result = 'va_new_rate_2024_09';
    } else if ((whitelistedResults != null) && !(blacklistHelper.isWhitelistedBulkCheck('users', 'ecommerce-va-payment', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'va_new_rate_2024_09';
    }
}

/* ------------------------------------------------------------------------------------------------*/


if (userId == 'placeholder' && merchantId == TIKET_MERCHANT_ID) {
    rate_key_result = 'va_new_rate_2024_09';
}

if (merchantId == 'a74697e8-8cd8-11ee-b7ee-a94b5e22674c') {
    dp_rate = 0.3;
}

/*------------------------------------- Override Business Partner / Key Account / VIP ------------------------------------------*/
if (userId == '824633a8-95e4-43d1-b4c1-6befb986ec6d' || userId == '2c4d57e0-5853-4c3a-a886-c67e6b7142b3') {
  userPromoRiskGrade = 'A';
  is_trx_allowed_to_use_promo = true;
  dp_rate = 0;
  rate_key_result = merchantCreditRateGroupKey;
}

/* ---------------------------------------------------------------------------------------*/
/* ---------------------------------------------------------------------------------------*/
/* -------------------------------------- TIKET RBP --------------------------------------*/
/* ---------------------------------------------------------------------------------------*/
/* ---------------------------------------------------------------------------------------*/

/*------------------------------------- TIKET Additional 10% Higher Approval -------------------------------*/
var submit_tiket_additional_approval = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'tiket-additional-approval-higher-pricing', {"userId": masterUserId}, whitelistedResults);

/* 
Submit Additional 10% Higher Approval
-- new user 365-400(5.2% Flat)
1 month  : 6.59%
3 month  : 5.48%
6 month  : 5.02%
12 month : 4.98%
*/
if (merchantId == TIKET_MERCHANT_ID) {
    if (submit_tiket_additional_approval) {
        if ((selectedReinforcedScore >= 365) && (selectedReinforcedScore < 410) ) {
            rate_key_result = 'tiket-additional-approval-higher-pricing-522';
        }
    }
}


if (merchantId == TIKET_MERCHANT_ID) {
    /*------------------------------------- TIKET Experiment raise 1 month tenure max amount to 3 mio -------------------------------*/
    ab_test_tiket_3mio_1mo = abTestingHelper.getVariation(masterUserId, 'TIKET_1MO_3MIO_EXPERIMENT', 'NORMAL');
    if(ab_test_tiket_3mio_1mo == 'HIGHER') {
        rate_key_result = submit_tiket_additional_approval ? 'tiket-additional-approval-3mio-1mo-522' : 'tiket-paylater-3mio-1mo-experiment';
    }
    /* Yohanes + Rio + Novela testing */
    if ((userId == 'c03454bb-8c64-49d2-ac34-89b529e034e5' || userId == '93bd2d33-81c1-4eec-8ace-706d95b4cf20' || userId == 'b038338b-fe0b-40cc-9beb-aea62054c877') && merchantId == TIKET_MERCHANT_ID) {
        rate_key_result = submit_tiket_additional_approval ? 'tiket-additional-approval-3mio-1mo-522' : 'tiket-paylater-3mio-1mo-experiment';
    }
    /*------------------------------------- Reactivated Accounts Higher Price For First 60d -------------------------------*/
    if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'tiket-paylater-expensive-reactivate';
    }
}
/* ------------------------------------------------------------------------------------------------*/

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ---------------------------------------- E-WALLET RBP ------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
if (merchantId == EWALLET_MERCHANT_ID) {
    if(stringUtils.contains(lowerCaseItemNames, 'dana')) {
        rate_key_result = 'stellar-ewallet-expensive-nov25';
    }
    if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'stellar-ewallet-expensive-nov25';
    } else if ((whitelistedResults != null) && !(blacklistHelper.isWhitelistedBulkCheck('users', 'ecommerce-va-payment', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'stellar-ewallet-new-users';
    }
}
/* ------------------------------------------------------------------------------------------------*/

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ---------------------------------------- CERMATI DIGITAL (STELLAR) RBP ------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
if (merchantId == CERMATI_DIGITAL_MERCHANT_ID) {
    if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'va_new_rate_2024_09';
    }
}
/* ------------------------------------------------------------------------------------------------*/


return {
    "rate_group_key": rate_key_result,
    "user_promo_risk_grade": userPromoRiskGrade,
    "is_trx_allowed_to_use_promo": isTrxAllowedToUsePromo,
    "is_existing_user": is_existing_user,
    "is_offline_transaction": is_offline_transaction,
    "offline_item_category": offline_item_category,
    "mandatory_dp_rate": dp_rate,
    "offline_merchant_tag":offline_merchant_tag,
    "offline_merchant_risk_category":offline_merchant_risk_category,
    "offline_merchant_risk_category_group":offline_merchant_risk_category_group,
    "ab_test_va_rbp": ab_test_va_rbp,
    "risk_grade_offline_score" : riskGradeOfflineScore,
    "mandatory_dp_tradi_experiment" : mandatory_dp_tradi_experiment,
    "is_smartphone_transaction" : is_smartphone_transaction,
    "experimentOffline": experiment_offline,
    "selectedReinforcedModelName" : selectedReinforcedModelName,
    "selectedReinforcedScore" : selectedReinforcedScore,
    "whitelistedResults" : whitelistedResults
};