var TRADI_DP_BRAND_LIST = [
    'abadi jmk group',
    'agatri',
    'alibaba store',
    'aneka elektronik',
    'aneka meubel & elektronik',
    'asiang com',
    'ask jaya cell',
    'aurora',
    'bandara ponsel',
    'bayang bayang langit',
    'bedjo tech',
    'bgp',
    'bintank cell',
    'biz telekom',
    'cahaya baru artha abadi',
    'changfong ponsel',
    'discovery cell',
    'duta ponsel',
    'free cell',
    'galaxy gadget',
    'garuda teknik',
    'gh shop',
    'global communication',
    'gondrong cell',
    'guffy cell',
    'gumilar',
    'harmony ponsel',
    'hoki jaya sentosa',
    'ide komunika',
    'indo bismar',
    'isob gadget',
    'jc my phone',
    'jc phone',
    'jh phone',
    'kana',
    'kana manado',
    'karya cell',
    'langgeng djoyo',
    'las vegas',
    'like phonecell',
    'mackindo jaya',
    'maraphone',
    'max primera telecom',
    'media cell',
    'media jaya cell',
    'mega selindo',
    'mitra agung',
    'muraiki',
    'naga mas group',
    'okey megah perkasa',
    'pasar ponsel',
    'pertemuan cellular',
    'pluto sellular',
    'prima elektronik banjaran',
    'pusat hape',
    'puskrip',
    'raja ponsel',
    'sahabat celullar',
    'sinar jaya cellular',
    'sinar mas',
    'sms shop',
    'sriwijaya selular',
    'tangs ponsel',
    'tele global indo',
    'teman group',
    'terminal phone',
    'timses mandau',
    'toko tangga mas',
    'toko tasik',
    'top deal electronics',
    'top phone shop',
    'trio sukses',
    'wewe',
    'wijaya cellular',
    'wkm jaya',
    'yy mobile',        
    'top indo maju 001 - top cell atrium mall panakukang',
    'top indo maju 008 - top cell xiaomi shop rappocini'];

var TRADI_DP_MERCHANT_EXCLUDE = [
    'pluto sellular 13 - prima sellular street',
    'jc my phone 03 - kulim',
    'sinar mas 30 - selluler pusat',
    'toko tasik 01 - star centre sumedang',
    'toko tasik 02 - star komunika sumedang',
    'toko tasik 03 - elektronik sumedang',
    'bgp 02 pgc',
    'bgp 03 pgc',
    'bgp 05 pgc',
    'asia jaya 14 - asia jaya store plaza marina',
    'maraphone 001 - plasa simpang lima 01',
    'maraphone 003 - plasa simpang lima 03',
    'ask jaya cell 01 - ask cell cimindi',
    'ask jaya cell 02 - ask cell cimindi 2',
    'ask jaya cell 03 - ask cell cijerah',
    'ask jaya cell 04 - ask cell ujungberung',
    'ask jaya cell 05 - ask cell ujungberung 2',
    'ask jaya cell 06 - ask cell cicalengka',
    'aurora 01 - pamulang siliwangi',
    'aurora 02 - pamulang surya kencana',
    'aurora 03 - pamulang square d8',
    'aurora 04 - pamulang square d9',
    'aurora 05 - pamulang square d6',
    'las vegas 11 - mobile store kapas krampung',
    'las vegas 13 - mobile store gresik pangsud',
    'las vegas 15 - mobile store gresik gkb 2',
    'karya cell 01 - karya cell ciputat',
    'karya cell 02 - gallery phone cipayung',
    'karya cell 03 - best phone bsd',
    'like phonecell 01 - like phonecell majalaya',
    'like phonecell 02 - suka phone cell rancaekek',
    'mega selindo 01 mbh',
    'mega selindo 02 perumnas 3',
    'mega selindo 03 mi shop perumnas 3',
    'mega selindo 05 gosaka',
    'mega selindo 06 mbh',
    'pluto sellular 01 - pluto sellular 1',
    'pluto sellular 02 - pluto sellular 2',
    'pluto sellular 03 - pluto sellular 3',
    'pluto sellular 04 - prima sellular 1',
    'pluto sellular 05 - prima sellular 2',
    'pluto sellular 06 - utama sellular',
    'pluto sellular 07 - pluto sellular 5',
    'pluto sellular 08 - xiaomi store',
    'pluto sellular 09 - vivo store',
    'pluto sellular 10 - vivo store',
    'pluto sellular 11 - xiaomi store',
    'puskrip 001 - rungkut madya',
    'puskrip 003 - siwalan kerto',
    'puskrip 004 - rungkut tengah',
    'puskrip 005 - rungkut kidul',
    'puskrip 007 - pogot',
    'puskrip 008 - gunung anyar',
    'puskrip 009 - merr',
    'puskrip 016 - betr0',
    'maraphone 002 - plasa simpang lima 02',
    'sinar mas 01 - selluler 1',
    'sinar mas 03 - selluler lt. dasar ii',
    'sinar mas 04 - selluler 3 reborn',
    'sinar mas 05 - selluler spp',
    'sinar mas 06 - m2 new',
    'sinar mas 10 - selluler tlogosari',
    'sinar mas 11 - sms selluler tlogosari',
    'sinar mas 12 - selluler shop tlogosari',
    'sinar mas 14 - sms selluler ngaliyan ii',
    'sinar mas 15 - selluler banyumanik',
    'sinar mas 17 - selluler karangawen',
    'sinar mas 18 - selluler kaliwungu',
    'sinar mas 19 - selluler veteran - kudus',
    'sinar mas 20 - kudus simpang 7 - kudus',
    'sinar mas 21 - sms selluler menara - kudus',
    'sinar mas 22 - selluler jepara - mayong',
    'sinar mas 23 - selluler serayu - tegal',
    'sinar mas 24 - selluler kartini - tegal',
    'sinar mas 25 - selluler pancasila - tegal',
    'sinar mas 26 - selluler sudibyo - tegal',
    'sinar mas 27 - selluler shop pancasila - tegal',
    'sinar mas 28 - bumiayu - brebes',
    'sinar mas 29 - selluler salatiga',
    'sms shop 01 - display simpanglima',
    'sms shop 04 - depan simpanglima',
    'sms shop 05 - atas simpanglima',
    'sms shop 06 - mega simpanglima',
    'sms shop 07 - xiaomi simpanglima',
    'sms shop 12 - sambiroto',
    'sms shop 13 - gajah',
    'sms shop 14 - lampersari',
    'sms shop 16 - pemuda',
    'sms shop 17 - banyumanik 1',
    'sms shop 18 - banyumanik 2',
    'sms shop 19 - mijen boja',
    'sms shop 21 - ungaran 2',
    'sms shop 22 - babadan',
    'sms shop 24 - ambarawa 2',
    'sms shop 26 - demak',
    'sms shop 27 - purwodadi 1',
    'sms shop 28 - purwodadi 2',
    'sms shop 29 - jepara',
    'sms shop 30 - salatiga kosambi',
    'hoki jaya sentosa 001 - rajawali cell tlogosari',
    'hoki jaya sentosa 002 - rajawali cell kaliwungu i',
    'hoki jaya sentosa 003 - rajawali cell kaliwungu ii',
    'hoki jaya sentosa 004 - sinar cell tlogosari',
    'hoki jaya sentosa 005 - nagasakti cell tlogosari',
    'hoki jaya sentosa 007 - indocell tlogosari',
    'hoki jaya sentosa 008 - indocell sambiroto',
    'hoki jaya sentosa 009 - indocell banyumanik',
    'hoki jaya sentosa 010 - indocell ungaran',
    'hoki jaya sentosa 012 - indocell mijen',
    'hoki jaya sentosa 013 - indocell kaliwungu',
    'hoki jaya sentosa 014 - indocell wolter',
    'media cell 01 - media cell',
    'media cell 02 - seni abadi',
    'alibaba store 011 - original store grosir pasuruan',
    'alibaba store 013 - original store pandaan',
    'biz telekom 08 - bismar ponsel pasuruan',
    'sms shop 02 - tlogosari 3',
    'sms shop 10 - tlogosari 1',
    'sms shop 11 - tlogosari 2',
    'jc phone 02 kramat jati',
    'tele global indo 018 - telering yogyakarta 1',
    'tele global indo 027 - telering yogyakarta 2 ( ses yogya )',
    'tele global indo 041 - telering godean yogya',
    'mitra agung 01 - mitra agung electronic',
    'sms shop 25 - mranggen',
    'hoki jaya sentosa 011 - indocell thamrin',
    'hoki jaya sentosa 015 - indocell mranggen',
    'sinar mas 16 - selluler mranggen',
    'pertemuan cellular 010 - oppo store',
    'pertemuan cellular 02 - tuparev',
    'pertemuan cellular 03 - brigpol sukama',
    'pertemuan cellular 04 - telukjambe',
    'pertemuan cellular 05 - dewi sartika',
    'wkm jaya 01 - ryzla phone shop',
    'wkm jaya 02 - laku laku 1',
    'wkm jaya 03 - laku laku 2',
    'wkm jaya 04 - laku laku 3',
    'wkm jaya 05 - jtc mobile phone shop',
    'wkm jaya 06 - djogja cell',
    'aneka elektronik 01 - mall cikampek',
    'aneka elektronik 02 - bike',
    'asiang com 01 - dumai',
    'sinar mas 31 - huawei store ciputra',
    'sinar mas 32 - huawei store paragon',
    'like phonecell 03 - bless mobile ciparay',
    'kana 01 - kana computer gejayan',
    'kana 02 - jj komputer',
    'kana 03 - lenovo exclusive store by kana',
    'kana 04 - asus exclusive store by kana',
    'langgeng djoyo 003 - lancar djoyo cell gkb gresik',
    'sms shop 32 - sampangan',
    'sms shop 33 - simongan',
    'prima elektronik banjaran 02 - prima elektronik gading soreang'
];

var abtestUniqueId = mainApplicationCreditLimitOrderId == null ? "static-bucket-id" : mainApplicationCreditLimitOrderId;

var mandatory_dp_tradi_experiment = abTestingHelper.getVariation(abtestUniqueId, 'mandatory_dp_tradi_experiment', 'default_value');

var experiment_offline = abTestingHelper.getVariation(abtestUniqueId, 'offline_simplification_ab_test_2025', 'default_value');

/*Default rate key assignment*/
var dp_rate = 0;
var rate_key_result = merchantCreditRateGroupKey;
var isTrxAllowedToUsePromo = true;
var userPromoRiskGrade = '';

/* offlineFeatures */
var userLastActivitySegment = offlineFeatures['userTransactionHistoryFeatures']['userLastActivitySegment'] == null ? "-99" : offlineFeatures['userTransactionHistoryFeatures']['userLastActivitySegment'];
var sumPaymentVaBeforeTrx = offlineFeatures['userTransactionHistoryFeatures']['sumPaymentVaBeforeTrx'] == null ? -99 : offlineFeatures['userTransactionHistoryFeatures']['sumPaymentVaBeforeTrx'];

var VA_MERCHANTS = [
    '77337991-bf38-11ee-a258-31e5ebb41a87' /*agoda*/
    ,'4ede4340-ab7b-11ee-9642-9f3f449c6c33' /*lazada*/
    ,'826b91a3-a0b0-11ee-90cf-23cf2d34ee74' /*shopee*/
    ,'184ab49f-ab7b-11ee-8196-87e351c1a74e' /*tiktok*/
    ,'209b4e8b-7324-11ee-9749-abb1dc7c3e41' /*tokopedia*/
    ,'642cbedd-b99a-11ee-9b3e-fbaefd543359' /*zalora*/
    ,'fe70c52c-7588-11ef-b98b-5754b239ed4d' /*traveloka*/
];

var MODERN_BRAND_CITY_TIER = [
    'ERAFONE',	'IBOX',	'ERABLUE',	'GTN',	'HARTONOELEKTRONIK',	'DIGIMAP',	'DIGIPLUS',	'KAWANLAMA INFORMA',	'ELECTRONICCITY',	'PLANETGADGET',	'KAWANLAMA INFORMA ELEKTRONIK',	'GAN',	'CELULLARWORLD',	'MIIURBANREPUBLIC',	'YOGYA',	'NASA',	'MITRAHUBINDONESIA',	'UFO',	'CATURMITRASEJATISENTOSA',	'ADVANCE',	'HYPERMART',	'KAWANLAMA SELMA',	'AGRESID',	'BERKAHBERSAMATARAPHONE',	'SEMERU',	'MEGALLERY',	'ATRIA',	'LOTTE',	'LOTTEGROSIR',	'SUARAELEKTRO',	'COURTS',	'GAYATRI',	'GRANDBUMIMAS',	'GRAMEDIA',	'MANADOMITRABERSAMA',	'MEGADIGITAL',	'HARTONOMOBILE',	'KAWANLAMA',	'GOOD',	'ELSID',	'FONEL',	'SJSPLAZAPADANG',	'MDPSUPERSTORE',	'LOGINMEGASTORE',	'ALASKA MAKASSAR',	'JEFINDOTEKNOLOGI',	'KLIKNKLIK',	'FELIXINDO',	'YAMADABEST',	'PIXELELECTROSMART',	'JAYAGRAHAABADI',	'PTATAKRIBGROUP',	'NEWSTORETANGCITY',	'INDOCELL',	'KLACOMPUTER',	'TARAPHONE',	'ANYELIRPONSEL',	'OB',	'RAPPANG',	'LAVITAJAYAMANDIRI',	'SUMBERSAMUDERAREZEKI',	'BSTORE',	'CELLULAR',	'AGRESJOGJATEKNOLOGI',	'PUTRANIAGALESTARI',	'DIANAEVAFURNITURE',	'CANDIJITUINDONESIA',	'SCANDIA',	'BALISATUCOMPUTER',	'CELULLAR WORLD',	'OFFOLIVING',	'PERFECTHEALTH',	'ELECTRONIC CITY',	'BITCOM',	'ALASKA MAKASSAR IT GADGET',	'LULUHYPERMART',	'ABSOLUTEFITMITRAINDONESIA',	'AGRES.ID',	'DEKORUMA'
];

var OFFLINE_PARENT_MERCHANT_VERY_LOW_RISK = [
  'IBOX','GTN','GAN','DIGIMAP','DIGIPLUS','PLANETGADGET','MEGALLERY','MITRAHUBINDONESIA','CELULLARWORLD'
];

var OFFLINE_MERCHANT_LOW_RISK = [
  "ABSOLUTEFIT MITRA INDONESIA 008 - KWITANG","ABSOLUTEFIT MITRA INDONESIA 002 - ABSOLUTEFIT CENGKARENG","ABSOLUTEFIT MITRA INDONESIA 003 - ABSOLUTEFIT TANJUNG PRIOK","ABSOLUTEFIT MITRA INDONESIA 005 - ABSOLUTEFIT MENTENG","ABSOLUTEFIT MITRA INDONESIA 006 - ABSOLUTEFIT KEBON JERUK XTENSION","ADVANCE 133 - MITRA10 ANTASARI","ADVANCE 17 MITRA10 QBIG","ADVANCE 197 NUANSA ELEKTRONIK MATOS","ADVANCE 202 SAMARINDA SQUARE","ADVANCE 44 MALL BOEMI KEDATON","ADVANCE 48 MITRA10 TANJUNG APIAPI","ALASKA MANDIRI CEMERLANG 01 - MAKASSAR","ANYELIR PONSEL 001 - NEW KESIMAN DENPASAR","ANYELIR PONSEL 002 - LIKE NEW KESIMAN DENPASAR","APOLLO 03 - WTC SPP","APPEL HOUSE 03 - APPEL HOUSE BABARSARI","ATLANTA 02 - NGALIYAN","BELANJA DIGITAL BORNEO 001 - BORNEO STORE BANJARMASIN GADGET","BERKAH BERSAMA TARA 07 NEW - SURABAYA","BERKAH BERSAMA TARA 09 NEW - SIDOARJO","BERKAH BERSAMA TARA NEW 01 - TUKAD BARITO","BERKAH BERSAMA TARA NEW 03 - DALUNG","BERKAH BERSAMA TARA NEW 05 - MALANG","BINA KARYA SARANA BANGUN 002 - PLAZA BANGUNAN ELECTRONIC","BOOSTERFITS 01 BEKASI","BUMI MAS BALI PRIMA 001 - BUMI MAS ELEKTRONIK & FURNITURE TABANAN","CANDI JITU INDONESIA 01 - CANDI ELEKTRONIK SOLO PREMIUM","MITRA10 008 - PASAR BARU","MITRA10 020 - CIBUBUR","MITRA10 026 - A YANI SURABAYA","MITRA10 033 - SUNAN GUNUNG JATI CRB","MITRA10 038 - TANJUNG API API","MITRA10 046 - TASIKMALAYA","MITRA10 047 - SERANG","MITRA10 054 - GARUT","MITRA10 055 - TENTH AVENUE BANDUNG","CATUR WARGA COMPUTER 01 - CATUR WARGA COMPUTER MATARAM","CELULLAR WORLD 17 - ARENA LIKE NEW TEUKU UMAR","CELLULAR WORLD 01 - TEUKU UMAR","CELLULAR WORLD 02 - GATSU","CELLULAR WORLD 08 - SES TEUKU UMAR","CELLULAR WORLD 09 - E WORLD","CELULLAR WORLD 12 - ARENA","DARGAN CELL 01 - SOEKARNO HATTA","DAZZLE 001 - SUPER DAZZLE GEJAYAN","DENPASAR ELEKTRONIK & FURNITURE 001 - DENPASAR ELEKTRONIK & FURNITURE GATSU TIMUR","DEVSTORE 002 - NEW GATSU","DEVSTORE 005 - NEW BLAHKIUH","DIGIMAP 02 - DIGIMAP GRAND INDONESIA","DIGIMAP 08 - DIGIMAP TRANS CIBUBUR MALL","DIGIMAP 09 - DIGIMAP AEON MALL BSD","DIGIMAP 10 - DIGIMAP SUPERMALL KARAWACI","DIGIMAP 12 - DIGIMAP AEON MALL SENTUL","DIGIMAP 14 - DIGIMAP AEON TANJUNG BARAT","DIGIMAP 16 - DIGIMAP LIPPO PLAZA KRAMAT JATI","DIGIMAP 17 - DIGIMAP PLAZA BLOK M","DIGIMAP 18 - DIGIMAP PONDOK INDAH MALL 2","DIGIMAP 28 - DIGIMAP TRANS STUDIO MALL BANDUNG","DIGIMAP 29 - DIGIMAP 23 PASKAL MALL","DIGIMAP 34 - DIGIMAP PAKUWON MALL","DIGIMAP 35 - DIGIMAP TUNJUNGAN PLAZA 3","DIGIMAP 36 - DIGIMAP GRESSMALL GRESIK","DIGIMAP 38 - DIGIMAP GALAXY MALL","DIGIMAP 39 - DIGIMAP GALERIA MALL","DIGIMAP 42 - DIGIMAP PLAZA MALIOBORO YOGYA","DIGIMAP 43 - DIGIMAP SOLO SQUARE","DIGIMAP 44 - DIGIMAP PAKUWON MALL SOLO BARU","DIGIMAP 45 - DIGIMAP CENTRE POINT MEDAN","DIGIMAP 49 - DIGIMAP THE PARK KENDARI","DIGIMAP 51 - DIGIMAP BASKO PADANG","DIGIMAP 52 - DIGIMAP AYANI PONTIANAK","DIGIMAP 53 - DIGIMAP PALEMBANG INDAH MALL","DIGIMAP 56 - DIGIMAP CITIMALL DUMAI","DIGIMAP 60 - DIGIMAP AEON DELTAMAS","DIGIMAP 62 - DIGIMAP LIVING WORLD KOTA WISATA","DIGIMAP 63 - DIGIMAP JAVA SUPERMALL SEMARANG","DIGIMAP 64 - DIGIMAP MALANG TOWN SQUARE","DIGIMAP 66 - DIGIMAP SUN CITY MALL SIDOARJO","DIGIMAP 69 - DIGIMAP LIPPO PLAZA BATU","DIGIMAP 70 - DIGIMAP PLAZA SURABAYA","DIGIMAP 71 - DIGIMAP BINJAI MALL","DIGIMAP 74 - DIGIMAP JATINANGOR TS","DIGIMAP 76 - DIGIMAP LIPPO PLAZA MANADO","DIGIMAP 77 - DIGIMAP CITY PLAZA JATINEGARA","DIGIMAP 78 - DIGIMAP MAL CIJANTUNG","DIGIMAP 81 - DIGIMAP TENTH AVENUE","DIGIMAP 90 - DIGIMAP BASKO CITY MALL PADANG","DIGIMAP 91 - DIGIMAP KOTA BARU PARAHYANGAN","DIGIMAP 98 - DIGIMAP SUNSET ROAD BALI","DIGIPLUS 02 - DIGIPLUS BINTARO XCHANGE","DIGIPLUS 04 - DIGIPLUS MARGOCITY DEPOK","DIGIPLUS 05 - DIGIPLUS GANDARIA CITY","DIGIPLUS 09 - DIGIPLUS CIBINONG CITY MALL 2","DIGIPLUS 10 - DIGIPLUS WTC MALL SURABAYA","DIGIPLUS 102 - DIGIPLUS LOMBOK EPICENTRUM","DIGIPLUS 11 - DIGIPLUS PLAZA MARINA SURABAYA","DIGIPLUS 13 - DIGIPLUS MALL OLYMPIC GARDEN MALANG","DIGIPLUS 14 - DIGIPLUS SOLO PARAGON MALL","DIGIPLUS 15 - DIGIPLUS PAKUWON MALL YOGYAKARTA","DIGIPLUS 17 - DIGIPLUS NIPAH PARK MAKASSAR","DIGIPLUS 18 - DIGIPLUS TRANS STUDIO MALL MAKASSAR EXTENSION","DIGIPLUS 19 - DIGIPLUS LIVING WORLD DENPASAR","DIGIPLUS 20 - DIGIPLUS BIG MALL SAMARINDA","DIGIPLUS 21 - DIGIPLUS DUTA MALL BANJARMASIN","DIGIPLUS 23 - DIGIPLUS RITA SUPERMALL PURWOKERTO","DIGIPLUS 26 - DIGIPLUS PLAZA ATRIUM SENEN","DIGIPLUS 27 - DIGIPLUS QUEEN CITY MALL","DIGIPLUS 29 - DIGIPLUS SUMMARECON BANDUNG","DIGIPLUS 32 - DIGIPLUS PLAZA PARAHYANGAN BANDUNG","DIGIPLUS 33 - DIGIPLUS MALL CIPUTRA SEMARANG","DIGIPLUS 35 - DIGIPLUS POPUP SUNRISE MALL MOJOKERTO","DIGIPLUS 37 - DIGIPLUS CITIMALL GARUT","DIGIPLUS 38 - DIGIPLUS KARAWANG CENTRAL PLAZA","DIGIPLUS 40 - DIGIPLUS LIPPO PLAZA EKALOKASARI","DIGIPLUS 41 - DIGIPLUS CIREBON SUPERBLOCK","DIGIPLUS 44 - DIGIPLUS ARION MALL","DIGIPLUS 45 - DIGIPLUS JOGJA CITY MALL","DIGIPLUS 52 - DIGIPLUS LIPPO PLAZA JOGJAKARTA","DIGIPLUS 63 - DIGIPLUS THE PARK SAWANGAN","DIGIPLUS 64 - DIGIPLUS Q MALL BANJARMASIN","DIGIPLUS 67 - DIGIPLUS THE PARK PEJATEN","DIGIPLUS 68 - DIGIPLUS LIPPO PLAZA KENDARI","DIGIPLUS 71 - DIGIPLUS MALL BALI GALERIA","DIGIPLUS 74 - DIGIPLUS PALEMBANG TC","DIGIPLUS 75 - DIGIPLUS MEGA MALL BTM","DIGIPLUS 76 - DIGIPLUS PAKUWON MALL BEKASI","DIGIPLUS 82 - DIGIPLUS BEC","DIGIPLUS 88 - DIGIPLUS GRAGE MALL","DIGIPLUS 90 - DIGIPLUS SKA MALL","DIGIPLUS 93 - DIGIPLUS CITIMALL GORONTALO","DIGIPLUS 94 - DIGIPLUS LIVING WORLD GRAND WISATA","DUETTO AUDIO DAN LAMPU 002 - FORTINO PRO AUDIO MUSIC","ELECTRONIC CITY 72 - SKA","ELECTRONIC CITY 06 - MARGO","ELECTRONIC CITY 07 - BOTANI SQUARE","ELECTRONIC CITY 09 - REVO TOWN BEKASI","ELECTRONIC CITY 11 - KRAMAT JATI","ELECTRONIC CITY 15 - RUKO BUARAN","ELECTRONIC CITY 36 - METLAND CILEUNGSI","ELECTRONIC CITY 43 - TANGERANG CITY","ELECTRONIC CITY 53 - BOGOR TRADE MALL","ELECTRONIC CITY 56 - LIPPO MALL CIKARANG","ELS.ID 003 - SURAKARTA","ERABLUE 02 - ERABLUE ELECTRONICS KALI ABANG","ERABLUE 03 - ERABLUE ELECTRONICS MARGONDA","ERABLUE 06 - ERABLUE ELECTRONICS HOS COKROAMINOTO","ERABLUE 07 - ERABLUE ELECTRONICS RAWA BUNTU","ERABLUE 11 - ERABLUE ELECTRONICS KUTABUMI","ERABLUE 12 - ERABLUE ELECTRONICS SAWANGAN","ERABLUE 20 - ERABLUE ELECTRONICS SATU MARET","ERABLUE 21 - ERABLUE ELECTRONICS RAYA PARUNG","ERABLUE 22 - ERABLUE ELECTRONICS PERJUANGAN TAMAN","ERABLUE 29 - ERABLUE ELECTRONICS KARANG TENGAH JAKARTA","ERABLUE 30 - ERABLUE ELECTRONICS DURI KOSAMBI","ERABLUE 33 - ERABLUE ELECTRONICS RAYA CURUG","ERABLUE 38 - ERABLUE ELECTRONICS CIRENDEU","ERABLUE 41 - ERABLUE ELECTRONICS CEGER RAYA","ERABLUE 42 - ERABLUE ELECTRONICS PUSPITEK","ERABLUE 45 - ERABLUE ELECTRONICS H NAWI","ERABLUE 47 - ERABLUE ELECTRONICS PARUNG BOGOR","ERABLUE 48 - ERABLUE ELECTRONICS KH HASYIM ASHARI","ERABLUE 54 - ERABLUE ELECTRONICS MAUK","ERABLUE 57 - ERABLUE ELECTRONICS KRESEK","ERABLUE 62 - ERABLUE ELECTRONICS BENDA PERMAI RAYA","ERABLUE 84 - ERABLUE ELECTRONICS BUARAN RAYA","ERABLUE 88 - ERABLUE ELECTRONICS JL PIK PENGGILINGAN","EAR 02 - ERAFONE 3 MEGA BEKASI HYPERMALL","EAR 07 - ERAFONE 2 BOTANI SQUARE","EAR 09 - MEGASTORE MARGO CITY","EAR 1087 - ERAFONE AND MORE LOMBOK EPICENTRUM MALL","EAR 1090 - ERAFONE AND MORE SUN PLAZA MEDAN","EAR 15 MEGASTORE SUPERMALL KARAWACI","EAR 16 ERAFONE TANGCITY","EAR 248 - ERAFONE RUKO KOPO BANDUNG","EAR 268 - MEGASTORE TUNJUNGAN PLAZA 3","EAR 325 - ERAFONE PLAZA AMBARUKMO","EAR 339 - ERAFONE MEGASTORE SEMARANG","EAR 353 - ERAFONE MEGASTORE RUKO SINGARAJA BALI","EAR 398 - ERAFONE RUKO TEMBALANG","EAR 401 - ERAFONE MALL OLYMPIC GARDEN","EAR 51 - MEGASTORE BX CHANGE","EAR 619 - ERAFONE FRANCHISE RUKO KLIPANG","EAR 660 - ERAFONE MEGASTORE CILILITAN","EAR 665 - ERAFONE MEGASTORE MALL PANAKKUKANG","EAR 67 - ERAFONE MALL GANDARIA CITY","EAR 711 - ERAFONE BANGKA RAYA","EAR 723 - ERAFONE & MORE RUKO A YANI DENPASAR","EAR 724 - ERAFONE & MORE RUKO GATOT SUBROTO","EAR 740 - ERAFONE CIBANTENG KOJA","EAR 775 - ERAFONE & MORE KAKATUA MAKASSAR","EAR 791 - ERAFONE MEGASTORE RUKO TODDOPULI","EAR 799 - ERAFONE PALLANGGA GOWA","EAR 832 - ERAFONE RUKO SUDIRMAN PEKANBARU","EAR 841 - ERAFONE RUKO DURI RIAU","EAR 842 - ERAFONE PERAWANG RIAU","EAR 843 - ERAFONE PANGKALAN KERINCI","EAR 882 - ERAFONE RUKO ANTASARI SAMARINDA","EAR 888 - ERAFONE MEGASTORE RUKO MT HARYONO BALIKPAPAN","EAR 892 - ERAFONE AND MORE SOREANG BANDUNG","EAR 899 - ERAFONE RUKO PRAYA","EAR 904 - ERAFONE MEGASTORE PALEMBANG SQUARE","FITHUB 103 - GATSU BARAT","FITHUB 117 - NUSA DUA","FITHUB 34 - BALI RENON","FITHUB 53 - BALI TEUKU UMAR","FITHUB 65 - SUNSET ROAD","FITHUB 79 - GATSU TIMUR","GAN 01 - HELLO TRANSPARK BINTARO","GAN 02 - HELLO LIPPO MALL CIKARANG","GAN 03 - HELLO KUNINGAN CITY","GAN 04 - HELLO UPTOWN MALL","GAN 08 - HELLO DAAN MOGOT","GAN 10 - HELLO MARGONDA DEPOK","GAN 12 - HELLO JAMBU DUA","GAN 13 - HELLO GREEN PRAMUKA","GAN 14 - HELLO BUAH BATU","GAN 16 - HELLO KALIBATA CITY","GAN 17 - HELLO TEBET","GAN 18 - HELLO EASTVARA BSD","GAN 19 - HELLO MALL CIPUTRA PEKANBARU","GAN 21 - HELLO MALL OF SERANG","GAN 22 - HELLO LIVING WORLD GRAND WISATA","GAN 23 - HELLO PLAZA RENNON BALI","GAN 24 - HELLO BASSURA CITY","GAN 25 - HELLO EXHIBITION JAKARTA FAIR KEMAYORAN 2025","GAN 26 - HELLO - SAMRATULANGI MANADO","GAN 27 - HELLO TUPAREV CIREBON","GOOD PONSEL","GRAMEDIA 182 LIPPO KENDARI","GRAMEDIA 483 CILEUNGSI","GRAND BUMI MAS 001 - GATSU","GTN - SES BOTANI","GTN 100 - TUKAR TAMBAH SUPERMALL KARAWACI","GTN 111 - BLIBLI STORE GANDARIA CITY","GTN 117 - TUKAR TAMBAH TEUKU UMAR BALI","GTN 118 - BLIBLI STORE PASKAL 23","GTN 132 - BLIBLI STORE TUNJUNGAN PLAZA","GTN 134 - BLIBLI STORE LIVING WORLD DENPASAR","GTN 135 - BLIBLI STORE CIBINONG CITY MALL 2","GTN 139 - BLIBLI STORE PAKUWON SURABAYA","GTN 140 - BLIBLI STORE RESINDA PARK MALL","GTN 144 - BLIBLI STORE THE PARK SAWANGAN DEPOK","GTN 146 - BLIBLI STORE AEON SENTUL CITY","GTN 150 - BLIBLI STORE TSM MAKASSAR","GTN 151 - BLIBLI STORE MARGO CITY","GTN 154 - BLIBLI STORE LIVING WORLD ALAM SUTERA","GTN 155 - BLIBLI STORE DISCOVERY MALL BALI","GTN 156 - BLIBLI STORE SUPERMALL KARAWACI","GTN 161 - BLIBLI STORE BINTARO XCHANGE MALL 2","GTN 162 - BLIBLI STORE NIPAH MALL MAKASSAR","GTN 163 - BLIBLI STORE BLOK M PLAZA","GTN 164 - BLIBLI STORE SUMMARECON MALL BANDUNG","GTN 167 - BLIBLI STORE LIVING WORLD GRAND WISATA BEKASI","GTN 168 - BLIBLI STORE AEON MALL DELTA MAS","GTN 172 - BLIBLI STORE LIVING WORLD KOTA WISATA","GTN 173 - BLIBLI STORE LOTTE SHOPPING AVENUE KUNINGAN","GTN 174 - BLIBLI STORE SKA MALL PEKANBARU","GTN 179 - BLIBLI STORE BEC BANDUNG","GTN 180 - BLIBLI STORE TSM BALI","GTN 188 - BLIBLI STORE LIVING WORLD PEKANBARU","GTN 189 - BLIBLI STORE BLUE MALL ARTHA GADING","GTN 190 - BLIBLI STORE BLUE MALL PANAKKUKANG","GTN 191 - BLIBLI STORE BLUE CIREBON SUPER BLOCK","GTN 192 - BLIBLI STORE BLUE PARAGON SEMARANG","GTN 193 - BLIBLI STORE BLUE DAAN MOGOT","GTN 194 - BLIBLI STORE BLUE MEGAMALL MANADO","GTN 195 - BLIBLI STORE BLUE BINTARO PLAZA","GTN 196 - BLIBLI STORE BLUE MALL LIPPO CIKARANG","GTN 197 - BLIBLI STORE BLUE CIPUTRA CIBUBUR","GTN 198 - BLIBLI STORE BLUE SUN PLAZA MEDAN","GTN 199 - BLIBLI STORE BLUE BEKASI CYBER PARK","GTN 200 - BLIBLI STORE BLUE WTC SURABAYA","GTN 202 - BLIBLI STORE BLUE TANGERANG CITY","GTN 203 - BLIBLI STORE BLUE PALEMBANG SQUARE","GTN 206 - BLIBLI STORE BLUE MALL OLYMPIC GARDEN (MOG) MALANG","GTN 207 - BLIBLI STORE BLUE MALL PAKUWON SOLO","GTN 211 - BLIBLI STORE MALL RATU INDAH","GTN 227 - BLIBLI STORE BLUE GATOT SUBROTO SOLO","GTN 231 - BLIBLI STORE BLUE ITC ROXY MAS","GTN 234 - BLIBLI STORE BLUE ITC BSD","GTN 235 - BLIBLI STORE BLUE PEJATEN VILLAGE","GTN 236 - BLIBLI STORE BLUE KALIBATA CITY","GTN 237 - BLIBLI STORE BLUE BASSURA","GTN 241 - BLIBLI STORE CILEGON CENTER MALL","GTN 243 - BLIBLI STORE PALEMBANG INDAH MALL","GTN 251 - BLIBLI STORE AEON MALL TANJUNG BARAT","GTN 252 - BLIBLI STORE MEGA MALL BATAM CENTER","GTN 256 - BLIBLI STORE PAKUWON MALL BEKASI","GTN 257 - BLIBLI STORE PLAZA MEDAN FAIR","GTN 263 - BLIBLI STORE RITA SUPERMALL","GTN 264 - BLIBLI STORE BLUE GORONTALO","GTN 265 - BLIBLI STORE SUMMARECON MALL SERPONG","GTN 269 - BLIBLI STORE PARAGON SOLO","GTN 270 - BLIBLI STORE DUMAI CITY MALL","GTN 274 - BLIBLI STORE PTC PALEMBANG","GTN 276 - BLIBLI STORE ICON MALL GRESIK","GTN 277 - BLIBLI STORE CIPUTRA JAKARTA","GTN 282 - BLIBLI STORE JAMBU DUA","GTN 284 - BLIBLI EXHIBITION JAKARTA FAIR KEMAYORAN 2025","GTN 29 - POINT 2000 KOTA KASABLANKA","GTN 290 - BLIBLI STORE BLACK ITC ROXY MAS","GTN 302 - BLIBLI STORE PONDOK INDAH MALL 1","GTN 321 - BLIBLI STORE BASKO CITY MALL","GTN 59 - TUKAR TAMBAH CCM","GTN 86 - BLIBLI STORE CENTRAL PARK","GTN 91 - BLIBLI STORE TSM CIBUBUR","GTN 92 - BLIBLI STORE LIPPO MALL PURI","HARTONO ELEKTRONIK 03 - KTI","HARTONO ELEKTRONIK 04 - BDB","HARTONO ELEKTRONIK 05 - MLG","HARTONO ELEKTRONIK 06 - PIN","HITECH CELL 01 - HITECH CELL TASIKMALAYA","HYPERMART 207 PURI INDAH","HYPERMART 210 DAAN MOGOT","HYPERMART 362 SERANG","HYPERMART 460 CITRA RAYA","IBOX 02 - GRAND GALAXY PARK BEKASI","IBOX 04 - METROPOLITAN MALL BEKASI","IBOX 05 - SUMMARECON MALL BEKASI","IBOX 06 - BOTANI SQUARE BOGOR","IBOX 07 - MARGO CITY","IBOX 08 - PESONA SQUARE DEPOK","IBOX 09 - FLAGSHIP CENTRAL PARK","IBOX 10 - ITC ROXY","IBOX 102 - IBOX BULUSARAUNG","IBOX 11 - MALL CIPUTRA JAKARTA","IBOX 110 - IBOX PLAZA ASIA SUMEDANG","IBOX 112 - IBOX JOGJA JAKAL","IBOX 114 - IBOX SOEKARNO HATTA SUHAT MALANG","IBOX 115 - IBOX QUEEN CITY SEMARANG","IBOX 116 - IBOX PADJAJAN BOGOR","IBOX 118 - IBOX PARAGON SEMARANG","IBOX 119 - IBOX GIANYAR BALI","IBOX 12 - ST MORITZ","IBOX 122 - IBOX SUDIRMAN PEKANBARU","IBOX 123 - IBOX PARIS VAN JAVA BANDUNG","IBOX 124 - IBOX CITY PLAZA GARUT","IBOX 126 - IBOX CITIMALL GARUT","IBOX 127 - IBOX SOLO PARAGON MALL","IBOX 13 - ATRIUM","IBOX 131 - IBOX CIPINANG INDAH","IBOX 132 - IBOX SKA MALL PEKANBARU","IBOX 133 - IBOX CIBINONG CITY MALL","IBOX 134 - IBOX BIGMALL SAMARINDA","IBOX 136 - IBOX KLATEN TOWN SQUARE","IBOX 137 - IBOX SAMARINDA CENTRAL PLAZA","IBOX 139 - IBOX SUDIRMAN BALIKPAPAN","IBOX 142 - IBOX SUMMARECON MALL BANDUNG","IBOX 143 - IBOX DUTAMALL BANJARMASIN","IBOX 145 - IBOX IMAM BONJOL BALI","IBOX 146 - IBOX PANAKKUKANG BOULEVARD MAKASSAR","IBOX 147 - IBOX RINGROAD MEDAN","IBOX 149 - IBOX JUANDA SAMARINDA","IBOX 150 - IBOX GATOT SUBROTO BANJARMASIN","IBOX 153 - IBOX DEWATA UDAYANA","IBOX 154 - IBOX BINTARO JAYA XCHANGE MALL 2","IBOX 155 - IBOX PALEMBANG TRADE CENTER","IBOX 156 - IBOX OPI PALEMBANG","IBOX 157 - IBOX SUNRISE MALL MOJOKERTO","IBOX 159 - IBOX GRAGE MAL CIREBON","IBOX 160 - IBOX PATTIMURA PADANG","IBOX 162 - IBOX KEDIRI TOWN SQUARE","IBOX 163 - IBOX PARAMOUNT BSD","IBOX 165 - PAKUWON CITY MALL","IBOX 166 - MANYAR KERTOARJO","IBOX 169 - IBOX GRAND BATAM MALL","IBOX 170 - IBOX ONE MALL BATAM","IBOX 171 - IBOX MEGAMALL BATAM","IBOX 172 - IBOX LIPPO PLAZA KENDARI","IBOX 173 - IBOX QMALL BANJARBARU","IBOX 175 - IBOX PANCA USAHA MATARAM","IBOX 176 - IBOX SUDIRMAN PALEMBANG","IBOX 178 - ROYAL PLAZA SURABAYA","IBOX 179 - SLAMET RIYADI SURAKARTA","IBOX 180 - IBOX LIPPO PLAZA KUPANG","IBOX 182 - CITIMALL GORONTALO","IBOX 183 - IBOX AHMAD YANI SERANG","IBOX 185 - STREET CONDET","IBOX 188 - IBOX JEND SUDIRMAN SUKABUMI","IBOX 19 - FLAGSHIP SENAYAN CITY","IBOX 190 - IBOX GATSU MEDAN","IBOX 194 - IBOX DAYS MANADO TOWN SQUARE","IBOX 197 - IBOX EXHIBITION JAKARTA FAIR KEMAYORAN 2025","IBOX 198 - IBOX EXHIBITION IBOXING WEEK MALL RATU INDAH MAKASSAR","IBOX 199 - IBOX SAWAHAN PADANG","IBOX 20 - GANDARIA CITY","IBOX 200 - IBOX RAJAWALI PALEMBANG","IBOX 202 - IBOX MONGINSIDI PALU","IBOX 203 - IBOX MARTADINATA PURWAKARTA","IBOX 205 - IBOX SIPIN JAMBI","IBOX 206 - IBOX ANNIVERSARY MALL KOTA KASABLANKA","IBOX 211 - IBOX PAMULANG","IBOX 22 - MALL OF AMBASSADOR II","IBOX 23 - KOTA KASABLANKA","IBOX 230 - IBOX EXHIBITION IBOX DAYS LIVING WORLD PEKANBARU","IBOX 26 - MAL ARTHA GADING","IBOX 29 - MALL KELAPA GADING","IBOX 33 - CILEGON CENTRE","IBOX 34 - FLAGSHIP SUMMARECON MALL SERPONG","IBOX 35 - TANGERANG CITY MALL","IBOX 36 - BINTARO PLAZA","IBOX 37 - CIPUTRA CITRARAYA TANGERANG","IBOX 40 - THE PARK SAWANGAN","IBOX 41 - PLAZA MEDAN FAIR","IBOX 42 - DELIPARK MEDAN","IBOX 43 - MANHATTAN TIMES SQUARE","IBOX 45 - LIVING WORLD PEKANBARU","IBOX 48 - PALEMBANG ICON","IBOX 49 - PALEMBANG SQUARE","IBOX 50 - MALL JAMBI TOWN SQUARE","IBOX 51 - THE PARK MALL SOLO","IBOX 52 - AMBARUKMO PLAZA YOGYAKARTA","IBOX 53 - HARTONO YOGYAKARTA","IBOX 54 - LIPPO PLAZA YOGYAKARTA II","IBOX 55 - JOGJA CITY MALL","IBOX 56 - PENTACITY","IBOX 57 - DP MALL SEMARANG","IBOX 58 - CIPUTRA SEMARANG","IBOX 59 - RITA MALL PURWOKERTO","IBOX 60 - GAIA BUMI RAYA PONTIANAK","IBOX 61 - RESINDA KARAWANG","IBOX 62 - BANDUNG ELECTRONIC CENTER 1","IBOX 63 - BANDUNG ELECTRONIC CENTER","IBOX 64 - BANDUNG INDAH PLAZA","IBOX 65 - FESTIVAL CITYLINK BANDUNG","IBOX 66 - DAGO BANDUNG","IBOX 68 - PLAZA ASIA TASIKMALAYA","IBOX 69 - CIREBON","IBOX 70 - MANADO TOWN SQUARE","IBOX 71 - MEGAMALL MANADO","IBOX 74 - PLAZA MARINA 1 SURABAYA","IBOX 76 - WTC ( WORLD TRADE CENTER )","IBOX 77 - MALL OLYMPICE GARDEN","IBOX 78 - TRANS STUDIO MALL BALI","IBOX 79 - EPICENTRUM LOMBOK","IBOX 80 - TEUKU UMAR BALI","IBOX 81 - LIPPO MALL KUTA (KUTA ICON) BALI","IBOX 83 - IBOX ARMADA TOWN SQUARE","IBOX 84 - IBOX LIPPO PLAZA MALL SIDOARJO","IBOX 86 - IBOX GATOT SUBROTO BALI","IBOX 88 - IBOX THE PARK MALL SEMARANG","IBOX 90 - IBOX LIVING WORLD DENPASAR","IBOX 91 - IBOX ICON MALL GRESIK","IBOX 93 - IBOX CIBUBUR JUNCTION","IBOX 94 - IBOX METROPOLITAN MALL CILEUNGSI","IBOX 97 - IBOX MALL RATU INDAH MAKASSAR","IBOX 99 - IBOX KARAWANG CENTRAL PLAZA","IBOX 105 - IBOX LIPPO PLAZA EKALOKASARI","IPHONE TASIK 01 - IPHONE TASIK","IUSEDPHONE LIKE NEW 001 - BALI","IUSEDPHONE NEW 002 - BALI","JAKARTA ELECTRONIC 001 - SUDIRMAN KUPANG","JAKARTA ELECTRONIC 004 - TIMOR RAYA","JALAN UNTUK KEMENANGAN 03 - ATLANTIS SMARTPHONE MATARAM GAJAH MADA","JAYAWIJAYA AUDIO 001 - BALI","JOY PHONE 001 - BATUBULAN","JURAGAN STORE BALI 02 - LIKE NEW","JURAGAN STORE MANDIRI 001 - JURAGAN MALL STORE AYANI BANJARBARU KM 36","JURAGAN STORE MANDIRI 002 - JURAGAN STORE AYANI BANJARBARU KM 35","JURAGAN STORE MANDIRI 006 - JURAGAN STORE BANJARMASIN","JURAGAN STORE MANDIRI 008 - JURAGAN STORE VETERAN","KARYA RUANG 02 - FURNITURE ASIA PLAZA","KAWAN LAMA INFORMA 004 MANADO TOWN SQUARE","KAWAN LAMA INFORMA 027 KENDARI","KAWAN LAMA INFORMA 032 LP PERINTIS MAKASAR","KAWAN LAMA INFORMA 044 CIBINONG","KAWAN LAMA INFORMA 065 JUANDA MEDAN","KAWAN LAMA INFORMA 066 LW PEKAN BARU","KAWAN LAMA INFORMA 070 LP PETTARANI MKS","KAWAN LAMA INFORMA 083 LP BALIKPAPAN","KAWAN LAMA INFORMA 087 PANAKKUKANG MAKASAR","KAWAN LAMA INFORMA 089 DAMAR PADANG","KAWAN LAMA INFORMA 091 KARAWACI TGR","KAWAN LAMA INFORMA 094 IBCC BANDUNG","KAWAN LAMA INFORMA 101 TEKNOMART KRWNG","KAWAN LAMA INFORMA 103 GORONTALO","KAWAN LAMA INFORMA 106 LATANETE MAKASAR","KAWAN LAMA INFORMA 112 CITRA RAYA TGR","KAWAN LAMA INFORMA 114 PTC PALEMBANG","KAWAN LAMA INFORMA 117 - CITIMALL GARUT","KAWAN LAMA INFORMA 208 - LP BANJARMASIN","KAWAN LAMA INFORMA 220 - INFORMA TASIKMALAYA","KAWAN LAMA INFORMA ELEKTRONIK 02 - IBCC BDG","KAWAN LAMA INFORMA ELEKTRONIK 108 - INFORMA ELEKTRONIK TASIKMALAYA","KAWAN LAMA INFORMA ELEKTRONIK 18 - CIBINONG BGR","KAWAN LAMA INFORMA ELEKTRONIK 23 - LP PETTARANI MKS","KAWAN LAMA INFORMA ELEKTRONIK 25 - TKM KARAWANG","KAWAN LAMA INFORMA ELEKTRONIK 29 - LP CIREBON","KAWAN LAMA INFORMA ELEKTRONIK 34 - LW PEKANBARU","KAWAN LAMA INFORMA ELEKTRONIK 42 - PTC PALEMBANG","KAWAN LAMA INFORMA ELEKTRONIK 84 HCIR IE PANAKKUKANG SQUARE","KAWAN LAMA INFORMA ELEKTRONIK 86 - CITIMALL GARUT","KAWAN LAMA INFORMA ELEKTRONIK 96 - IE LP PALEMBANG","KAWAN LAMA SELMA 07 - BG JUNCTION SURABAYA","KAWAN LAMA SELMA 11 - CIREBON SUPERBLOCK","KAWAN LAMA SELMA 24 - KINGS","KAWAN LAMA SELMA 31 - MEGA MALL MANADO","KAWAN LAMA SELMA 49 - THE PARK KENDARI","KAWAN LAMA SELMA 51 - PALEMBANG SQUARE","KAWAN LAMA SELMA 53 - CITIMALL DUMAI","K FITNESS 02 - SEMARANG","KHARISMA KOMPUTER INDONESIA 001 - KUPANG","LAVITA JAYA MANDIRI 001 - MAKASSAR","LOG IN MEGASTORE 01 - ABC","LOG IN MEGASTORE 09 - CINUNUK","LOTTE 01- GANDARIA CITY MALL","LOTTE 07 - GREEN PRAMUKA","LOTTE GROSIR 18 - BOGOR","LUCKY PERDANA 01 - LUCKY CIRACAS 7","MANADO MITRA BERSAMA 001 - SAMSUNG STORE MANTOS 3","MANADO MITRA BERSAMA 002 - SAMSUNG STORE MANTOS 1","MANADO MITRA BERSAMA 003 - M STORE MANTOS 3","MAX-INDO 001 - PADANG","DIGI STORE 02 - DIGI STORE MALL MARI","DIGI STORE 12 - HUAWEI MALL PANAKKUKANG","DIGI STORE O4 - DIGI STORE MALL PANAKUKKANG","ME GALLERY 01 - ME GALLERY TSM MAKASSAR","ME GALLERY 03 - ME GALLERY MARI","ME GALLERY 06 - ME GALLERY MALL PANAKKUKANG MAKASSAR","ME GALLERY 07 - ME GALLERY NIPAH MALL MAKASSAR","ME GALLERY 08 - ME GALLERY PETTARANI MAKASSAR","MENARA GRUP 001 - MENARA COMPUTER & GADGET","MII URBAN REPUBLIC 015 - URBAN REPUBLIC TEUKU UMAR BALI","MII URBAN REPUBLIC 016 - URBAN REPUBLIC LIVING WORLD DENPASAR","MII URBAN REPUBLIC 034 - URBAN REPUBLIC CIBINONG CITY MALL","MII URBAN REPUBLIC 035 - URBAN REPUBLIC GANDARIA CITY","MII URBAN REPUBLIC 046 - URBAN REPUBLIC SUMMARECON MALL SERPONG","MII URBAN REPUBLIC 054 - URBAN REPUBLIC DUTA MALL BANJARMASIN","MITRA JAYA PERKASA 001 - STAR KITCHEN PALU","MHI 016 - CIKARANG","MHI 020 - CIBINONG CITY MALL","MHI 031 - TANGCITY 2","NAGA MAS GROUP 01 - NAGA MAS CELLULER PUSAT","NASA 130 - SES MALL PANAKKUKANG","NEW STORE TANGCITY 01 - TANGCITY MALL","ORISKIN 46 - LIVING WORLD PEKANBARU","ORISKIN 51 - TANG CITY MALL","ORISKIN 54 - MALL CIPUTRA SERAYA PEKANBARU","ORISKIN 66 - TSM BALI","PIXEL 01 - ELECTRO SMART KARAWANG","PLANET GADGET 24 - KUPANG","PLANET GADGET 01 - SES TEUKU UMAR 06","PLANET GADGET 02 - SEP TEUKU UMAR 84","PLANET GADGET 03 - HAND PHONE SHOP","PLANET GADGET 05 - TABANAN","PLANET GADGET 07 - GATSU TENGAH","PLANET GADGET 08 - GATSU BARAT","PLANET GADGET 15 - PONDOK BAMBU","PLANET GADGET 25 - BATUBULAN","SARI BUNGA 001 - BADILAN AYANI","SARI BUNGA 002 - BADILAN SERIRIT","SEHATI GROUP 03 - MEGASTORE","SEHATI GROUP 04 - SEHATI PREMIUM STORE 02","SEMERU 002 - SEMERU SARAPPO MAKASAR","SINAR GUNTUR 01 - TOKO SINAR GUNTUR GARUT","SJS PLAZA PADANG 01 - SJS PLAZA PADANG","TIGA PUTRA 01 - KAWI","TOKO ALPINE 01 - TOKO ALPINE PERINTIS MAKASAR","TOPSELL MOJOAGUNG 003 - JOMBANG","UFO 18 - UFO COKROAMINOTO","UFO 19 - UFO TEUKU UMAR","WILLFITNESS 05 - CEMPAKA PUTIH","WILLFITNESS 06 - GROGOL","WILLFITNESS 11 - KOSAMBI","WILLFITNESS 14 - TEGALSARI SURABAYA","WILLFITNESS 16 - DEPOK","WILLFITNESS 17 - BALI GATSU BARAT","WILLFITNESS 18 - KARAWACI","WILLFITNESS 19 - BANDUNG KOPO","WILLFITNESS 20 - GUBENG SURABAYA","WILLFITNESS 21 - BOGOR UTARA","WILLFITNESS 22 - IMAM BONJOL BALI","YOGYA 07 - GRIYA GRAND CINUNUK","YOGYA 19 - YOGYA TASIK HZ","YOGYA 21 - GRAND YOGYA KEPATIHAN","YOGYA 24 - GRIYA GRAND MAJALAYA","YOGYA 25 - GRIYA CICALENGKA","YOGYA 26 - GRIYA PLAZA SUMEDANG","ZOA INTERSTELLAR GROUP 001 - UP GADGET PONTIANAK"
];

var OFFLINE_MERCHANT_AVERAGE_RISK = [
  "8 J STORE 01 - DENPASAR","ABSOLUTEFIT MITRA INDONESIA 004 - ABSOLUTEFIT KEBAYORAN LAMA","ADVANCE 100 LIVING WORLD PEKANBARU","ADVANCE 132 - MITRA10 RAJABASA","RKI06 - MAJU JAYA COMPUTER KARAWACI J1 NO.3-3A","AIO STORE 01 - AIO STORE TASIKMALAYA","ALYOSHA 002 - JOGJATRONIK","ANDREAN CELL 001 - NEW WTC MALL LT. 1","APPEL HOUSE 02 - APPEL HOUSE WATES","ATLANTA 06 - HOS COKROAMINOTO YOGYA","ATRIA 11 - ATRIA GATSU BALI","BALI SATU COMPUTER 001 - BLESSING COMPUTER","BEC BALI 01 - TEUKU UMAR","BERKAH BERSAMA TARA LIKE NEW 06 - MALANG","BERKAH BERSAMA TARA NEW 11 - DARMO PERMAI SURABAYA","BUCCHERI 104 - PALU GALARA MALL","MITRA10 002 - SOLO BARU","MITRA10 029 - JENGGOLO SIDOARJO","MITRA10 030 - KEBONSARI MALANG","CELULLAR WORLD 19 - KUPANG","CITITEL 01 CIKARANG","COURTS 101 - KOTA HARAPAN INDAH","DEVSTORE 001 - LIKE NEW GATSU","DIANA EVA FURNITURE 03 - CIBUBUR","DIGIMAP 12 - DIGIMAP AEON MALL SENTUL","DIGIMAP 49 - DIGIMAP THE PARK KENDARI","DIGIMAP 53 - DIGIMAP PALEMBANG INDAH MALL","DIGIMAP 63 - DIGIMAP JAVA SUPERMALL SEMARANG","DIGIMAP 76 - DIGIMAP LIPPO PLAZA MANADO","DIGIMAP 77 - DIGIMAP CITY PLAZA JATINEGARA","DIGIMAP 78 - DIGIMAP MAL CIJANTUNG","DIGIPLUS 05 - DIGIPLUS GANDARIA CITY","DIGIPLUS 15 - DIGIPLUS PAKUWON MALL YOGYAKARTA","DIGIPLUS 26 - DIGIPLUS PLAZA ATRIUM SENEN","DIGIPLUS 29 - DIGIPLUS SUMMARECON BANDUNG","DIGIPLUS 32 - DIGIPLUS PLAZA PARAHYANGAN BANDUNG","DIGIPLUS 35 - DIGIPLUS POPUP SUNRISE MALL MOJOKERTO","DIGIPLUS 67 - DIGIPLUS THE PARK PEJATEN","DIGIPLUS 74 - DIGIPLUS PALEMBANG TC","DUBAI SMARTPHONE 01 - SAWAHAN","ELECTRONIC CITY 02 - MALL ARTHA GADING","ELECTRONIC CITY 05 - KARAWACI","ELECTRONIC CITY 10 - BEKASI METALL","ELECTRONIC CITY 19 - RUKO PEMUDA","ELECTRONIC CITY 23 - RUKO JABABEKA","ELECTRONIC CITY 34 - UJUNG MENTENG","ELECTRONIC CITY 45 - PANAKUKANG","ELECTRONIC CITY 52 - JATINANGOR","ELECTRONIC CITY 54 - CIBINONG CITY MALL","ELECTRONIC CITY 77 - THE PARK KENDARI","ELS.ID 004 - SEMARANG","ERABLUE 04 - ERABLUE ELECTRONICS RADEN SALEH","ERABLUE 05 - ERABLUE ELECTRONICS SILIWANGI","ERABLUE 101 - ERABLUE ELECTRONICS BATUJAJAR TIMUR","ERABLUE 111 - ERABLUE ELECTRONICS RAYA CICALENGKA","ERABLUE 16 - ERABLUE ELECTRONICS LEGOK","ERABLUE 17 - ERABLUE ELECTRONICS MERUYA SELATAN","ERABLUE 19 - ERABLUE ELECTRONICS MUSTIKA JAYA","ERABLUE 24 - ERABLUE ELECTRONICS MOHAMAD TOHA BOGOR","ERABLUE 25 - ERABLUE ELECTRONICS MOH TOHA TANGERANG","ERABLUE 26 - ERABLUE ELECTRONICS BANTAR GERBANG SATU","ERABLUE 27 - ERABLUE ELECTRONICS PONDOK PETIR","ERABLUE 32 - ERABLUE ELECTRONICS CIKUPA PEUSAR","ERABLUE 34 - ERABLUE ELECTRONICS BOSIH RAYA","ERABLUE 35 - ERABLUE ELECTRONICS PAHLAWAN","ERABLUE 36 - ERABLUE ELECTRONICS CISOKA TIGARAKSA","ERABLUE 37 - ERABLUE ELECTRONICS KEADILAN RAYA","ERABLUE 39 - ERABLUE ELECTRONICS JATIWARINGIN","ERABLUE 49 - ERABLUE ELECTRONICS CIKARANG","ERABLUE 55 - ERABLUE ELECTRONICS KANO RAYA","ERABLUE 58 - ERABLUE ELECTRONICS RAYA LEGOK KARAWACI","ERABLUE 60 - ERABLUE ELECTRONICS WIBAWA MUKTI","ERABLUE 61 - ERABLUE ELECTRONICS PLUMPANG SEMPER","ERABLUE 67 - ERABLUE ELECTRONICS KH. AGUS SALIM","ERABLUE 70 - ERABLUE ELECTRONICS MAULANA HASANUDIN","ERABLUE 73 - ERABLUE ELECTRONICS RAYA HANKAM","ERABLUE 80 - ERABLUE ELECTRONICS RAYA KRESEK SUKAMULYA","ERABLUE 85 - ERABLUE ELECTRONICS PRAMUKA","ERABLUE 87 - ERABLUE ELECTRONICS SUKATANI","ERABLUE 90 - ERABLUE ELECTRONICS RAYA MAUK JATIWARINGIN","EAR 06 - MEGASTORE CIBINONG CITY MALL","EAR 1001 - ERAFONE A YANI MEGAMALL","EAR 104 - ERAFONE MEGASTORE JBK CIKARANG","EAR 15 ERAFONE SUPERMAL KARAWACI","EAR 255 - ERAFONE PONDOK LABU","EAR 322 - ERAFONE JOGYATRONIK MALL","EAR 357 - ERAFONE MEGASTORE 2 TEUKU UMAR","EAR 376 - ERAFONE RUKO DONGKELAN","EAR 38 MEGASTORE SEMPER","EAR 433 - RUKO HOS COKROAMINOTO CIAMIS","EAR 441 - ERAFONE MALL AMBASADOR","EAR 518 - ERAFONE MEGASTORE RUKO TEUKU UMAR BARAT","EAR 540 - ERAFONE RUKO KAPAS KRAMPUNG SURABAYA","EAR 541 - ERAFONE MASPION SQUARE","EAR 602 - ERAFONE LIVING WORLD DENPASAR","EAR 64 - ERAFONE SUMARECON MALL BEKASI","EAR 666 - ERAFONE GRAND MALL MAROS","EAR 671 - ERAFONE MALL RATU INDAH","EAR 674 - ERAFONE MEGASTORE DAENG TATA M","EAR 704 - ERAFONE RUKO ALAUDDIN MAKASSAR","EAR 726 - ERAFONE RUKO RENGASDENGKLOK","EAR 736 - ERAFONE & MORE AROEPALA","EAR 745 - ERAFONE VETERAN","EAR 767 - ERAFONE 2.5 TRANS STUDIO MAKASSAR","EAR 780 - ERAFONE MB HASANUDDIN GOWA","EAR 783 - ERAFONE MEGASTORE BATUA MAKASSAR","EAR 805 - ERAFONE RUKO CIMANUK GARUT","EAR 814 - ERAFONE AND MORE SUDIRMAN BANTUL","EAR 825 - ERAFONE PAAL DUA MANADO","EAR 828 - ERAFONE SKA MALL","EAR 829 - ERAFONE MEGASTORE RUKO PANAM PEKANBARU","EAR 83 - MEGASTORE CILEUNGSI","EAR 86 - ERAFONE DAAN MOGOT MALL","EAR 902 - ERAFONE PALEMBANG TRADE CENTER","EAR 940 - ERAFONE TOMOHON","EAR 941 - ERAFONE MEGASTORE GIRIAN BITUNG","EAR 98 - ERAFONE MALL BUARAN","FITHUB 119 - KUTA","FITHUB 86 - ULUWATU","FITHUB 91 - DIENG MALANG","FITHUB 92 - YASMIN BOGOR","FITX GYM 004 - FATMAWATI","GAN 04 - HELLO UPTOWN MALL","GAN 08 - HELLO DAAN MOGOT","GAN 12 - HELLO JAMBU DUA","GAN 13 - HELLO GREEN PRAMUKA","GAN 16 - HELLO KALIBATA CITY","GAN 27 - HELLO TUPAREV CIREBON","GAYATRI 05 - PUTRA JAYA LAPTOP TEUKU UMAR","GAYATRI 11 - GAYATRI GLOBAL TECH COMPUTER TABANAN","GS 001 - PLATINUM STORE","GRAMEDIA 117 KARAWACI","GTN 100 - TUKAR TAMBAH SUPERMALL KARAWACI","GTN 135 - BLIBLI STORE CIBINONG CITY MALL 2","GTN 174 - BLIBLI STORE SKA MALL PEKANBARU","GTN 194 - BLIBLI STORE BLUE MEGAMALL MANADO","GTN 203 - BLIBLI STORE BLUE PALEMBANG SQUARE","GTN 236 - BLIBLI STORE BLUE KALIBATA CITY","GTN 282 - BLIBLI STORE JAMBU DUA","HARTONO ELEKTRONIK 02 - BGJ","HARTONO ELEKTRONIK 08 - BANDUNG","HDSHOP 001 - PADANG","IBOX 05 - SUMMARECON MALL BEKASI","IBOX 09 - FLAGSHIP CENTRAL PARK","IBOX 10 - ITC ROXY","IBOX 102 - IBOX BULUSARAUNG","IBOX 114 - IBOX SOEKARNO HATTA SUHAT MALANG","IBOX 115 - IBOX QUEEN CITY SEMARANG","IBOX 12 - ST MORITZ","IBOX 124 - IBOX CITY PLAZA GARUT","IBOX 139 - IBOX SUDIRMAN BALIKPAPAN","IBOX 145 - IBOX IMAM BONJOL BALI","IBOX 150 - IBOX GATOT SUBROTO BANJARMASIN","IBOX 155 - IBOX PALEMBANG TRADE CENTER","IBOX 157 - IBOX SUNRISE MALL MOJOKERTO","IBOX 162 - IBOX KEDIRI TOWN SQUARE","IBOX 163 - IBOX PARAMOUNT BSD","IBOX 175 - IBOX PANCA USAHA MATARAM","IBOX 26 - MAL ARTHA GADING","IBOX 36 - BINTARO PLAZA","IBOX 52 - AMBARUKMO PLAZA YOGYAKARTA","IBOX 58 - CIPUTRA SEMARANG","IBOX 63 - BANDUNG ELECTRONIC CENTER","IBOX 64 - BANDUNG INDAH PLAZA","IBOX 70 - MANADO TOWN SQUARE","IBOX 71 - MEGAMALL MANADO","IBOX 76 - WTC ( WORLD TRADE CENTER )","IBOX 94 - IBOX METROPOLITAN MALL CILEUNGSI","IBOX 105 - IBOX LIPPO PLAZA EKALOKASARI","INDOCELL 002 - NEW SESETAN","INDOCELL 003 - LIKE NEW TEUKU UMAR","INDOCELL 004 - NEW TEUKU UMAR","ISTANA IT 001 - GATSU","JEFINDO TEKNOLOGI 01 - PUSAT","JET FITNESS 01 KARAWACI","KANA MANADO 001 - KANA CELL MEGAMAS","KAWAN LAMA INFORMA 002 NAGOYA BATAM","KAWAN LAMA INFORMA 040 HERTASNING MAKASAR","KAWAN LAMA INFORMA 076 A.YANI BEKASI","KAWAN LAMA INFORMA 093 LP TASIKMALAYA","KAWAN LAMA INFORMA 207 - LP PALEMBANG","KAWAN LAMA INFORMA 216 - INFORMA LP PALU","KAWAN LAMA INFORMA ELEKTRONIK 100 - LW GRAND WISATA BEKASI","KAWAN LAMA INFORMA ELEKTRONIK 24 - LP TASIKMALAYA","KAWAN LAMA SELMA 58 - BASKO CITIMALL","KING JAYA SELALU 001 - KING'S FURNITURE JAWI","LOTTE GROSIR 16- CIKARANG","MATANI TIGA BERSAUDARA 001 - MATANI ELCOM MANADO","MAXI STORE 02 - MAXI STORE ALAUDDIN","METEOR CELL 01 - GAJAYANA PUSAT","MII URBAN REPUBLIC 001 - URBAN REPUBLIC BINTARO JAYA EXCHANGE 2","MII URBAN REPUBLIC 006 - URBAN REPUBLIC MALL PANAKKUKANG MAKASSAR","MII URBAN REPUBLIC 009 - URBAN REPUBLIC TSM MAKASSAR","MII URBAN REPUBLIC 010 - URBAN REPUBLIC PAKUWON MALL YOGYAKARTA","MII URBAN REPUBLIC 052 - URBAN REPUBLIC BIG MALL SAMARINDA","MHI 022 - SMS DEPOK","MHI 038 - BEC 2","MHI 071 - CIBINONG CITY MALL 2","MHI 076 - SES SOLO KRATONAN","MITRA NORIA ABADI 005 - IOS STORE AYANI MEGAMALL","MUGEN 01 - MUGEN COMPUTER PETTARANI","NASA 160 - SPS THE PARK KENDARI","NUANSA SUPERSTORE 04 - MATOS SAMARINDA","ORISKIN 06 - BINTARO JAYA","ORISKIN 07 - ALAM SUTERA","ORISKIN 08 - KARAWACI","ORISKIN 16 - DENPASAR BALI","ORISKIN 18 - DIY","ORISKIN 19 - SEMARANG","ORISKIN 27 - MALANG","ORISKIN 61 - MALL CITRA RAYA","PERDANA KOMUNIKASI 002 - STARLIGHT STORE KUANINO KUPANG","PERFECT HEALTH 05 - AYANI PONTIANAK","PLANET GADGET 18 - KUTA","PLANET GADGET 23 - MOJOKERTO","PURA PURA PONSEL 001 - LIKE NEW","PURA PURA PONSEL 002 - NEW","PURA PURA PONSEL 003 - DENPASAR BARAT","PUTRA NIAGA LESTARI 01 - PONDOK ELEKTRONIK BANJARMASIN","ROSE CELLULAR 001 - TUPAREV","RUMAH GADGET 002 - NEW","RUPARUPA","SARI BUNGA 004 - BADILAN NGURAH RAI","SBC BERKAH BERSAMA 001 - SBC NGORO","SEHATI GROUP 02 - MODERN STORE GARUT","SEMERU 001 - SEMERU PERINTIS MAKASAR","SMART PHONE SHOP 04 - SMART GADGET BCP","SQUARE COMPUTER 001 - S PARMAN","SUKSES SEHAT SEJAHTERA SELAMANYA 001 - FIT SOCIETY","SUMBAR SMARTPHONE 09 - PURWAKARTA","TOKO ANUGERAH GADGET AROEPPALA ","TOPSELL 014 - BERKAH ELEKTRONIK MOJOAGUNG","TOPSELL PLAZA 007 - SIDOARJO","UFO 01 - UFO KERTAJAYA","VIVA BERRY TANGCITY 02 - APPLE SOLUTION","WILLFITNESS 13 - KALIMALANG","YAMADA BEST 09 - YAMADA BEST AEON DELTA MAS CIKARANG","YULI SUMBER LARIS 02 - PETTARANI"
];

var OFFLINE_MERCHANT_MODERATE_RISK = [
  "ADVANCE 134 - LAMPUNG CITY MALL","ADVANCE 195 FARMERS PLAZA BALIKPAPAN","RGC02 - AGRES.ID PGC 3A NO. 562C","ALASKA MANDIRI CEMERLANG 02 - ALASKA MAKASSAR IT GADGET","AMERICAN PILLO 003 - MATARAM","ANDALAS 01 - SUPERSTORE SOEKARNO HATTA","ANDALAS 06 - EXP STORE SUDIRMAN","ANDALAS 07 - PENTACITY","ATLANTA 08 - MAJAPAHIT SEMARANG","B STORE 01 - CONDET JAKARTA","MITRA10 003 - SEMARANG","COURTS 102 - MEGA BEKASI HYPERMALL","CAHAYA BERKAT 02 - DIAMOND SESETAN","DARGAN CELL 01 - SOEKARNO HATTA","DIGIMAP 14 - DIGIMAP AEON TANJUNG BARAT","DIGIMAP 38 - DIGIMAP GALAXY MALL","DIGIPLUS 38 - DIGIPLUS KARAWANG CENTRAL PLAZA","DIGIPLUS 68 - DIGIPLUS LIPPO PLAZA KENDARI","DIGIPLUS 74 - DIGIPLUS PALEMBANG TC","DIGIPLUS 75 - DIGIPLUS MEGA MALL BTM","ELIY'S FURNITURE 01 - TANGCITY MALL","ELS.ID 001 - YOGYAKARTA","ERABLUE 01 - ERABLUE ELECTRONICS TOLE ISKANDAR","ERABLUE 08 - ERABLUE ELECTRONICS DEWI SARTIKA","ERABLUE 09 - ERABLUE ELECTRONICS RADEN FATAH","ERABLUE 120 - ERABLUE ELECTRONICS TUNTUNG GUNUNG","ERABLUE 121 - ERABLUE ELECTRONICS RAWA BELONG","ERABLUE 14 - ERABLUE ELECTRONICS SETIA MEKAR","ERABLUE 15 - ERABLUE ELECTRONICS BINTARA","ERABLUE 22 - ERABLUE ELECTRONICS PERJUANGAN TAMAN","ERABLUE 23 - ERABLUE ELECTRONICS MT HARYONO","ERABLUE 31 - ERABLUE ELECTRONICS PATRIOT","ERABLUE 40 - ERABLUE ELECTRONICS SYEH MUBAROK","ERABLUE 44 - ERABLUE ELECTRONICS KEBALEN","ERABLUE 51 - ERABLUE ELECTRONICS CIOMA KRETEG","ERABLUE 53 - ERABLUE ELECTRONICS RE MARTADINATA","ERABLUE 66 - ERABLUE ELECTRONICS LEUWILIANG","ERABLUE 71 - ERABLUE ELECTRONICS RAYA NAROGONG","ERABLUE 72 - ERABLUE ELECTRONICS RENGASDENGKLOK","ERABLUE 74 - ERABLUE ELECTRONICS KAMPUNG MELAYU","ERABLUE 75 - ERABLUE ELECTRONICS PENDIDIKAN","ERABLUE 77 - ERABLUE ELECTRONICS KRONJO","ERABLUE 81 - ERABLUE ELECTRONICS SYEH QURO TELAGASARI","ERABLUE 83 - ERABLUE ELECTRONICS PROKLAMASI","ERABLUE 86 - ERABLUE ELECTRONICS SERANG CIBARUSAH","ERABLUE 88 - ERABLUE ELECTRONICS JL PIK PENGGILINGAN","ERABLUE 95 - ERABLUE ELECTRONICS MANGUNJAYA","ERABLUE 96 - ERABLUE ELECTRONICS PITARA RAYA","EAR 01 - ERAFONE 1 MEGA BEKASI HYPERMALL","EAR 09 - ERAFONE PLAZA PONDOK GEDE","EAR 1095 - ERAFONE AND MORE RUKO ITC ROXY MAS","EAR 18 ERAFONE ITC BSD","EAR 270 - ERAFONE RUKO LEMBANG","EAR 292 - MEGASTORE RUKO A YANI KARAWANG","EAR 294 - ERAFONE RUKO CIPULIR","EAR 323 - ERAFONE GEJAYAN JOGJA","EAR 351 - ERAFONE MEGASTORE RUKO TELOGOSARI SEMARANG","EAR 392 - ERAFONE & MORE RUKO MARGONDA DEPOK","EAR 409 - ERAFONE WTC E - MALL LANTAI 2 SURABAYA","EAR 430 - PLAZA ASIA SUMEDANG","EAR 431 - PLAZA ASIA","EAR 433 - RUKO HOS COKROAMINOTO CIAMIS","EAR 434 - MEGASTORE RUKO TASIKMALAYA","EAR 456 - ERAFONE MAYOR SAFEI SERANG","EAR 532 - ERAFONE MEGASTORE PONDOK BAMBU","EAR 540 - ERAFONE RUKO KAPAS KRAMPUNG SURABAYA","EAR 613 - ERAFONE GRESSMALL","EAR 661 - ERAFONE RUKO CIWIDEY","EAR 677 - ERAFONE RUKO BUMI TAMALANREA PERMAI","EAR 68 - ERAFONE MALL KOTA KASABLANKA","EAR 71 - MEGASTORE KEMANG","EAR 736 - ERAFONE & MORE AROEPALA","EAR 770 - ERAFONE AND MORE USMAN SADAR GRESIK","EAR 779 - ERAFONE & MORE PUCANG ANOM SURABAYA","EAR 822 - ERAFONE MEGASTORE RUKO MANADO","EAR 85 - ERAFONE RUKO BINUS","EAR 945 - ERAFONE RUKO MOJOAGUNG","EAR 949 - ERAFONE AIRLANGGA MOJOSARI","EAR 988 - ERAFONE SEBERANG PADANG","ERA TELEKOMUNIKASI 01 - TOPSELL JOGJATRONIK","GALLERY PHONE 001 - RAPOCINI","GAN 18 - HELLO EASTVARA BSD","GAN 21 - HELLO MALL OF SERANG","GAYATRI 03 - AGUSTIN LAPTOP","GTN 173 - BLIBLI STORE LOTTE SHOPPING AVENUE KUNINGAN","GTN 179 - BLIBLI STORE BEC BANDUNG","GTN 189 - BLIBLI STORE BLUE MALL ARTHA GADING","GTN 191 - BLIBLI STORE BLUE CIREBON SUPER BLOCK","GTN 200 - BLIBLI STORE BLUE WTC SURABAYA","GTN 227 - BLIBLI STORE BLUE GATOT SUBROTO SOLO","GTN 231 - BLIBLI STORE BLUE ITC ROXY MAS","GTN 236 - BLIBLI STORE BLUE KALIBATA CITY","GTN 257 - BLIBLI STORE PLAZA MEDAN FAIR","GTN 264 - BLIBLI STORE BLUE GORONTALO","GTN 277 - BLIBLI STORE CIPUTRA JAKARTA","HDSHOP 001 - PADANG","HYPERMART 320 KARAWACI","IBOX 147 - IBOX RINGROAD MEDAN","IBOX 171 - IBOX MEGAMALL BATAM","IBOX 172 - IBOX LIPPO PLAZA KENDARI","IBOX 176 - IBOX SUDIRMAN PALEMBANG","IBOX 202 - IBOX MONGINSIDI PALU","IBOX 22 - MALL OF AMBASSADOR II","IBOX 48 - PALEMBANG ICON","IBOX 66 - DAGO BANDUNG","IBOX 99 - IBOX KARAWANG CENTRAL PLAZA","JAYA GRAHA ABADI 01 - GRAHA ELEKTRONIK MATARAM MALL","JAYA GRAHA ABADI 02 - GRAHA ELEKTRONIK BRAWIJAYA","JURAGAN STORE MANDIRI 006 - JURAGAN STORE BANJARMASIN","KAWAN LAMA INFORMA ELEKTRONIK 104 - INFORMA ELEKTRONIK BASKO CITIMALL","KAWAN LAMA SELMA 36 - PRABUMULIH","LISTAR PUTRA GORONTALO 001 - S.PARMAN","LOTTE 06 - TAMAN SURYA","MAJU BERSAMA 016 - MAJU HARDWARE KEDIRI","MANADO MITRA BERSAMA 004 - APPLE SHOP MHC","MAXI STORE 01- MAXI STORE PERINTIS","MDP SUPERSTORE 01 - MDP IT SUPERSTORE","MII URBAN REPUBLIC 008 - URBAN REPUBLIC MALL RATU INDAH MAKASSAR","MII URBAN REPUBLIC 024 - URBAN REPUBLIC AEON MALL TANJUNG BARAT","MII URBAN REPUBLIC 039 - URBAN REPUBLIC MARGO CITY DEPOK","MII URBAN REPUBLIC 049 - URBAN REPUBLIC PALEMBANG SQUARE","NASA 118 - SES PLAZA ASIA TASIKMALAYA","NUANSA SUPERSTORE 05 - IMAM BONJOL SAMARINDA","OKE SHOP 53 OKESHOP MAL PANAKUKANG (U82)","ORISKIN 07 - ALAM SUTERA","ORISKIN 38 - SURABAYA","PLANET GADGET 06 - GIANYAR","PLANET GADGET 10 - SIDOARJO","PLANET GADGET 20 - CIREBON","PRIMA COMPUTER 001 - SOLO","RED FITNESS 07 CIBUBUR","RUMAH GADGET 001 - LIKE NEW","SEHATI GROUP 05 - SEHATI SMART SHOP","SPM SUKSES SEJAHTERA 01 - SUPER MURAH PANCA USAHA","STRONGEST FITNESS INDONESIA 001 - BG JUNCTION SURABAYA","SUARA ELEKTRO 001 - PANIKI","SUARA ELEKTRO 006 - TOMOHON","SUMBAR SMARTPHONE 01 - PREMIERE","SURYA PHONE 06 - ABUL HASAN SSP","SYIHAB JAYA UTAMA 001 - SYIHAB STORE AYANI BANJARBARU","TAHAKI 02 - TAHAKI CELL","TAMARA MEUBEL 01 - SRIWIJAYA MATARAM","TOKO ANUGERAH  GADGET GOWA","TOPSELL 009 - KEDIRI","TOPSELL ANGGREK 002 - MOJOKERTO","TOPSELL MOJOSONGO 006 - JOMBANG","TOPSELL PLAZA 004 - JOMBANG","TOPSELL PLOSO 005 - JOMBANG","UFO 06 - UFO BANJARMASIN","UFO 12 - UFO MALANG","UFO 13 - UFO JOMBANG","VINIX INTICOM 01 - ASEAN CELL PANCA USAHA NEW","WIN INDO NUSA 01 - WIN CELLULAR","WIN'S ELEKTRONIK 001 - KENDARI","YOGYA 60 - YOGYA SOREANG"
];

var OFFLINE_MERCHANT_HIGH_RISK = [
  "ATLANTA 04 - KARANGWULAN","ATLANTA 07 - MUNTILAN","BERKAH BERSAMA TARA NEW 14 - KEDIRI","CAHAYA ELEKTRONIK JAYA 01 - MATARAM","DATA BASIS TECHNOLOGY 001 - DATABASE COMPUTER PONTIANAK","DIGIMAP 14 - DIGIMAP AEON TANJUNG BARAT","DIGIMAP 74 - DIGIMAP JATINANGOR TS","DIGIPLUS 10 - DIGIPLUS WTC MALL SURABAYA","DIGIPLUS 102 - DIGIPLUS LOMBOK EPICENTRUM","DIGIPLUS 33 - DIGIPLUS MALL CIPUTRA SEMARANG","DIGIPLUS 93 - DIGIPLUS CITIMALL GORONTALO","EGA JAYA ELEKTRIK 001 - EGAJAYA ELEKTRONIK","ERABLUE 13 - ERABLUE ELECTRONICS SILIWANGI BEKASI","ERABLUE 28 - ERABLUE ELECTRONICS BOJONG SARI LAMA","ERABLUE 46 - ERABLUE ELECTRONICS KALIABANG TENGAH","ERABLUE 50 - ERABLUE ELECTRONICS PONDOK KELAPA","ERABLUE 59 - ERABLUE ELECTRONICS RAYA CIBARUSAH SIMPANG TIGA","ERABLUE 65 - ERABLUE ELECTRONICS PASAR KEMIS","ERABLUE 69 - ERABLUE ELECTRONICS TELAGASARI KOSAMBI","ERABLUE 78 - ERABLUE ELECTRONICS SYEH QURO PALUMBONSARI","ERABLUE 79 - ERABLUE ELECTRONICS LETJEN IBRAHIM ADJIE","ERABLUE 93 - ERABLUE ELECTRONICS SYEH QURO LEMAHABANG","ERABLUE 94 - ERABLUE ELECTRONICS JERUK RAYA","EAR 1036 - ERAFONE THE PARK KENDARI","EAR 1037 - ERAFONE MEGASTORE RUKO MT HARYONO KENDARI","EAR 1042 - ERAFONE & MORE RAWASARI","EAR 1082 - ERAFONE RUKO PLERED PURWAKARTA","EAR 1083 - ERAFONE MEGASTORE RUKO PURWAKARTA","EAR 1084 - ERAFONE RUKO VETERAN PURWAKARTA","EAR 1094 - ERAFONE MEGASTORE RUKO LIMBOTO GORONTALO","EAR 1101 - ERAFONE RUKO KALIJATI SUBANG","EAR 22 MEGASTORE RUKO CIPUTAT","EAR 229 - ERAFONE 1 BANDUNG ELECTRONIC CENTER","EAR 230 - MEGASTORE ISTANA BANDUNG ELECTRONIC CENTER","EAR 231 - ERAFONE 3 BANDUNG ELECTRONIC CENTER","EAR 268 - MEGASTORE TUNJUNGAN PLAZA 3","EAR 31 ERAFONE ARION MALL","EAR 361 - RUKO SUPRATMAN CIPUTAT","EAR 424 - ERAFONE RUKO GARUT","EAR 440 - ERAFONE MEGASTORE TEGALREJO JOGJAKARTA","EAR 481 - ERAFONE MB KRIAN SIDOARJO","EAR 591 - ERAFONE PLAZA SURABAYA","EAR 611 - ERAFONE ICON MALL GRESIK","EAR 635 - ERAFONE & MORE SAWOJAJAR MALANG","EAR 652 - MAYOR ABDURAHMAN","EAR 675 - ERAFONE MEGASTORE RUKO PONGTIKU","EAR 72 - MEGASTORE PONDOK PINANG","EAR 729 - ERAFONE CILAMPENI BANDUNG","EAR 782 - ERAFONE & MORE RAPPOCINI MAKASSAR","EAR 784 - ERAFONE & MORE BULUSARAUNG","EAR 793 - ERAFONE AND MORE MAYJEND SUNGKONO","EAR 824 - ERAFONE 1 MEGA MALL MANADO","EAR 834 - ERAFONE MALL LIVING WORD","EAR 898 - ERAFONE MEGASTORE MATARAM","EAR 90 - ERAFONE AEON TANJUNG BARAT","EAR 933 - ERAFONE AND MORE PLAZA JAMBU 2 BOGOR","EAR 944 - ERAFONE FRANCHISE JOMBANG","EAR39 MEGASTORE MKG","EVAN MEUBEL 01 - EVAN MEUBEL KUPANG","FAMILY DIGITALCOM 001 - FAMILY DIGITALCOM 1","FAMILY DIGITALCOM 002 - REALME BRAND STORE","FITHUB 123 - SANUR","GADGET MART 01 - BJM BELITUNG","GALLERY PHONE 001 - RAPOCINI","GEMILANG JAYA 002 - GEMILANG JAYA IT CENTER","GTN 198 - BLIBLI STORE BLUE SUN PLAZA MEDAN","GTN 257 - BLIBLI STORE PLAZA MEDAN FAIR","GTN 276 - BLIBLI STORE ICON MALL GRESIK","HARAPAN PONSEL 01 - HARAPAN PONSEL PEKANBARU","HARTONO ELEKTRONIK 01 - SDN","IBOX 136 - IBOX KLATEN TOWN SQUARE","IBOX 173 - IBOX QMALL BANJARBARU","IBOX 182 - CITIMALL GORONTALO","IBOX 203 - IBOX MARTADINATA PURWAKARTA","IBOX 56 - PENTACITY","IBOX 61 - RESINDA KARAWANG","JAKARTA ELECTRONIC 002 - AIWA ELECTRONIC KUANINO KUPANG","J-BROS 001 - ARIF RAHMAN HAKIM","KELLY DENZEL ELEKTRONIC 001 - K & D ELEKTRONIK CENTRE PONTIANAK","LISTAR PUTRA GORONTALO 002 - PULUBALA","LOTTE GROSIR 35 - MATARAM","LRI AGUNG CELL 01 - AGUNG CELL PUSAT","MDP SUPERSTORE 02 - MDP PLAZA","MICHAEL HUTAMA PERSADA 001 - MICHAEL HP PANCA USAHA","MII URBAN REPUBLIC 018 - URBAN REPUBLIC LOMBOK EPICENTRUM MALL","MII URBAN REPUBLIC 048 - URBAN REPUBLIC PALEMBANG ICON","MII URBAN REPUBLIC 067 - URBAN REPUBLIC DP MALL SEMARANG","MULTI MEDIA 001 - AHMAD YANI","NEOFIT GYM 03 - SEKARPACE","NUANSA SUPERSTORE 02 - SUTOYO","NUANSA SUPERSTORE 06 - BANJAR BARU MARTAPURA","ORISKIN 21 - POINT SQUARE MEDAN","PERDANA KOMUNIKASI 001 - PLATINUM STORE KUANINO KUPANG","PERDANA KOMUNIKASI 004 - MASTER STORE KUANINO KUPANG","PRIMA INDAH CELL 04 - PRIMA INDAH CELL MAROS","RIVALD GROUP 002 - QIANA PONSEL 3","SARANA MULTI SELULAR 001 - GALERIA ELEKTRONIK KUPANG","SENTRA 002 - SENTRA OPPO L1 R172","SURYA PHONE 02 - AGUS SALIM","SURYA PHONE 04 - BUNGTOMO","SYIHAB JAYA UTAMA 005 - SYIHAB PHONE VETERAN BANJARMASIN","TOKO KAWIJAYA ELEKTRONIK 002 - TOKO KAWIJAYA ELEKTRONIK JOMBANG","TOPSELL 011 - SURABAYA","TOPSELL BHAYANGKARA 001 - MOJOKERTO","UFO 09 - UFO KEDIRI","UFO 17 - UFO SEMARANG","WILLFITNESS 25 - SUNSET ROAD BALI"
];

var OFFLINE_MERCHANT_VERY_HIGH_RISK = [
  "ADVANCE 204 GRAND MALL PALU","ADVANCE 51 MITRA10 JAKABARING","ANDALAS 10 - GUNUNG MALANG SUTOYO","ANEKA JAYA MOBILE 003 - MT HARYONO","ATLANTA 01 - MT HARYONO","ATLANTA 03 - NGESREP","BENGKONG JAYA FURNITURE 001 - BATAM","BERKAT JAYA FURNITURE 001 - BATAM","DH STORE 002 - LIKE NEW WTC LT. 1 SURABAYA","DIGIPLUS 11 - DIGIPLUS PLAZA MARINA SURABAYA","DIGIPLUS 40 - DIGIPLUS LIPPO PLAZA EKALOKASARI","DIGIPLUS 82 - DIGIPLUS BEC","ELECTRONIC CITY 44 - KOTA KASABLANKA","ELECTRONIC CITY 51 - RUKO PURWAKARTA","ERABLUE 10 - ERABLUE ELECTRONICS JATIMULYA","ERABLUE 56 - ERABLUE ELECTRONICS MERCEDES BENZ","ERABLUE 63 - ERABLUE ELECTRONICS TELUK JAMBE","EAR 1092 - ERAFONE AND MORE DAGO BANDUNG","EAR 1101 - ERAFONE RUKO KALIJATI SUBANG","EAR 273 - ERAFONE WORLD TRADE CENTER SURABAYA","EAR 320 - ERAFONE RUKO PERCETAKAN NEGARA","GAN 03 - HELLO KUNINGAN CITY","GAN 26 - HELLO - SAMRATULANGI MANADO","GTN 140 - BLIBLI STORE RESINDA PARK MALL","GTN 274 - BLIBLI STORE PTC PALEMBANG","HACOM 02 - PACUAN KUDA","IBOX 170 - IBOX ONE MALL BATAM","INDOTAMA BANGUNAN MAKMUR 001 - BJP BANGUNAN GORONTALO","MII URBAN REPUBLIC 011 - URBAN REPUBLIC PLAZA AMBARUKMO YOGYA","MII URBAN REPUBLIC 013 - URBAN REPUBLIC PARAGON MALL SEMARANG","NATURAL FURNITURE & ELEKTRONIK 001 - KENDARI","SYIHAB JAYA UTAMA 002 - SYIHAB STORE AYANI MARTAPURA","UFO 03 - UFO SIDOARJO"
];

var OFFLINE_MERCHANT_DOWNGRADE = [
    /* Batam Area Tradi */
    '7340c6ee-f4ce-11ef-89b0-6f17da6671f2', 
    '0305efd6-2af5-11f0-a504-0f84cdbac718',
    '6ee30fd8-a7dd-11ef-952a-271321a27ad0',
    '9ae74d8c-a7df-11ef-8362-a9a1c58f513d',
    'a1417e89-edcc-11ef-a94a-bdb3d6908e86',
    '7098e8c1-d8c9-11ef-910c-c77c400a204f',
    'd10edc06-d8ca-11ef-8606-ed7e73775513',
    '9520d726-a7d3-11ef-9aaa-e7c2241d7a12',
    'c3a2e121-4cd2-11f0-82f5-abbffabe0adb',
    'c78430ac-6cf2-11f0-9374-c5481c8b55be',
    'a7c6b733-8786-11ef-8790-31c1d963305a',
    'a7d0c95e-8786-11ef-8790-672487b3da43',
    '3c8da565-f316-11ee-a3d0-b3c90b9fcd5e',
    'f82ea3d9-a7da-11ef-9660-db33d6836dad',
    'b91b6065-bebd-11ef-8509-97f71879a0d3',
    '77a18d82-bebc-11ef-b86b-c58f92afe434',
    '77a8926b-bebc-11ef-b86b-9b7e4f185a7d',
    'ca00da0a-20b8-11f0-978a-e937b7ea6a32',
    '7277995b-a7be-11ef-9660-0761a28f6aac',
    '7181537f-3154-11f0-a67a-d76dda82f320',
    '04451a11-3ba7-11f0-bb1c-b370556dde94',
    '04606a4a-3ba7-11f0-bb1c-810c04bfbcc3',
    '9910ca92-4ffd-11f0-8401-a744a93cf72e',
    '2c4c136f-f4d1-11ef-89b0-7f2853e3ce74',
    '2c55d778-f4d1-11ef-89b0-ef48034ad58e',
    '73f1a26c-fa39-11ef-b369-156de6cccc68',
    'cc953c4e-a7bb-11ef-952a-9d5b76ae61cf',
    '98df2531-beba-11ef-b86b-6942466dbb46',
    'c4fe0bd3-a7d9-11ef-9660-3fb56e7ec95e',
    'c505fb1c-a7d9-11ef-9660-eb5b1cb66533',
    'b0f6db62-ce53-11ef-9152-77264670183a',
    '7cd70648-f4d6-11ef-9ee3-ef88ce6a7f53',
    '7cdf1ca1-f4d6-11ef-9ee3-931dd7466c56',
    '7ce5854a-f4d6-11ef-9ee3-ef9c87a11a5d',
    'b900f95e-c139-11ef-8509-8be1004a3453',
    '64a240b0-4a96-11f0-9c02-bf551ddb6a6b',
    '64ac79e9-4a96-11f0-9c02-29e1512c6c8e',
    '64b3a5e2-4a96-11f0-9c02-dddfd6d7624b',
    '64c2e834-4a96-11f0-9c02-eba0fa60d9ba',
    'cf2d2655-03b2-11f0-8550-3d74c7634cea',
    'cf3d52fe-03b2-11f0-8550-3b2e6a1e2d24'
];

/*Offline item categorization*/
var OFFLINE_WHITELIST_ITEMS = [ 
    'find n2 flip',
    'find n3 flip',
    'vivo x80',
    'find x5'
];

var TIKET_MERCHANT_ID = 'b4f0dc58-b43e-11ea-ba26-98039b2bc484';
var BLIBLI_MERCHANT_ID = 'fb3d032b-8ad8-11ea-9e4a-3dba9eff3f84';
var EWALLET_MERCHANT_ID = '3be04791-06c6-11ef-b1a6-2d64d067f971';
var CERMATI_DIGITAL_MERCHANT_ID = '301289e7-11ef-11ec-87a2-31f7040ea4a7';

var OFFLINE_WHITELIST_ITEMS_APPLE_EDITIONS = [
    'iphone 12',
    'iphone 13',
    'iphone 14',
    'iphone 15',
    'ip 12',
    'ip 13',
    'ip 14',
    'ip 15',
    'iphone12',
    'iphone13',
    'iphone14',
    'iphone15',
    'apple 12',
    'apple 13',
    'apple 14',
    'apple 15',
    'apple12',
    'apple13',
    'apple14',
    'apple15',
    'ipad',
    'macbook',
    'imac',
    'watch'
];

var OFFLINE_WHITELIST_ITEMS_SAMSUNG_EDITIONS = [
    's21',
    's22',
    's23',
    's24',
    's25',
    's26',
    'z',
    'flip',
    'fold'
];

var sanitizedItemNames = itemNames.replaceAll("_", " ");
var lowerCaseItemNames = sanitizedItemNames.toLowerCase();
var is_current_item_offline_whitelisted_item = false;
var is_va_transaction = false;

for (merchant: VA_MERCHANTS) {
    if (merchantId == merchant) {
        is_va_transaction = true;
        break;
    }
}

var is_offline_merchant_downgrade = false;
var offline_merchant_tag = 'normal'
for (offline_merchant: OFFLINE_MERCHANT_DOWNGRADE) {
    if (merchantId == offline_merchant) {
        is_offline_merchant_downgrade = true;
        offline_merchant_tag = 'downgrade';
        break;
    }
} 

/* Assignment of Offline Merchant Risk Category */
var offline_merchant_risk_category = 'not top merchant';
var offline_merchant_risk_category_group = 'high risk';

var merchantNameLowerCase =  merchantName.toLowerCase();
for (offline_merchant: OFFLINE_MERCHANT_LOW_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'low';
        break;
    }
} 
for (offline_merchant: OFFLINE_MERCHANT_AVERAGE_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'average';
        break;
    }
} 
for (offline_merchant: OFFLINE_MERCHANT_MODERATE_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'moderate';
        break;
    }
} 
for (offline_merchant: OFFLINE_MERCHANT_HIGH_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'high';
        break;
    }
} 
/*Very Low Risk Brand Override*/
var sanitizedParentMerchantName = parentMerchantName.replaceAll(" ", "").toLowerCase();
for (offline_brand: OFFLINE_PARENT_MERCHANT_VERY_LOW_RISK) {
    if (sanitizedParentMerchantName == offline_brand.toLowerCase()) {
        offline_merchant_risk_category = 'very low';
        break;
    }
} 

for (offline_merchant: OFFLINE_MERCHANT_VERY_HIGH_RISK) {
    if (merchantNameLowerCase == offline_merchant.toLowerCase()) {
        offline_merchant_risk_category = 'very high';
        break;
    }
} 


if ((offline_merchant_risk_category == 'very low') || (offline_merchant_risk_category == 'low') || (offline_merchant_risk_category == 'average')) {
    offline_merchant_risk_category_group = 'ok';
}

for (item: OFFLINE_WHITELIST_ITEMS) {
    if (stringUtils.contains(lowerCaseItemNames, item)) {
        is_current_item_offline_whitelisted_item = true;
        break;
    }
}

/* samsung + (s21/s22/s23/flip/fold/z) */
for (samsung_series: OFFLINE_WHITELIST_ITEMS_SAMSUNG_EDITIONS) {
    if(stringUtils.contains(lowerCaseItemNames, 'samsung') 
    && stringUtils.contains(lowerCaseItemNames, samsung_series.toLowerCase())) {
        is_current_item_offline_whitelisted_item = true;
        break;
    }
}

/*Apple + (iphone 12/iphone 13/iphone 14/iphone 15/ipad/macbook/imac/watch)*/
for (apple_series: OFFLINE_WHITELIST_ITEMS_APPLE_EDITIONS) {
    if(stringUtils.contains(lowerCaseItemNames, 'apple') 
    && stringUtils.contains(lowerCaseItemNames, apple_series.toLowerCase())) {
        is_current_item_offline_whitelisted_item = true;
        break;
    }
}

var is_smartphone_transaction = false;
for (itemtypes : itemTypes) {
    if (itemtypes.toLowerCase() == 'smartphone') {
        is_smartphone_transaction = true;
        break;
    }
}

/*Is tradi brand city tier*/
var is_tradi_brand_city_tier = true;
for (offline_brand: MODERN_BRAND_CITY_TIER) {
    if (sanitizedParentMerchantName == offline_brand.toLowerCase()) {
        is_tradi_brand_city_tier = false;
        break;
    }
}
for (offline_brand: MODERN_BRAND_CITY_TIER) {
    if (stringUtils.contains(merchantNameLowerCase, offline_brand.toLowerCase())) {
        is_tradi_brand_city_tier = false;
        break;
    }
}

/*Is tradi brands*/
var is_tradi_trx = false;
for (store_initial: TRADI_DP_BRAND_LIST) {
    if (stringUtils.contains(merchantNameLowerCase, store_initial)) {
        is_tradi_trx = true;
    } 
}

var is_exclude_from_dp = false;
for (store_initial: TRADI_DP_MERCHANT_EXCLUDE) {
    if (stringUtils.contains(merchantNameLowerCase, store_initial)) {
        is_exclude_from_dp = true;
    } 
}

var is_eligible_dp_tradi_trx = false;
if (is_tradi_trx == true && is_exclude_from_dp == false) {
    is_eligible_dp_tradi_trx = true;
    riskMerchantCategoryName = 'average';
}

var is_offline_transaction = false;
var is_offline_edc_transaction = false;
var is_offline_qr_transaction = false;
for (item_cat: itemCategories) {
    var itemCatLowerCase = item_cat.toLowerCase();
    if (itemCatLowerCase == 'offline-store' || itemCatLowerCase == 'offline-transaction'  || itemCatLowerCase == 'offline') {
        is_offline_transaction = true; /* offline-store, trx with promotors can handover */
    }
    if (itemCatLowerCase == 'offline-transaction') {
        is_offline_qr_transaction = true;
    }
    if (itemCatLowerCase == 'offline') {
        is_offline_edc_transaction = true;
    }
}

if(stringUtils.contains(merchantNameLowerCase, 'absolute')) {
  is_offline_transaction = true; /* offline-store, trx with promotors can handover */
  is_offline_qr_transaction = true;
}

var offline_item_category = 'other';
if (is_offline_transaction) {
    offline_item_category = 'non-smartphone'
    if (is_offline_edc_transaction || is_offline_qr_transaction) {
        offline_item_category = 'QR'
    } 
    if (is_smartphone_transaction) {
        offline_item_category = 'smartphone'
        if (is_current_item_offline_whitelisted_item) {
            offline_item_category = 'high-end phone'
        }
    }
}

/*User categorization*/
var EXISTING_USERS_RISK_GRADE = [
    'A',
    'B',
    'C',
    'D',
    'E'
];

/* MUST UPDATE Definition of existing users need to be based on payment */
var is_existing_user = riskGradeOfflineScore > 0;

/* userPromoRiskGrade assignment */
if (is_offline_transaction) {
    userPromoRiskGrade = 'C';
    
    /* Score Reduction on Selected Offline Merchant (risk downgrade) */
    if (is_offline_merchant_downgrade) {
        riskGradeOfflineScore = riskGradeOfflineScore == null ? null : (riskGradeOfflineScore - 50);
        selectedReinforcedScore = selectedReinforcedScore == null ? null : ( selectedReinforcedScore - 50);
    }

      if (is_existing_user) {
        if (offline_item_category == 'smartphone' || offline_item_category == 'high-end phone') {
            /* MUST UPDATE Inconsistencies for offline score between risk query and prod due to scheduling https://reports.indodana.com/queries/24097/source 10% difference in every risk grade refresh date */
            if (hasNonLimitActiveCashLoanContract == true) {
                if (riskGradeOfflineScore >= 521) {userPromoRiskGrade = 'B'}
                if (riskGradeOfflineScore < 521) {userPromoRiskGrade = 'D'}
                if (riskGradeOfflineScore < 470) {userPromoRiskGrade = 'E'}
            } else if (offline_merchant_risk_category_group == 'high risk') {
                if (riskGradeOfflineScore >= 535) {userPromoRiskGrade = 'A'}
                if (riskGradeOfflineScore < 535) {userPromoRiskGrade = 'B'}
                if (riskGradeOfflineScore < 475) {userPromoRiskGrade = 'C'}
                if (riskGradeOfflineScore < 461) {userPromoRiskGrade = 'D'}
                if (riskGradeOfflineScore < 454) {userPromoRiskGrade = 'E'}
            } else {
                if (riskGradeOfflineScore >= 521) {userPromoRiskGrade = 'A'}
                if (riskGradeOfflineScore < 521) {userPromoRiskGrade = 'B'}
                if (riskGradeOfflineScore < 469) {userPromoRiskGrade = 'C'}
                if (riskGradeOfflineScore < 453) {userPromoRiskGrade = 'D'}
                if (riskGradeOfflineScore < 433) {userPromoRiskGrade = 'E'}
            }
        } else if (offline_item_category == 'non-smartphone' || offline_item_category == 'QR') {
            if (riskGradeOfflineScore >= 521) {userPromoRiskGrade = 'A'}
            if (riskGradeOfflineScore < 521) {userPromoRiskGrade = 'B'}
            if (riskGradeOfflineScore < 469) {userPromoRiskGrade = 'C'}
            if (riskGradeOfflineScore < 453) {userPromoRiskGrade = 'D'}
            if (riskGradeOfflineScore < 433) {userPromoRiskGrade = 'E'}
        }
    } else {
        if (offline_item_category == 'smartphone' || offline_item_category == 'high-end phone') {
            /* MUST UPDATE Reinforced score is not based on cached result from BQ2, but current selector rule version */
            if (offline_merchant_risk_category_group == 'high risk') {
                if (selectedReinforcedScore >= 460) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 400) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 380) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 360) {userPromoRiskGrade = 'E'}
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_koperasi_20240405' || selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_no_ewallet_20240912') {
                    if (selectedReinforcedScore >= 560) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 560) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 525) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 493) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'E'}
                }
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_contact_call_20250728') {
                    if (selectedReinforcedScore >= 568) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 568) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 518) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 478) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 442) {userPromoRiskGrade = 'E'}
                }
            } else {
                if (selectedReinforcedScore >= 460) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 400) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 380) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 360) {userPromoRiskGrade = 'E'}
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_koperasi_20240405' || selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_no_ewallet_20240912') {
                    if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 483) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 457) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 431) {userPromoRiskGrade = 'E'}
                }
                if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_contact_call_20250728') {
                    if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                    if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                    if (selectedReinforcedScore < 469) {userPromoRiskGrade = 'C'}
                    if (selectedReinforcedScore < 440) {userPromoRiskGrade = 'D'}
                    if (selectedReinforcedScore < 410) {userPromoRiskGrade = 'E'}
                }
            }
        } else if (offline_item_category == 'non-smartphone' || offline_item_category == 'QR') {
            if (selectedReinforcedScore >= 460) {userPromoRiskGrade = 'A'}
            if (selectedReinforcedScore < 460) {userPromoRiskGrade = 'B'}
            if (selectedReinforcedScore < 400) {userPromoRiskGrade = 'C'}
            if (selectedReinforcedScore < 380) {userPromoRiskGrade = 'D'}
            if (selectedReinforcedScore < 360) {userPromoRiskGrade = 'E'}
            if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_koperasi_20240405' || selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_no_ewallet_20240912') {
                if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 483) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 457) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 431) {userPromoRiskGrade = 'E'}
            }
            if (selectedReinforcedModelName == 'reinforced_pefindo_scoring_cli_offline_contact_call_20250728') {
                if (selectedReinforcedScore >= 543) {userPromoRiskGrade = 'A'}
                if (selectedReinforcedScore < 543) {userPromoRiskGrade = 'B'}
                if (selectedReinforcedScore < 469) {userPromoRiskGrade = 'C'}
                if (selectedReinforcedScore < 440) {userPromoRiskGrade = 'D'}
                if (selectedReinforcedScore < 410) {userPromoRiskGrade = 'E'}
            }
        } 
    }   
}

/* Merchant Risk Based Pricing Rule */
if (riskMerchantCategoryName == 'Bad' || riskMerchantCategoryName == 'Very Bad') {
    rate_key_result = 'offline_transaction290k'
}

/* DO NOT REPLACE THIS SECTION - for addon transaction we will return specific rate group key */
if (merchantId == '9dbbd98c-7777-11ec-ab86-6f31bc08f747') { /* FSP */
    rate_key_result = '1month-12month-no_min_installment-int199';
}

/* aput (INTEGRATION TEAM) UAT risk grade promo  */
if (userId == '6354b3a5-8b5a-49ee-b99d-03a681aeaddc' || userId == 'af0e9f88-ad57-4781-a771-4f52c5a266f1' || userId == '6354b3a5-8b5a-49ee-b99d-03a681aeaddc' || userId == '5159dce1-b88a-45e7-a86a-a372a1250a4f' || userId == '28c47e88-939b-460b-b20f-9d60b0c15c84' || userId == 'e2d719d0-4d55-4997-8890-3f231caf7408'|| userId == '6354b3a5-8b5a-49ee-b99d-03a681aeaddc' || userId == '28c47e88-939b-460b-b20f-9d60b0c15c84' || userId == 'e2d719d0-4d55-4997-8890-3f231caf7408') {
    if(stringUtils.contains(lowerCaseItemNames, 'riska')) {userPromoRiskGrade = 'A'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riskb')) {userPromoRiskGrade = 'B'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riskc')) {userPromoRiskGrade = 'C'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riskd')) {userPromoRiskGrade = 'D'} 
    if(stringUtils.contains(lowerCaseItemNames, 'riske')) {userPromoRiskGrade = 'E'} 
}

if ((masterUserId == null || masterUserId == '') && (userId != null || userId != '')) {
    masterUserId = userId
}

var whitelistedResults = null;
if (masterUserId != null && masterUserId != '') {
  whitelistedResults = blacklistHelper.getWhitelists([
    {"type": 'users', "namespace": 'offline-mp-higher-rate-cde', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'mandatory-dp-offline-mp-higher-rate-cde', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'traditional-mp-eligible-promo', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'traditional-mandatory-dp-offline-mp', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'phase-2-cash-loan-via-limit', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'tiket-additional-approval-higher-pricing', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'above-480-nonmp-downlimit-highrate-experiment', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'below-480-nonmp-downlimit-highrate-experiment', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'risk-reactivation', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'ecommerce-va-payment-auto', "searchField": {"userId": masterUserId}},
    {"type": 'users', "namespace": 'ecommerce-va-payment', "searchField": {"userId": masterUserId}}

  ]);
}

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------ Offline OVERWRITE RBP -------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/

if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
    userPromoRiskGrade = 'E';
}

/*[CHRISTIE] Additional Approval High Risk Erafone Roadside Experiment, rate 3.5% 99k-259k */
/* ------------------------------------------------------------------------------------------------*/
var is_additional_approval_mp_cde = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'offline-mp-higher-rate-cde', {"userId": masterUserId}, whitelistedResults);

/* 
C - admin 199k, bunga 3.49%
D - admin 199k, bunga 3.99%
E - admin 349k, bunga 4.49% 
*/
if (is_additional_approval_mp_cde && userPromoRiskGrade == 'C' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
    isTrxAllowedToUsePromo = false;
}
else if (is_additional_approval_mp_cde && userPromoRiskGrade == 'D' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
    isTrxAllowedToUsePromo = false;
}
else if (is_additional_approval_mp_cde && userPromoRiskGrade == 'E' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    isTrxAllowedToUsePromo = false;
}
else if (is_additional_approval_mp_cde && !['C','D','E'].contains(userPromoRiskGrade)) {
    rate_key_result = merchantCreditRateGroupKey;
    isTrxAllowedToUsePromo = true;
}

/*[CHRISTIE] Additional Approval High Risk Erafone Roadside Experiment, rate 3.5% 99k-259k */
var is_mandatory_dp_additional_approval_mp_cde = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'mandatory-dp-offline-mp-higher-rate-cde', {"userId": masterUserId}, whitelistedResults);

/* 
C - admin 199k, bunga 3.49%
D - admin 199k, bunga 3.99%
E - admin 349k, bunga 4.49%

4 Dec 
C/D/E - admin 349k, bunga 4.49%
*/


if (is_mandatory_dp_additional_approval_mp_cde && userPromoRiskGrade == 'C' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    dp_rate = 0;
    isTrxAllowedToUsePromo = false;
}
else if (is_mandatory_dp_additional_approval_mp_cde && userPromoRiskGrade == 'D' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    dp_rate = 0;
    isTrxAllowedToUsePromo = false;
}
else if (is_mandatory_dp_additional_approval_mp_cde && userPromoRiskGrade == 'E' && is_smartphone_transaction && loanAmount > 1000000) {
    rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
    dp_rate = 0;
    isTrxAllowedToUsePromo = false;
}
else if (is_mandatory_dp_additional_approval_mp_cde && !['D','E'].contains(userPromoRiskGrade)) {
    rate_key_result = merchantCreditRateGroupKey;
    isTrxAllowedToUsePromo = true;
}

/* Non-MP Downlimit Project Higher Rate */
/* ------------------------------------------------------------------------------------------------*/
var above_480_nonmp_downlimit_highrate_experiment = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'above-480-nonmp-downlimit-highrate-experiment', {"userId": masterUserId}, whitelistedResults);

var below_480_nonmp_downlimit_highrate_experiment = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'below-480-nonmp-downlimit-highrate-experiment', {"userId": masterUserId}, whitelistedResults);


/* 
- OFFLINE SET A -

- Identity Above 480++
--- 372++ - 4.60% (6Mio)
--- 407++ - Normal Price (9Mio)
--- 420++ - Normal Price (12.5Mio)

- Identity Below 480++
--- 372++ - 4.60% (6Mio)
--- 410++ - 3.90% (9Mio)
--- 420++ - Normal Price (12.5Mio)

- OFFLINE SET B -

- Identity Above 480++
--- 315++ - 4.60% (6Mio)
--- 361++ - Normal Price (9Mio)
--- 386++ - Normal Price (12.5Mio)

- Identity Below 480++
--- 315++ - 4.60% (6Mio)
--- 376++ - 3.90% (9Mio)
--- 386++ - Normal Price (12.5Mio)
*/

if (above_480_nonmp_downlimit_highrate_experiment || below_480_nonmp_downlimit_highrate_experiment){

    /* - OFFLINE SET A - */
    if (experiment_offline == 'offline_set_a'){

        if (above_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 420) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 407) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 372) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        } else if (below_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 420) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 410) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
                isTrxAllowedToUsePromo = false;
            } else if (selectedReinforcedScore >= 372) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        }
    } 

    /* - OFFLINE SET B - */
    else if (experiment_offline == 'offline_set_b'){
        
        if (above_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 386) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 361) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 315) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        } else if (below_480_nonmp_downlimit_highrate_experiment){

            if (selectedReinforcedScore >= 386) {
                rate_key_result = merchantCreditRateGroupKey;
                isTrxAllowedToUsePromo = true;
            } else if (selectedReinforcedScore >= 376) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_349';
                isTrxAllowedToUsePromo = false;
            } else if (selectedReinforcedScore >= 315) {
                rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
                isTrxAllowedToUsePromo = false;
            }

        }
    }

    if (loanAmount < 1000000){
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
}

/* ==========================================
   CITY TIER ADJUSTMENT & RISK PRICING LOGIC
   ========================================== */

/* * 1. Traditional Brand Base Logic
 * Apply a specific rate (IR 3.49%) for high-risk users (Grade D or E) 
 * associated with traditional brands, regardless of city tier. -- NO OVERRIDE of TRADI DP, and EXTRA AR rule
 */
if (isTrxAllowedToUsePromo == true) {
    if (is_tradi_brand_city_tier && (userPromoRiskGrade == 'D' || userPromoRiskGrade == 'E')) {
        rate_key_result = 'offline_transaction_additional_mp_199k_ir_349';
    } 

    /* * 2. Low-Tier City Pricing Overrides (Tier 4 & 5)
    * Apply stricter pricing rules for merchants located in lower-tier cities.
    */
    if (merchantAddressCityTier == 'TIER_4' || merchantAddressCityTier == 'TIER_5') {
        if (userPromoRiskGrade == 'C') {rate_key_result = 'offline_transaction_additional_mp_199k_ir_349';}    
        if (userPromoRiskGrade == 'D' || userPromoRiskGrade == 'E') {rate_key_result = 'offline_transaction_additional_mp_199k_ir_399';}
    } 

    /* * 3. Risk Grade Penalty / Downgrade
    * If the merchant is in a low-tier city (4 or 5), artificially lower 
    * the user's risk grade by one level (e.g., A becomes B) to lower promo benefit.
    */
    if (merchantAddressCityTier == 'TIER_4' || merchantAddressCityTier == 'TIER_5') {
        if (userPromoRiskGrade == 'A') {userPromoRiskGrade = 'B';}
        else if (userPromoRiskGrade == 'B') {userPromoRiskGrade = 'C';}
        else if (userPromoRiskGrade == 'C') {userPromoRiskGrade = 'D';}
        else if (userPromoRiskGrade == 'D') {userPromoRiskGrade = 'E';}
    }

    if (loanAmount < 1000000){
        rate_key_result = merchantCreditRateGroupKey;
    }
}

/*Tradi Eligible Promo, B and D*/
var submit_traditional_eligible_promo = whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'traditional-mp-eligible-promo', {"userId": masterUserId}, whitelistedResults);

var submit_traditional_mandatory_dp_no_promo = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'traditional-mandatory-dp-offline-mp', {"userId": masterUserId}, whitelistedResults);;


/* 
Submit Tradi Eligible Promo (B/D)
-- new user (pefindo)
510++ - B Treatment
440++ - D Treatment
360++ - D Treatment (set A)
*/

if (submit_traditional_eligible_promo){
    if (selectedReinforcedScore >= 510) {
        userPromoRiskGrade = 'B';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    else if (selectedReinforcedScore >= 440) {
        userPromoRiskGrade = 'D';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    /*Mandatory DP set A*/
    else if (selectedReinforcedScore >= 360) {
        userPromoRiskGrade = 'D';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
}

/*
Submit Tradi No Promo Mandatory DP
-- new user (pefindo)
420++ - admin 199k, bunga 3.49% (set B)
400++ - admin 199k, bunga 3.99% (set B)
360++ - admin 349k, bunga 4.49% (set B)
*/

else if (submit_traditional_mandatory_dp_no_promo){
    /*Mandatory DP set B*/
    if (selectedReinforcedScore >= 420) {
        rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
        dp_rate = 0;
        isTrxAllowedToUsePromo = false;
    }
    else if (selectedReinforcedScore >= 400) {
        rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
        dp_rate = 0;
        isTrxAllowedToUsePromo = false;
    }
    else if (selectedReinforcedScore >= 360) {
        rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
        dp_rate = 0;
        isTrxAllowedToUsePromo = false;
    }

    if (loanAmount < 1000000){
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
        dp_rate = 0;
    }
}

/*
Existing Tradi Eligible Promo (B/D)
-- existing user (offline RG score)
540++ - B Treatment
485++ - D Treatment
0++   - D treatment (set A)

Existing Tradi No Promo Mandatory DP
-- existing user (offline RG score)
460++ - admin 199k, bunga 3.49% (set B)
450++ - admin 199k, bunga 3.99% (set B)
0++ - admin 349k, bunga 4.49% (set B)
*/

else if (is_eligible_dp_tradi_trx && is_existing_user){
    if (riskGradeOfflineScore >= 540) {
        userPromoRiskGrade = 'B' ;
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    else if (riskGradeOfflineScore >= 485) {
        userPromoRiskGrade = 'D';
        rate_key_result = merchantCreditRateGroupKey;
        isTrxAllowedToUsePromo = true;
    }
    else if (mandatory_dp_tradi_experiment == 'set_a'){
        if (riskGradeOfflineScore > 0) {
            userPromoRiskGrade = 'D';
            rate_key_result = merchantCreditRateGroupKey;
            isTrxAllowedToUsePromo = true;
        }
    }
    else if (mandatory_dp_tradi_experiment == 'set_b'){
        if (riskGradeOfflineScore >= 460) {
            rate_key_result = 'offline_transaction_additional_mp_199k_ir_349'; 
            dp_rate = 0;
            isTrxAllowedToUsePromo = false;
        }
        else if (riskGradeOfflineScore >= 450) {
            rate_key_result = 'offline_transaction_additional_mp_199k_ir_399'; 
            dp_rate = 0;
            isTrxAllowedToUsePromo = false;
        }
        else if (riskGradeOfflineScore > 0) {
            rate_key_result = 'offline_transaction_additional_mp_349k_ir_449'; 
            dp_rate = 0;
            isTrxAllowedToUsePromo = false;
        }
    }
}

/* Greylist */
var is_greylist = 
    whitelistedResults != null && blacklistHelper.isWhitelistedByNamespaceAndReasonBulkCheck('users', 'phase-2-cash-loan-via-limit', 'greylist', {"userId": masterUserId}, whitelistedResults);

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* -------------------------------------- VA Transaction RBP --------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
var ab_test_va_rbp = '';
if (is_va_transaction) {
    rate_key_result = merchantCreditRateGroupKey;

    if (is_greylist) {
        rate_key_result = 'va_new_rate_2024_09';
    } else if (sumPaymentVaBeforeTrx <= 0 && hasNonLimitActiveCashLoanContract == true) {
        ab_test_va_rbp = abTestingHelper.getVariation(masterUserId, 'RISK_VA_RBP', 'NORMAL');
        
        if (ab_test_va_rbp == 'HIGHER') {
            rate_key_result = 'va_new_rate_2024_09';
        } 
    } else if (sumPaymentVaBeforeTrx <= 0 && userLastActivitySegment == 'CASH_LOAN') {
        ab_test_va_rbp = abTestingHelper.getVariation(masterUserId, 'RISK_VA_RBP', 'NORMAL');
        if (ab_test_va_rbp == 'HIGHER') {
            rate_key_result = 'va_new_rate_2024_09';
        } 
    } else if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        /*------------------------------------- Reactivated Accounts Higher Price For First 60d -------------------------------*/
        rate_key_result = 'va_new_rate_2024_09';
    } else if ((whitelistedResults != null) && !(blacklistHelper.isWhitelistedBulkCheck('users', 'ecommerce-va-payment', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'va_new_rate_2024_09';
    }
}

/* ------------------------------------------------------------------------------------------------*/


if (userId == 'placeholder' && merchantId == TIKET_MERCHANT_ID) {
    rate_key_result = 'va_new_rate_2024_09';
}

if (merchantId == 'a74697e8-8cd8-11ee-b7ee-a94b5e22674c') {
    dp_rate = 0.3;
}

/*------------------------------------- Override Business Partner / Key Account / VIP ------------------------------------------*/
if (userId == '824633a8-95e4-43d1-b4c1-6befb986ec6d' || userId == '2c4d57e0-5853-4c3a-a886-c67e6b7142b3') {
  userPromoRiskGrade = 'A';
  is_trx_allowed_to_use_promo = true;
  dp_rate = 0;
  rate_key_result = merchantCreditRateGroupKey;
}

/* ---------------------------------------------------------------------------------------*/
/* ---------------------------------------------------------------------------------------*/
/* -------------------------------------- TIKET RBP --------------------------------------*/
/* ---------------------------------------------------------------------------------------*/
/* ---------------------------------------------------------------------------------------*/

/*------------------------------------- TIKET Additional 10% Higher Approval -------------------------------*/
var submit_tiket_additional_approval = 
    whitelistedResults != null && blacklistHelper.isWhitelistedBulkCheck('users', 'tiket-additional-approval-higher-pricing', {"userId": masterUserId}, whitelistedResults);

/* 
Submit Additional 10% Higher Approval
-- new user 365-400(5.2% Flat)
1 month  : 6.59%
3 month  : 5.48%
6 month  : 5.02%
12 month : 4.98%
*/
if (merchantId == TIKET_MERCHANT_ID) {
    rate_key_result = merchantCreditRateGroupKey;

    if (submit_tiket_additional_approval) {
        if ((selectedReinforcedScore >= 365) && (selectedReinforcedScore < 410) ) {
            rate_key_result = 'tiket-additional-approval-higher-pricing-522';
        }
    }

    /*------------------------------------- TIKET Experiment raise 1 month tenure max amount to 3 mio -------------------------------*/
    ab_test_tiket_3mio_1mo = abTestingHelper.getVariation(masterUserId, 'TIKET_1MO_3MIO_EXPERIMENT', 'NORMAL');
    if(ab_test_tiket_3mio_1mo == 'HIGHER') {
        rate_key_result = submit_tiket_additional_approval ? 'tiket-additional-approval-3mio-1mo-522' : 'tiket-paylater-3mio-1mo-experiment';
    }
    /* Yohanes + Rio + Novela testing */
    if ((userId == 'c03454bb-8c64-49d2-ac34-89b529e034e5' || userId == '93bd2d33-81c1-4eec-8ace-706d95b4cf20' || userId == 'b038338b-fe0b-40cc-9beb-aea62054c877') && merchantId == TIKET_MERCHANT_ID) {
        rate_key_result = submit_tiket_additional_approval ? 'tiket-additional-approval-3mio-1mo-522' : 'tiket-paylater-3mio-1mo-experiment';
    }
    /*------------------------------------- Reactivated Accounts Higher Price For First 60d -------------------------------*/
    if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'tiket-paylater-expensive-reactivate';
    }
}
/* ------------------------------------------------------------------------------------------------*/

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ---------------------------------------- E-WALLET RBP ------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
if (merchantId == EWALLET_MERCHANT_ID) {
    rate_key_result = merchantCreditRateGroupKey;

    if(stringUtils.contains(lowerCaseItemNames, 'dana')) {
        rate_key_result = 'stellar-ewallet-expensive-nov25';
    }
    if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'stellar-ewallet-expensive-nov25';
    } else if ((whitelistedResults != null) && !(blacklistHelper.isWhitelistedBulkCheck('users', 'ecommerce-va-payment', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'stellar-ewallet-new-users';
    }
}
/* ------------------------------------------------------------------------------------------------*/

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ---------------------------------------- CERMATI DIGITAL (STELLAR) RBP ------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
if (merchantId == CERMATI_DIGITAL_MERCHANT_ID) {
    rate_key_result = merchantCreditRateGroupKey;

    if ((whitelistedResults != null) && (blacklistHelper.isWhitelistedBulkCheck('users', 'risk-reactivation', {'userId': masterUserId}, whitelistedResults))) {
        rate_key_result = 'va_new_rate_2024_09';
    }
}

/* ------------------------------------------------------------------------------------------------*/

/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ---------------------------------------- BLIBLI RBP ------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
/* ------------------------------------------------------------------------------------------------*/
if (merchantId == BLIBLI_MERCHANT_ID) {
    rate_key_result = merchantCreditRateGroupKey;
}
/* ------------------------------------------------------------------------------------------------*/

/*
Testing user (https://chat.google.com/room/AAAA0s1HhlE/Tkchx0x8fo8/M-7g-d7Gx9o?cls=10)
*/
if (userPhoneNumber == '+6281519346572' || userPhoneNumber == '+6281519712364' || userPhoneNumber == '+6281519276802') {
    rate_key_result = merchantCreditRateGroupKey;
}

return {
    "rate_group_key": rate_key_result,
    "user_promo_risk_grade": userPromoRiskGrade,
    "is_trx_allowed_to_use_promo": isTrxAllowedToUsePromo,
    "is_existing_user": is_existing_user,
    "is_offline_transaction": is_offline_transaction,
    "offline_item_category": offline_item_category,
    "mandatory_dp_rate": dp_rate,
    "offline_merchant_tag":offline_merchant_tag,
    "offline_merchant_risk_category":offline_merchant_risk_category,
    "offline_merchant_risk_category_group":offline_merchant_risk_category_group,
    "ab_test_va_rbp": ab_test_va_rbp,
    "risk_grade_offline_score" : riskGradeOfflineScore,
    "mandatory_dp_tradi_experiment" : mandatory_dp_tradi_experiment,
    "is_smartphone_transaction" : is_smartphone_transaction,
    "experimentOffline": experiment_offline,
    "selectedReinforcedModelName" : selectedReinforcedModelName,
    "selectedReinforcedScore" : selectedReinforcedScore,
    "whitelistedResults" : whitelistedResults
};